### ISSUE TITLE
Allow Mob Heads to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [itsmeow/betteranimalsplus#101]
`Forge v28.1.44`
`Minecraft v1.14.4`
~~`Extended Caves v7.1.2`~~ 
`Better Animals Plus v7.1.2`

Currently, Mob Heads cannot be waterlogged. Allowing this would add more immersion to the game.
![2019-10-11_22 39 45](https://user-images.githubusercontent.com/12000593/66694427-c7925f00-ec78-11e9-828e-4a27a57c534f.png)

**Comment by itsmeow** [comment]
I think you meant Better Animals Plus 7.1.2, lol
Definitely! I will see about waterlogging (although I am not sure how in 1.14 yet), for all animal heads as well as the hand of fate!

**Comment by WenXin20** [comment]
Oops, copy and paste mistakes!
