### ISSUE TITLE
World Gen Crash

### ISSUE THREAD

**Issue by EightBlade** [itsmeow/betteranimalsplus#102]
**Describe what you were doing before the crash**
Spawning a new world.

**To Reproduce** (Required unless unknown)
Log into that world.

**Crash Log (REQUIRED)**

https://paste.dimdev.org/apawufemiz.mccrash

**Versions:**
 - Forge Version: 14.23.5.2847
 - MC Version: 1.12.2
 - Mod Version: 7.1.1?

**Comment by itsmeow** [comment]
Looks like the boar is eating crops before the world is loaded. Easy fix. Should work if you re-generate the world, random chance is a factor here.
