### ISSUE TITLE
Crash when placing Mob heads on tall grass

### ISSUE THREAD

**Issue by Partonetrain** [itsmeow/betteranimalsplus#103]
**Describe what you were doing before the crash**
Testing things in creative

**To Reproduce** (Required unless unknown)
Steps to reproduce the behavior (if possible):
1. Get mob head
2. Try to place on top of tall grass (possibly other two-block-tall blocks)
3. See error

**Crash Log (REQUIRED)**
https://pastebin.com/8x9u66jm

**Versions:**
 - Forge Version: 28.1.42 (same crash happens on forge .61)
 - MC Version: 1.14.4
 - Mod Version: 7.1.2

**Additional context**
Happens with all heads. Head faces upwards if placed on bottom block, but doesn't crash.

**Comment by itsmeow** [comment]
So wait, when you place on the top block of a two block tall grass, placing on one of the sideways directions it crashes? Or placing on top of the two block tall top block?

**Comment by Partonetrain** [comment]
This was caused by placing it on the side, I haven't tried placing it on top face, I will later today. 

No idea why it tries to place the block facing downward when I'm placing it from the side. 

There's logic in the class in question to prevent it from being placed downward but somehow it still happens https://github.com/itsmeow/betteranimalsplus/blob/1.14/src/main/java/its_meow/betteranimalsplus/common/item/ItemBlockSkull.java

**Comment by Partonetrain** [comment]
Placing mob heads on the top face of tall grass does nothing
