### ISSUE TITLE
[FEATURE] Thaumcraft 6 Aspects

### ISSUE THREAD

**Issue by DoomRater** [itsmeow/betteranimalsplus#105]
I want to kill all the things with vats of Liquid Death and get vis appropriate vis crystals from them. IE's Chemical Thrower loaded with Liquid Death and the Essense Harvester Infusion Enchantment also use these aspects to cause mobs to drop vis crystals on death.

I'd make them myself, or accept a list of aspects already added by the community, if that's possible.  Mostly I want continuity between created lists and other mods.

**Comment by Sunconure11** [comment]
I can send over a pull with this.

Meow’s done quite a bit for me but I haven’t done much for him.

This should also be really easy to set up.

**Comment by itsmeow** [comment]
Update on this @Sunconure11 ?

**Comment by Sunconure11** [comment]
Sleep did a fucked

**Comment by Sunconure11** [comment]
Working on this now.

https://cdn.discordapp.com/attachments/494803762087591949/647562965733736459/unknown.png
