### ISSUE TITLE
Lampreys randomly dying

### ISSUE THREAD

**Issue by 6ix9ine2** [itsmeow/betteranimalsplus#107]
In the newest version of the mod, after getting sucked by a lamprey, even after killing it, every time after landing with elytra after flying for long enough to cause wear on it, a lamprey spawns in and instantly dies. You don't take any damage, but it is fairly startling.

**Comment by itsmeow** [comment]
Please follow the issue format. What MC version, mod version, etc.

**Comment by itsmeow** [comment]
Managed to reproduce this in 1.12, and I've fixed it. We'll see.

**Comment by lamoyrl90** [comment]
I'm experiencing this issue still, version 1.12.2-8.1.1.

**Comment by KydZombie** [comment]
I am also still experiencing this issue on 1.12.2-9.0.1

**Comment by itsmeow** [comment]
1.12 is no longer supported for bugfixes, so the chances of this being resolved are near 0. You can ask @bglandolt to add it to [Better Animals Plus Plus](https://www.curseforge.com/minecraft/mc-mods/better-animals-plus-plus), perhaps.
