### ISSUE TITLE
No vanilla agressive mob spawning [1.12.2]

### ISSUE THREAD

**Issue by RutraNickers** [itsmeow/betteranimalsplus#112]
**Description**
There was no vanilla agressive mob spawning in the Overworld.

**To Reproduce**
Was using this mod with ExoticBirds in a new generated world (at start with Normal Dificulty, later with Hard Dificulty). No vanilla agressive mobs spawned as far as I knew, even in night and caves. When I removed BetterAnimalsPlus, they came back as normal. In a Creative World for test I use with flat/vanillaRedstone configuration, there was vanilla agressive mobs spawning during bad weather as usual.

**Expected behavior**
I expected near normal vanilla agressive mob spawn during night and inside caves.

**Versions:**
 - Forge Version: 14.23.5.2847
 - MC Version: 1.12.2
 - Mod Version: 1.12.2-6.0.3

**Comment by itsmeow** [comment]
I have no idea what precisely would cause this as we have only one `MONSTER` type spawn, the tarantula, and they only spawn in deserts. Sounds like something else is afoot. Anything in the logs?

**Comment by itsmeow** [comment]
Closing unless something else comes up. Feel free to re-open.
