### ISSUE TITLE
NullPointerException on dismountZotz [1.12.2]

### ISSUE THREAD

**Issue by Orygeunik** [itsmeow/betteranimalsplus#125]
**Describe what you were doing before the crash**
Wait in "home" some time (client was minimized), and unexpectedly client was crashed

**To Reproduce**
1. Connect to my server;
1. Do some work;
1. End some work and wait some time;
1. Get unexpected crash

**Crash Log (REQUIRED)**
[Synopsis of crash-log (on gist.github)](https://gist.github.com/Orygeunik/08507c523b871de3db9da17bb1feefcc)

**Short Log**
``` Log
> Caused by: java.lang.NullPointerException
> 	at its_meow.betteranimalsplus.common.entity.EntityZotzpyre.dismountZotz(EntityZotzpyre.java:220) ~[EntityZotzpyre.class:?]
> 	at its_meow.betteranimalsplus.common.entity.EntityZotzpyre.func_70097_a(EntityZotzpyre.java:284) ~[EntityZotzpyre.class:?]
```

**Versions:**
 - Forge Version: Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3
 - MC Version: Minecraft Version: 1.12.2
 - Mod Version: betteranimalsplus-1.12.2-8.1.0

**Additional context**
On server no any logs about it

**Comment by mxnmnm** [comment]
here's my crash it looks like it's somewhat similar so it may be caused by the same issue
https://paste.dimdev.org/doteriloga.mccrash

**Comment by Orygeunik** [comment]
Hm...
After 3+ hours of AFK on server, new crash not have been yet... I don't know what is init this crash

**Comment by mxnmnm** [comment]
I wasn't afk when I crashed although they seem like the same one

**Comment by Dabombber** [comment]
I'm getting this as well, seems to happen to me when I kill a zotzpyre while it's mounted on me.

**Comment by itsmeow** [comment]
Can I get that log too?

**Comment by Dabombber** [comment]
Happens at the same place. https://gist.github.com/Dabombber/904b68490de330da6f20cc4b32e35303

**Comment by itsmeow** [comment]
Pretty obvious to me now what's causing this. Easy patch but takes a bit to get sorted for me (holidays and such, lol)

**Comment by Lordbaane** [comment]
https://paste.dimdev.org/livafiguwa.mccrash
Seems to be a similiar issue.

**Comment by kellixon** [comment]
My FPS too is Down (1.12.2/8.1.0). Zotzpyre loads the world and consequently low fps (laggoogles - 20100ms).

**Comment by Aeron216** [comment]
Here to report the same. 
Running 8.1.0

Interestingly enough only the clients have been crashing, the server that we run and where we play has never crashed.
I'll try to upload a log as soon as I get back to my PC.

**Comment by itsmeow** [comment]
Working on it currently, no need for more logs. Although I'm not sure about the low FPS issue, I'd report that separately @kellixon. Any sort of debug stacktraces would also be useful (I believe you can profile methods within LagGoggles??) Screenshots of laggoggles menu would be nice too.

**Comment by itsmeow** [comment]
Patch is up :) 1.12.2-8.1.1

**Comment by kellixon** [comment]
![javaw_2019_12_24_17_15_47_556](https://user-images.githubusercontent.com/22012731/71416364-185b0680-2671-11ea-92e4-c9c5f370a5f5.jpg)
With the old version of the mod, everything is working smoothly with a new picture twitches and fps drops. I'm staying on the old version for now.
