### ISSUE TITLE
No creatures spawning with OTG Biome Bundle

### ISSUE THREAD

**Issue by Gavin456b** [itsmeow/betteranimalsplus#128]
I do not have any Better Animals Plus mobs spawning when I use OTG Biome bundle except the giant bats and lamprey, in the past it was working just fine together but now for some reason it doesnt. I have tried regenerating the config but it has not worked.

**Comment by itsmeow** [comment]
Hey this report is missing some info like versions and also are your logs showing anything? Can you post your config so I can see if it's generating properly?

**Comment by Gavin456b** [comment]
Sorry, here is my log and config file
[2020-01-01-1.log](https://github.com/itsmeow/betteranimalsplus/files/4016755/2020-01-01-1.log)
[betteranimalsplus.cfg.txt](https://github.com/itsmeow/betteranimalsplus/files/4016758/betteranimalsplus.cfg.txt)

**Comment by itsmeow** [comment]
I don't see any problems, odd

**Comment by anqingchen** [comment]
I had that issue as well on my server with biome bundle. It was a conflict with InControl mod.

**Comment by Gavin456b** [comment]
Odd, well I dont have the InControl mod. Perhaps I will try jacking up the spawn weights
