### ISSUE TITLE
Hi! I want to help to translate this Mod! :D

### ISSUE THREAD

**Issue by Zethn** [itsmeow/betteranimalsplus#129]
**Language:**
Spanish.
**Are you able to translate to this language?**
Yes.
**If not, do you know anyone that speaks this language?**
Yes, all of my city and country.

**Comment by itsmeow** [comment]
Heyo, Spanish is currently up to date so we're not currently looking for much help. Is there anything specific you found missing/incorrect?

**Comment by Zethn** [comment]
Oh, in the CurseForge Page says: Out of dated

**Comment by itsmeow** [comment]
Ah yeah, sorry I forget to update that a lot

**Comment by Zethn** [comment]
Oh, well, i love this mod, and, if you need help in the spanish translation, i'll be there! :D

**Comment by itsmeow** [comment]
Alright thanks :) Closing this for now! I think you're in the discord so I'll throw you a DM if we need anything
