### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by SirHaxe** [itsmeow/betteranimalsplus#130]
**Language:**
German
**Are you able to translate to this language?**
Yep
**If not, do you know anyone that speaks this language?**

**Comment by itsmeow** [comment]
Hi, our German translation is currently only missing Zotzpyre and Bobbit Worm, is there anything else you've noticed specifically missing?

**Comment by SirHaxe** [comment]
i didnt see anything, (cause i cant play > server hoster did not update forge yet) only the "out of Date" on forge!

**Comment by itsmeow** [comment]
If you could throw me translations for those two I can add them! "Zotzpyre" basically means "bat god" + "pire/pyre" which is taken from "vampire"

probably just leave it as it is because it's not a real word
as for bobbit worm, that is definitely translatable!
