### ISSUE TITLE
zotzpyre group size?

### ISSUE THREAD

**Issue by Yourname942** [itsmeow/betteranimalsplus#133]
**Describe the bug** (Required)
In the nether, the groups of zotzpyre are way too massive

**To Reproduce** (Required unless not known)
1) go to the nether
2) fly around until you find zotzpyre
3) there will be dozens of zotzpyre

**Log output/error (if present)**
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/4054127/latest.log)

**Expected behavior** (Required)
For only a few zotzpyre will spawn, but a massive amount spawn instead

**Screenshots**
![2020-01-13_09 37 09](https://user-images.githubusercontent.com/58750222/72265251-3372c380-35ea-11ea-9b89-418e8aa71cec.png)

![2020-01-13_09 37 13](https://user-images.githubusercontent.com/58750222/72265275-3b326800-35ea-11ea-869d-59545e745496.png)

**Versions:**
 - Forge Version: 14.23.5.2847
 - MC Version: 1.12.2
 - Mod Version: betteranimalsplus-1.12.2-8.1.1.jar

**Additional context**
Even after adjusting the weight to 1, they still spawn in large groups:
`entityzotzpyre {
                    # True to despawn this entity when no one is nearby [default: true]
                    B:allowDespawning=true

                    # Disables natural spawning [default: true]
                    B:doSpawning=true

                    # Must be greater or equal to min value! [range: 1 ~ 9999, default: 1]
                    I:maxGroup=1

                    # Must be greater than 0 [range: 1 ~ 9999, default: 1]
                    I:minGroup=1

                    # Enter biome Resource Locations. Supports modded biomes. [default: [biomesoplenty:dead_swamp], [minecraft:taiga_hills], [minecraft:mutated_redwood_taiga_hills], [twilightforest:twilight_glacier], [midnight:obscured_peaks], [biomesoplenty:temperate_rainforest], [biomesoplenty:marsh], [biomesoplenty:gravel_beach], [defiledlands:ice_plains_defiled], [twilightforest:twilight_highlands], [minecraft:forest], [minecraft:mutated_roofed_forest], [biomesoplenty:flower_island], [biomesoplenty:overgrown_cliffs], [minecraft:mutated_mesa], [minecraft:birch_forest], [biomesoplenty:woodland], [minecraft:redwood_taiga_hills], [minecraft:mutated_taiga_cold], [biomesoplenty:lush_desert], [biomesoplenty:lush_swamp], [minecraft:mutated_jungle_edge], [minecraft:mutated_jungle], [twilightforest:mushroom_forest], [minecraft:swampland], [minecraft:taiga_cold], [minecraft:mutated_ice_flats], [midnight:warped_fields], [midnight:hilly_fungi_forest], [defiledlands:swamp_defiled], [minecraft:extreme_hills_with_trees], [twilightforest:deep_mushroom_forest], [biomesoplenty:orchard], [midnight:fungi_forest], [twilightforest:dense_twilight_forest], [midnight:deceitful_bog], [midnight:obscured_plateau], [minecraft:mutated_savanna_rock], [minecraft:mutated_mesa_clear_rock], [twilightforest:snowy_forest], [minecraft:cold_beach], [twilightforest:oak_savannah], [minecraft:roofed_forest], [biomesoplenty:mystic_grove], [aether:aether_arctic_peaks], [defiledlands:forest_vilespine], [minecraft:jungle], [minecraft:mutated_birch_forest_hills], [biomesoplenty:redwood_forest_edge], [biomesoplenty:white_beach], [midnight:runebush_grove], [biomesoplenty:tundra], [biomesoplenty:phantasmagoric_inferno], [biomesoplenty:land_of_lakes], [twilightforest:spooky_forest], [biomesoplenty:xeric_shrubland], [biomesoplenty:coniferous_forest], [biomesoplenty:snowy_forest], [biomesoplenty:origin_beach], [biomesoplenty:dead_forest], [biomesoplenty:mountain_foothills], [biomesoplenty:grassland], [biomesoplenty:sacred_springs], [twilightforest:firefly_forest], [minecraft:desert_hills], [biomesoplenty:flower_field], [biomesoplenty:moor], [biomesoplenty:seasonal_forest], [minecraft:mushroom_island_shore], [minecraft:mutated_swampland], [aether:aether_irradiated_forests], [biomesoplenty:tropical_island], [biomesoplenty:glacier], [biomesoplenty:eucalyptus_forest], [minecraft:beaches], [biomesoplenty:volcanic_island], [minecraft:birch_forest_hills], [twilightforest:enchanted_forest], [twilightforest:fire_swamp], [biomesoplenty:maple_woods], [biomesoplenty:redwood_forest], [minecraft:mutated_mesa_rock], [twilightforest:dark_forest_center], [biomesoplenty:bog], [biomesoplenty:oasis], [biomesoplenty:cherry_blossom_grove], [biomesoplenty:mangrove], [biomesoplenty:grove], [midnight:hilly_vigilant_forest], [minecraft:mutated_extreme_hills], [aether:aether_magnetic_hills], [twilightforest:twilight_forest], [minecraft:mutated_savanna], [minecraft:mutated_taiga], [minecraft:forest_hills], [minecraft:extreme_hills], [minecraft:jungle_hills], [twilightforest:thornlands], [biomesoplenty:snowy_tundra], [minecraft:jungle_edge], [biomesoplenty:fen], [minecraft:ice_mountains], [twilightforest:dark_forest], [biomesoplenty:crag], [biomesoplenty:mountain], [thaumcraft:magical_forest], [minecraft:stone_beach], [biomesoplenty:bamboo_forest], [biomesoplenty:ominous_woods], [biomesoplenty:wetland], [minecraft:taiga_cold_hills], [biomesoplenty:meadow], [minecraft:ice_flats], [defiledlands:hills_defiled], [minecraft:mutated_birch_forest], [biomesoplenty:rainforest], [biomesoplenty:shield], [minecraft:taiga], [biomesoplenty:boreal_forest], [biomesoplenty:alps_foothills], [minecraft:mutated_forest], [biomesoplenty:snowy_coniferous_forest], [defiledlands:forest_tenebra], [midnight:vigilant_forest], [biomesoplenty:lavender_fields], [biomesoplenty:undergarden], [biomesoplenty:tropical_rainforest], [twilightforest:highlands_center], [biomesoplenty:alps], [biomesoplenty:highland], [biomesoplenty:quagmire], [minecraft:redwood_taiga], [biomesoplenty:wasteland], [biomesoplenty:bayou], [minecraft:smaller_extreme_hills], [midnight:black_ridge], [twilightforest:twilight_swamp], [minecraft:mutated_extreme_hills_with_trees], [biomesoplenty:origin_island], [minecraft:mutated_redwood_taiga]]
                    S:spawnBiomes <
                        biomesoplenty:dead_swamp
                        minecraft:taiga_hills
                        minecraft:mutated_redwood_taiga_hills
                        twilightforest:twilight_glacier
                        midnight:obscured_peaks
                        biomesoplenty:temperate_rainforest
                        biomesoplenty:marsh
                        biomesoplenty:gravel_beach
                        defiledlands:ice_plains_defiled
                        twilightforest:twilight_highlands
                        minecraft:forest
                        minecraft:mutated_roofed_forest
                        biomesoplenty:flower_island
                        biomesoplenty:overgrown_cliffs
                        minecraft:mutated_mesa
                        minecraft:birch_forest
                        biomesoplenty:woodland
                        minecraft:redwood_taiga_hills
                        minecraft:mutated_taiga_cold
                        biomesoplenty:lush_desert
                        biomesoplenty:lush_swamp
                        minecraft:mutated_jungle_edge
                        minecraft:mutated_jungle
                        twilightforest:mushroom_forest
                        minecraft:swampland
                        minecraft:taiga_cold
                        minecraft:mutated_ice_flats
                        midnight:warped_fields
                        midnight:hilly_fungi_forest
                        defiledlands:swamp_defiled
                        minecraft:extreme_hills_with_trees
                        twilightforest:deep_mushroom_forest
                        biomesoplenty:orchard
                        midnight:fungi_forest
                        twilightforest:dense_twilight_forest
                        midnight:deceitful_bog
                        midnight:obscured_plateau
                        minecraft:mutated_savanna_rock
                        minecraft:mutated_mesa_clear_rock
                        twilightforest:snowy_forest
                        minecraft:cold_beach
                        twilightforest:oak_savannah
                        minecraft:roofed_forest
                        biomesoplenty:mystic_grove
                        aether:aether_arctic_peaks
                        defiledlands:forest_vilespine
                        minecraft:jungle
                        minecraft:mutated_birch_forest_hills
                        biomesoplenty:redwood_forest_edge
                        biomesoplenty:white_beach
                        midnight:runebush_grove
                        biomesoplenty:tundra
                        biomesoplenty:phantasmagoric_inferno
                        biomesoplenty:land_of_lakes
                        twilightforest:spooky_forest
                        biomesoplenty:xeric_shrubland
                        biomesoplenty:coniferous_forest
                        biomesoplenty:snowy_forest
                        biomesoplenty:origin_beach
                        biomesoplenty:dead_forest
                        biomesoplenty:mountain_foothills
                        biomesoplenty:grassland
                        biomesoplenty:sacred_springs
                        twilightforest:firefly_forest
                        minecraft:desert_hills
                        biomesoplenty:flower_field
                        biomesoplenty:moor
                        biomesoplenty:seasonal_forest
                        minecraft:mushroom_island_shore
                        minecraft:mutated_swampland
                        aether:aether_irradiated_forests
                        biomesoplenty:tropical_island
                        biomesoplenty:glacier
                        biomesoplenty:eucalyptus_forest
                        minecraft:beaches
                        biomesoplenty:volcanic_island
                        minecraft:birch_forest_hills
                        twilightforest:enchanted_forest
                        twilightforest:fire_swamp
                        biomesoplenty:maple_woods
                        biomesoplenty:redwood_forest
                        minecraft:mutated_mesa_rock
                        twilightforest:dark_forest_center
                        biomesoplenty:bog
                        biomesoplenty:oasis
                        biomesoplenty:cherry_blossom_grove
                        biomesoplenty:mangrove
                        biomesoplenty:grove
                        midnight:hilly_vigilant_forest
                        minecraft:mutated_extreme_hills
                        aether:aether_magnetic_hills
                        twilightforest:twilight_forest
                        minecraft:mutated_savanna
                        minecraft:mutated_taiga
                        minecraft:forest_hills
                        minecraft:extreme_hills
                        minecraft:jungle_hills
                        twilightforest:thornlands
                        biomesoplenty:snowy_tundra
                        minecraft:jungle_edge
                        biomesoplenty:fen
                        minecraft:ice_mountains
                        twilightforest:dark_forest
                        biomesoplenty:crag
                        biomesoplenty:mountain
                        thaumcraft:magical_forest
                        minecraft:stone_beach
                        biomesoplenty:bamboo_forest
                        biomesoplenty:ominous_woods
                        biomesoplenty:wetland
                        minecraft:taiga_cold_hills
                        biomesoplenty:meadow
                        minecraft:ice_flats
                        defiledlands:hills_defiled
                        minecraft:mutated_birch_forest
                        biomesoplenty:rainforest
                        biomesoplenty:shield
                        minecraft:taiga
                        biomesoplenty:boreal_forest
                        biomesoplenty:alps_foothills
                        minecraft:mutated_forest
                        biomesoplenty:snowy_coniferous_forest
                        defiledlands:forest_tenebra
                        midnight:vigilant_forest
                        biomesoplenty:lavender_fields
                        biomesoplenty:undergarden
                        biomesoplenty:tropical_rainforest
                        twilightforest:highlands_center
                        biomesoplenty:alps
                        biomesoplenty:highland
                        biomesoplenty:quagmire
                        minecraft:redwood_taiga
                        biomesoplenty:wasteland
                        biomesoplenty:bayou
                        minecraft:smaller_extreme_hills
                        midnight:black_ridge
                        twilightforest:twilight_swamp
                        minecraft:mutated_extreme_hills_with_trees
                        biomesoplenty:origin_island
                        minecraft:mutated_redwood_taiga
                     >

                    # The spawn chance compared to other animals (typically between 6-20) [range: 1 ~ 9999, default: 10]
                    I:weight=1
                }`

Here is my modpack:
[Test 1-1.0.0.zip](https://github.com/itsmeow/betteranimalsplus/files/4054179/Test.1-1.0.0.zip)

At the moment I have to disable zotzpyre from spawning because they're too many of  them.

**Comment by itsmeow** [comment]
This has been resolved in the 1.14 development branch and will be released eventually (on 1.12 as well)
