### ISSUE TITLE
Fix buggy Lammergeiers in 1.14+

### ISSUE THREAD

**Issue by BlueWither** [itsmeow/betteranimalsplus#146]
**Is your feature request related to a problem? Please describe.**
The bearded eagle's AI is quite buggy, difficult to tame, and does not work well when displayed like a zoo.

**Describe the solution you'd like**
I felt that there would be something in the settings to make their AI the same as a little bird.
However, it is better to use traditional AI only when it finds an enemy.

**Comment by itsmeow** [comment]
Planning on working on this for the next update hopefully.
