### ISSUE TITLE
Translation of wolf heads

### ISSUE THREAD

**Issue by Smollet777** [itsmeow/betteranimalsplus#151]
**Describe the bug**
Translation in lang file exists but not applying

**To Reproduce**
1. Switch to russian language;
2. Search for "head" or vice versa "голова"

**Screenshots**
![image](https://user-images.githubusercontent.com/41921653/76960045-5f306380-6923-11ea-91a6-5ec3062d9afb.png)

**Versions:**
 - OS: Windows
 - MC Version: 1.14.4
 - Mod Version: betteranimalsplus-1.14.4-8.2.1.39

**Comment by itsmeow** [comment]
You are using an alpha version, the translations that exist are no longer relevant because the item ID was changed. The translation will have to be updated. Alpha versions are also NOT supported on GitHub. All issues should be reported in discord.

**Comment by itsmeow** [comment]
I've resolved this in #150 and merged it.
