### ISSUE TITLE
Too Many Fresh Water Eels

### ISSUE THREAD

**Issue by mxnmnm** [itsmeow/betteranimalsplus#156]
**Describe the bug**
Eel mania

**To Reproduce**
1. Find river
2. meet giant hoard of fresh water eels

**Expected behavior**
A reasonable amount of fresh water eels

**Screenshots**
![2020-04-04_17 10 35](https://user-images.githubusercontent.com/8508976/78463892-739c8c00-7697-11ea-8b70-24dc08c5abdd.png)
![2020-04-04_16 57 34](https://user-images.githubusercontent.com/8508976/78463893-75fee600-7697-11ea-852d-4e2b1527465e.png)
![2020-04-04_16 57 35](https://user-images.githubusercontent.com/8508976/78463894-77301300-7697-11ea-9b1b-e49a55eaf2f6.png)
![2020-04-04_17 07 43](https://user-images.githubusercontent.com/8508976/78463895-78614000-7697-11ea-9c83-261de0e3f475.png)
![2020-04-04_19 12 04](https://user-images.githubusercontent.com/8508976/78465263-3ab8e300-76a8-11ea-9f5c-f7b0c5f3de2a.png)

**Versions:**
 - OS: Windows 10
 - MC Version: 1.12.2
 - Mod Version: 9.0.0

**Additional context**
Heavily modded instance

**Comment by mxnmnm** [comment]
https://pastebin.com/4DChcDEA here is the mod list

**Comment by Sereath** [comment]
Here to report the same issue, so far however it has only been happening inside the Twilight Forest.

![image](https://user-images.githubusercontent.com/54506307/78508970-54156a00-7750-11ea-832d-97474b729f2a.png)
![image](https://user-images.githubusercontent.com/54506307/78508976-5bd50e80-7750-11ea-9ab8-a6a3a4a80dbd.png)


First thing I did after noticing the issue was to delete the config file and try with a new world but unfortunately it kept happening with every single new world.

MC 1.12.2
On version 9.0.0

Modlist:

https://pastebin.com/jP5zJGdt

**Comment by mxnmnm** [comment]
for now you can use incontrol to limit the spawning but yea a fix would be nice for those who don't want to use it

**Comment by mxnmnm** [comment]
[  {
    "mob": "betteranimalsplus:eel_freshwater",
    "maxcount": {
      "amount": 3,
      "mob": "betteranimalsplus:eel_freshwater",
      "perchunk": true
    },
    "result": "allow"
  },
  {
    "mob": "betteranimalsplus:eel_freshwater",
    "result": "deny"
  }]

**Comment by mxnmnm** [comment]
in the spawn.json for incontrol and you should be set lol

**Comment by itsmeow** [comment]
You can literally lower spawns in our configuration, InControl is not needed. I will possibly lower the natural rate, but this issue is eliminated by the mod itself using configuration.

**Comment by itsmeow** [comment]
I will admit that is a bit weird. I'll set the max per chunk to 3 in code. This reminds me of the ancient lammergeier overspawning bug, that pesky thing took forever to eliminate and I don't even know how I did it.

**Comment by SjetCraft** [comment]
Can confirm issue in [Poetica](https://www.curseforge.com/minecraft/modpacks/poetica). Thousands of Freshwater Eels spawn in uncontrollably.
https://imgur.com/a/J5Z5snI
