### ISSUE TITLE
Spice of Life Compat

### ISSUE THREAD

**Issue by mxnmnm** [itsmeow/betteranimalsplus#157]
This is more of a compat issue with spice of life where whenever you eat turkey (the kind you place on the ground) it doesn't get registered as a different food type.

**Comment by itsmeow** [comment]
Does SOL register cakes? We use similar code to the cake to feed the player from slices.

**Comment by mxnmnm** [comment]
Yes it registers cakes and in fact I remember in 1.7 it didn't register pam's cakes but in 1.12 they did

**Comment by itsmeow** [comment]
This is a such a minor issue and 1.12 is EoL, no content updates, so I'm closing. I think the world will survive with SoL not affecting a fairly rare turkey block.
