### ISSUE TITLE
Whale sounds

### ISSUE THREAD

**Issue by mxnmnm** [itsmeow/betteranimalsplus#162]
How can you add whales without whale sounds ;-;

**Comment by matheusvingadouro** [comment]
they haven't added sounds for whales, turkeys and etc because they can't find COPYRIGHT-FREE sounds... please find some and share with them if you can

**Comment by cybercat5555** [comment]
As stated above, this is since we are having trouble finding clean sounds we can legally use, we do want to add sounds, but see above. Closing this as it is not an issue.

**Comment by mxnmnm** [comment]
Oh ok I'll search for some :)

**Comment by mxnmnm** [comment]
Alright so I can edit this if you want just tell me which time stamps you want and I can upload it somewhere for you :)
https://hitrecord.org/records/2430638

**Comment by cybercat5555** [comment]
Those are not the correct type of whale. Please instead join our discord if you want to further discuss this
