### ISSUE TITLE
Adding a standart config (Request)

### ISSUE THREAD

**Issue by KnifeOfDunwall** [itsmeow/betteranimalsplus#164]
it would be nice to have something similar to carryon´s solution where there is a file in configs that gets used as a template for generating the serverconfig so that you don´t need to change the config every time you create a new world

**Comment by itsmeow** [comment]
This is a thing. If you read the FAQ, Forge has a built-in feature where you can place the server config in a folder called "defaultconfigs" and it will automatically place it in new worlds.
