### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by footwanterfin** [itsmeow/betteranimalsplus#168]
[fi_fi.txt](https://github.com/itsmeow/betteranimalsplus/files/4601402/fi_fi.txt)

Corrected one thing.

**Comment by footwanterfin** [comment]
I tried to submit it as a json file but that didn't work.

**Comment by itsmeow** [comment]
By the way would appreciate a `lang` format version of this (from 1.12 branch) so I can merge that too when next patch cycle comes around. I can probably throw one together but I don't trust myself to get it right.
