### ISSUE TITLE
Tamed Feral Wolf Bug 1.14.4 Semi-Solved?

### ISSUE THREAD

**Issue by Disasterjane** [itsmeow/betteranimalsplus#171]
_I tried looking up the terms wolf, wolves, etc. to try and make sure this wasn't posted before. So I apologize if this issue has already been addressed._

Hello! My friends and I started using this mod a few days ago. We host a private server on Aternos.org  (It's only compatible we certain versions of forge and mods, because of whatever is added to the site)

My one friend logged in today and saw that her feral wolves were all moving around BUT sitting while doing so. She couldn't get them to sit, stand, or even drag them along using a lead and flying in creative mode. (The lead just stretches while the wolf stays put.) 

No other wolves were affected _yet_. The only thing of possible notice is that they stood up and walked around upon me joining the server.

After helping her tie down her wolves, we decided to close out of and restart the server. We came in and now **MY** feral wolves were having the same issue. 

Currently without restarting the server again. We have 2/3 players having this bug with our tamed wolves. The coyotes we have do not seem to be affected by this currently.

Edit mid post: I AFK'd while writing this, and my wolves returned to standing. My one friend AFK'd and they returned to normal, but i figured I'd still post this incase its something that can be addressed or at least be used to help others, and we don't know if it'll comeback or if others will have problems with that without that fixing it. Sorry if this is kinda spamy due to this. 

We are running the following (literally writing down the .jar name):
Forge  (1.14.4-forge-28.2.0)

- betteranimalsplus-1.14.4-9.0.1  
- BiomesOPlenty-1.14.4-9.0.0.262-universal  [link](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
- cfm-7.0.0-pre15-mc1.14.4  [link](https://mrcrayfish.com/mods?id=cfm)
- comforts-FORGE-1.14.4-2.0-beta6 [link](https://www.curseforge.com/minecraft/mc-mods/comforts)
- optifine_1.14.4_HD_U_F5  [link](https://optifine.net/home)

Thank you for reading, it isn't quite game-breaking but it is an issue we would really like to see help with or fixed if possible. ^^

**Comment by itsmeow** [comment]
I think this is caused by network desync on datamanager fields due to bad connections or slow server.
