### ISSUE TITLE
Interacting with coyotes causes a crash?

### ISSUE THREAD

**Issue by Willbound** [itsmeow/betteranimalsplus#176]
**Describe what you were doing before the crash**
I was building my house then my friends found a Coyote and tried to feed it, we also have a mod that let's you pet wolves, maybe that could be an issue?

**To Reproduce**
Steps to reproduce the behavior (if possible):
1. Spawn 'Coyote'
2. Interact
3. Crash

**Crash Log (REQUIRED)**
https://pastebin.com/pfyZxVQi

**Versions:**
 - OS: Windows Home
 - MC Version: 1.12.2
 - Mod Version: 8.2.1 BETA 96

Mod list:
https://pastebin.com/UifA5bWf

**Comment by itsmeow** [comment]
Duplicate of #174
