### ISSUE TITLE
[1.15.2] shark render ctd

### ISSUE THREAD

**Issue by IchigoGames** [itsmeow/betteranimalsplus#177]
walking around building near water 

minecraft 1.15.2
Forge 31.2.0
betteranimalsplus-1.15.2-8.2.1.96

**To Reproduce**
Steps to reproduce the behavior (if possible):
building near water do have optfine and shaders

https://pastebin.com/wcJ2UvTb

**Versions:**
 - OS: [e.g. Windows, Mac, Linux (include distribution)]
 - MC Version:
 - Mod Version:

**Additional context**

**Comment by itsmeow** [comment]
Duplicate of #165
