### ISSUE TITLE
crash on dedicated server [forge-1.15.2-31.2.9]

### ISSUE THREAD

**Issue by SDUBZ** [itsmeow/betteranimalsplus#178]
**Describe the bug**
[02:23:18] [Server thread/ERROR] [ne.mi.fm.co.ConfigFileTypeHandler/]: Failed to remove config ./world/serverconfig/betteranimalsplus-server.toml from tracker!
java.lang.NullPointer

**To Reproduce**
have a dedicated server with mod 
server crashes trying to remove a config

**Expected behavior**
to be able to explore without it crashing my server

**Screenshots**

**Versions:**
 - OS: [e.g. Windows 10
 - MC Version: 1.15.2
 - Mod Version: betteranimalsplus-1.15.2-8.2.1.96

**Additional context**
crash report:
[crash-2020-06-15_02.23.17-server.txt](https://github.com/itsmeow/betteranimalsplus/files/4779306/crash-2020-06-15_02.23.17-server.txt)

logs:

[debug.log](https://github.com/itsmeow/betteranimalsplus/files/4779303/debug.log)

[latest.log](https://github.com/itsmeow/betteranimalsplus/files/4779302/latest.log)

**Comment by itsmeow** [comment]
Everything I can find about this issue implies it's connected to something else. The log error at the end about BA+ configs is not connected to it. I don't think this is a BA+ issue.
