### ISSUE TITLE
whales crash  singleplayer and server[1.15.2-31.2.20]

### ISSUE THREAD

**Issue by SDUBZ** [itsmeow/betteranimalsplus#179]
Forge: 1.15.2-31.2.20

betteranimals: betteranimalsplus-1.15.2-8.2.1.96

i dicovered this many times just by even summoning the whale

[latest.log](https://github.com/itsmeow/betteranimalsplus/files/4786378/latest.log)

**Comment by itsmeow** [comment]
There's no crashes in that log. None.

**Comment by SDUBZ** [comment]
why did it output to game console but not in log wuttt

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/4789909/latest.log)
[crash-2020-06-17_11.55.17-client.txt](https://github.com/itsmeow/betteranimalsplus/files/4789910/crash-2020-06-17_11.55.17-client.txt)

**Comment by itsmeow** [comment]
Duplicate of #165
