### ISSUE TITLE
Dead eel spawning in area

### ISSUE THREAD

**Issue by plolil** [itsmeow/betteranimalsplus#183]
**Describe the bug**
Whenever I go within some range of when an eel initially latched onto me after being outside of this radius(presumably the mob loading radius) a dead eel spawns on me and goes up in a puff of smoke, dealing no damage and dropping nothing.

**To Reproduce**
1. Get an eel to latch onto you
2. Go a few chunks away.
3. Walk back towards where you initially had the eel latch on.
4. A dead eel should appear on you and play its death animation.

**Log output/error (if present)**
Get your minecraft log and paste it here.

**Expected behavior**
No dead eel to appear from nowhere

**Screenshots**
![ezgif com-optimize](https://user-images.githubusercontent.com/55294289/85775117-6384cd80-b717-11ea-9a98-8084e85f7755.gif)

**Versions:**
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2847
 - Mod Version: 1.12.2-9.0.1

**Additional context**
When the eel initially died, it was due to being outside of water, not a swing from the player.
The radius could be around where the eel died, I'm uncertain on this, but that was in a similar location to where the eel first attacked me.
@EliteMeats#5734 on discord has also experienced the same bug.

at the end of this video I point in the direction of where I had the initial encounter.

**Comment by itsmeow** [comment]
We've had this before and still don't know what causes it. Relogging should remove the dead eel however.

**Comment by ghost** [comment]
I'm so sorry for my question that doesn't fit this issue, but...
What is the white outline on your last heart on the gif?
Is this a certain mod and if yes so what does in do?

**Comment by itsmeow** [comment]
Official solution is just relog. Some weird networky-minecraft cause is behind this but I've tried fixing it 4 separate times and it always comes back.
