### ISSUE TITLE
Are zotzpyre meant to flap their wings?

### ISSUE THREAD

**Issue by katubug** [itsmeow/betteranimalsplus#184]
**Describe the bug**
I'm not sure whether this is intended, but zotzpyre do not flap their wings while gliding. I do get the impression that because they only glide, this may be intentional, but it looks...odd. Particularly with the weird way that MC handles turning entities, it makes them look a bit buggy.

**To Reproduce**
1. Spawn a zotzpyre
2. Observe it until it decides to glide to a lower surface

**Expected behavior**
I expected a flapping motion. Or, failing that, some sort of wing movement to indicate gliding (such as a billow in the webbing, maybe?).

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 31.2.27 (also occurs in .28)
 - Mod Version: 8.2.1.96.

**Comment by itsmeow** [comment]
Not really a bug per se... could do something about it but we're removing the Zotzpyre and moving it to our other mod Whisperwoods for the final 1.15 release, so either way problem solved lol

**Comment by katubug** [comment]
Rad, sounds awesome! I'll be sure to check out the new mod as well, thank
you!
