### ISSUE TITLE
1.15.2 Server Crash on Load

### ISSUE THREAD

**Issue by MokahTGS** [itsmeow/betteranimalsplus#185]
Getting a crash loading the server.

**Crash Log (REQUIRED)**
https://pastebin.com/7FyaybF1

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: forge-1.15.2-31.2.27
 - Mod Version: betteranimalsplus-1.15.2-8.2.1.96

**Additional context**
Full mod list: https://pastebin.com/F4xVDSWA

**Comment by itsmeow** [comment]
This crash log doesn't have a useful error. I would need the full server log.
