### ISSUE TITLE
1.15.2 Server/User Crashes when releasing BAP Entity from Ender Lasso/Mob Imprisonment Tool

### ISSUE THREAD

**Issue by SayulilyonPipeDream** [itsmeow/betteranimalsplus#186]
**Describe the bug**
It looks like there is an issue with "Bottling" entities from BAP to move them to a different area. We currently run this mod with Industrial Foregoing and Apotheosis. Whenever a player attempts to catch or release a BAP entity, be it songbird, goat, etc; the player and server crash, and the player cannot join with the entity in their inventory.
In a best-case scenario, the player crashes, keeps the entity bottler, and the entity is lost forever.

**To Reproduce**
1) Have Better Animals Plus with Apotheosis or Industrial Foregoing
2) Enjoy the adorable animals in Better Animals Plus and want to bring them home!
3) Use Apotheosis' Ender-Lead or IF's Mob Pokeball on said cute animal
4) Crash

**Log output/error (if present)**
Log!
[crash-2020-05-29_20.47.55-server.txt](https://github.com/itsmeow/betteranimalsplus/files/4894357/crash-2020-05-29_20.47.55-server.txt)

**Expected behavior**
Catch and Release with an Entity Bottler like the Mob Imprisonment tool or Ender-Lead

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 31.2.31
 - Mod Version:  8.2.1.118

**Comment by itsmeow** [comment]
This crash log is for a crash in some mod called  "Titanium"

**Comment by itsmeow** [comment]
Closing unless more info is given.
