### ISSUE TITLE
[1.15.2] Songbirds dont fly they just hover in place

### ISSUE THREAD

**Issue by Peach774** [itsmeow/betteranimalsplus#188]
**Describe the bug**
Birds dont fly - they just sit on the ground or in the air.

**To Reproduce**
1. Find a bird
2. See Bird
3. Bird doesnt fly or really move at all

**Expected behavior**
Birds should fly and flee when attacked

**Screenshots**
![image](https://user-images.githubusercontent.com/5171184/87455214-f21f9880-c5b9-11ea-8759-a7c0bf969712.png)

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 31.2.31
 - Mod Version: 8.2.1.96

**Comment by itsmeow** [comment]
I can't really tell from the image you sent, but you're sure that's a BA+ songbird? It's too small for me to make it out in the image

**Comment by SDUBZ** [comment]
This actually happens alot
have you tested your mod outside the dev enviroment ?

**Comment by itsmeow** [comment]
It appears to work fine, testing it now. May be a problem with that specific build. But it should work in the newer builds (I'll be pushing a version out sometime soon)
