### ISSUE TITLE
1.15.2 crash while afk standing

### ISSUE THREAD

**Issue by Jergeric** [itsmeow/betteranimalsplus#193]
**Describe what you were doing before the crash**
be standing at AFK

**To Reproduce**
I stood around afk and was the only one on the server at the time

**Crash Log (REQUIRED)**
[crash-2020-08-07_16.23.03-client.txt](https://github.com/itsmeow/betteranimalsplus/files/5042101/crash-2020-08-07_16.23.03-client.txt)

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 31.2.36
 - Mod Version: 8.2.1.96

**Comment by itsmeow** [comment]
Duplicate of #165
