### ISSUE TITLE
Compatibility issue with the Tiny Mob Farm lasso

### ISSUE THREAD

**Issue by SilentWolf101** [itsmeow/betteranimalsplus#194]
**Describe the bug**
I can capture a BAP mob in the Tiny Mob Farms lasso (does not matter which mob), and I can place it inside a tiny mob farm just fine to passively get loot, but if I try to place the mob back down on the ground like a normal Minecraft mob, it causes the player to crash and the mob to be deleted. 

**To Reproduce**
1. Have both BAP and tiny mob farms installed. 
2. Start up any world, singleplayer or multiplayer. 
3. Capture any BAP mob in a lasso. 
4. Try to place the mob back onto the ground. 
5. See error. 

**Log output/error (if present)**
> [31Jul2020 19:08:22.685] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: SilentWolfy101 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
> [31Jul2020 19:08:22.685] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: SilentWolfy101 left the game
> [31Jul2020 19:08:23.077] [Server thread/ERROR] [net.minecraft.world.chunk.storage.ChunkSerializer/]: An Entity type net.minecraft.entity.EntityType@24f70060 has thrown an exception trying to write state. It will not persist. Report this to the mod author
> java.lang.NullPointerException: null
> 	at net.minecraft.nbt.StringNBT.func_229705_a_(StringNBT.java:40) ~[?:?]
> 	at net.minecraft.nbt.CompoundNBT.func_74778_a(CompoundNBT.java:145) ~[?:?]
> 	at its_meow.betteranimalsplus.common.entity.util.IVariantTypes.writeType(IVariantTypes.java:37) ~[?:8.2.1.96]
> 	at its_meow.betteranimalsplus.common.entity.util.abstracts.EntityAnimalWithTypes.func_184198_c(EntityAnimalWithTypes.java:30) ~[?:8.2.1.96]
> 	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1309) ~[?:?]
> 	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:302) ~[?:?]
> 	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:684) ~[?:?]
> 	at net.minecraft.world.server.ChunkManager.lambda$scheduleSave$10(ChunkManager.java:411) ~[?:?]
> 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_101]
> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_101]
> 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_101]
> 	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:393) [?:?]
> 	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:370) [?:?]
> 	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:342) [?:?]
> 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:313) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Expected behavior**
The mob will appear on the ground in front of the player after being placed. 

**Screenshots**
With the mob in the lasso: 
![image](https://user-images.githubusercontent.com/19398802/89663901-8a482f00-d893-11ea-88b5-c58ad87fb9f9.png)
After trying to place the mob on the ground: 
![image](https://user-images.githubusercontent.com/19398802/89663773-4c4b0b00-d893-11ea-8379-8630b86e5f52.png)

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 1.15.2.31.2.21
 - Mod Version: 1.15.2.8.2.1.96 

**Additional context**
 - Tiny Mob Farm Version: 1.15.2-1.0.6.1
I also have the animal nets mod (because I wanted a safe way to transport the animals), and I usually have no issues when attempting to place a mob back onto the ground with those nets. I opened this issue with the Tiny Mob Farms mod, and they told me it was an issue with this mod and to come here instead. Do let me know if you need any more information. The server itself does not crash, but it spits out an error in the latest log. The player may rejoin just fine but without the animal.

**Comment by itsmeow** [comment]
This was fixed in our newer development builds under commit 276c28957e1f68b7b11ecd0c5d14824706f52ce0
