### ISSUE TITLE
1.16.1 betteranimalplus crash

### ISSUE THREAD

**Issue by iWisd0M5d** [itsmeow/betteranimalsplus#196]
**Describe what you were doing before the crash**
I use a item a crash the server and when i enter again it say server close when its turn on

**To Reproduce**
I put the white head with horns and crash my game

Crash Log
https://pastebin.com/56gAUazK

 - Minecraft Version: 1.16.1
 - Forge Version: 1.16.1
 - Mod Version: 1.16.1

I love this mod

**Comment by itsmeow** [comment]
You've put the wrong versions. Your Forge version is 32.0.108 and your mod version is 9.0.1.3. Also it says this crash is caused by a lamprey, not a Hirschgeist Skull.

**Comment by iWisd0M5d** [comment]
what a lamprey and what version i should use?

**Comment by itsmeow** [comment]
No, I'm saying you've written the wrong versions, I'm telling you which ones are correct.
 -   Minecraft Version: 1.16.1
 -  Forge Version: 32.0.108
 -  Mod Version: 9.0.1.3

Those are the correct ones. For future reference.
A lamprey is an animal in this mod. The Hirschgeist Skull (horn head) is not was appears to have caused this crash.

**Comment by iWisd0M5d** [comment]
those where the versions i had its there anyway to turn off the lamprey one in case i want to use it and dont crash?

**Comment by itsmeow** [comment]
You can use the configuration

**Comment by iWisd0M5d** [comment]
what configuration you talking about?

**Comment by itsmeow** [comment]
Read the FAQ.

**Comment by iWisd0M5d** [comment]
where i can find that FAQ?

**Comment by itsmeow** [comment]
https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus

**Comment by iWisd0M5d** [comment]
this its what only appear in my files 	[entities.reindeer]
		#Set to false to disable snow particles around reindeer.
		create_snow = true
nothing else

**Comment by itsmeow** [comment]
Wrong one.

**Comment by iWisd0M5d** [comment]
that the only config that appear for me

**Comment by itsmeow** [comment]
READ. THE. FAQ.

**Comment by itsmeow** [comment]
There's also a huge comment at the top of that client config you pasted.

**Comment by iWisd0M5d** [comment]
ok ill check out and let you know

**Comment by iWisd0M5d** [comment]
ok i put false everything related to lamprey ill test it out and let you know
