### ISSUE TITLE
1.12.2 Invisible Whales

### ISSUE THREAD

**Issue by KarmaDeb** [itsmeow/betteranimalsplus#197]
**Describe the bug**
Some mobs (big ones) are invisible

**To Reproduce**
1. Spawn 'any big mob'

**Log output/error (if present)**
https://pastebin.com/vbvAZMkg

**Versions:**
 - Minecraft Version: 1.12.2
 - Forge Version: latest forge [1.12.2 - 14.23.5.2854]
 - Mod Version: 9.0.1

**Additional context**
Other mods:
AutoRegLib
BetterCaves
BetterFoliage
BetterMineshafts
BetterNether
BiomesOPlenty
Blur
CreativeCore
DynamicSurroundings
DynamicSurroundingsHud
DynamicTrees
DynamicTreesBiomesOPlenty
Forgelin
iChunUtil
Ido
MobAmputations
MobDismemberment
Optifine[F6]
OreLib
Quark
QuarkOddities
RandomPatches
RoguelikeDungeons
SoundFilters
SoundReloader
Tumbleweed

**Comment by KarmaDeb** [comment]
Edit:

It only occurs when the mob is under water

**Comment by itsmeow** [comment]
Does this occur without Optifine? Also, what's your graphics card?

**Comment by KarmaDeb** [comment]
> Does this occur without Optifine? Also, what's your graphics card?

I didn't test it without optifine, I have an AMD RADEON RX590

**Comment by itsmeow** [comment]
If you could, please try it without Optifine

**Comment by KarmaDeb** [comment]
> If you could, please try it without Optifine

Yes, it keeps happening

NOTE: Even removing all the other mods, it keeps happening

**Comment by Redoaz** [comment]
Hey,

it happens for me too.
hope this information serves good

Forge 1.12

running mods as this setup https://www.youtube.com/watch?v=DnGn4d-rrj8

thought it was Zawa mod not running properly it is better animals plus showing entities with no textures I believe.
I can see mobs hp and walk around but they are invisible.

my setup:
TLauncher: Forge 1.12
online play: disabled
Optifine F5 on/off

I3 8100
GTX 1060 3GB
8GB RAM 2400 mhz

W10

**Comment by itsmeow** [comment]
Is this only the whales?

**Comment by Redoaz** [comment]
sorry to bother you with that previous statement it was a wrong character on the mod.jar name specifically mocreatures.jar I don't think it has anything to do with this one

edit1: I just removed the '+' character from the filename and the all mobs from said jar loaded properly

**Comment by itsmeow** [comment]
I meant the original issue, glad you got that fixed though.

**Comment by itsmeow** [comment]
@KarmaConfigs Does this issue only affect whales or have you noted it on anything else?

**Comment by KarmaDeb** [comment]
> @KarmaConfigs Does this issue only affect whales or have you noted it on anything else?

This issue affected to any "giant" mob on water, the shadow was there, so I guess the mob wasn't disappearing

**Comment by itsmeow** [comment]
Do you know *specifically* that it affected anything other than whales?

**Comment by KarmaDeb** [comment]
> Do you know _specifically_ that it affected anything other than whales?

I didn't tested it with all the animals, all I can say is that I tested with 3-4 big animals and all they disappeared

**Comment by itsmeow** [comment]
The only big animals in the mod in 1.12 are the whale and the moose, so I'm a bit confused here.

**Comment by KarmaDeb** [comment]
> The only big animals in the mod in 1.12 are the whale and the moose, so I'm a bit confused here.

I had this issue a long time ago, maybe the only animals I was having issues with were there two
