### ISSUE TITLE
Lammergeier Flight Buggy

### ISSUE THREAD

**Issue by somebodyandnobody** [itsmeow/betteranimalsplus#200]
The lammergeier is really buggy. Its flying is driving me crazy because it just hovers in thin air. Its also trying to stand on tall grass and sitting while flying (?)

Can you please work on it's AI? Everything in the mod is well made, and it makes me sad to see this thing behaving this way.

**Comment by itsmeow** [comment]
It has been patched in development and will release with v10

**Comment by somebodyandnobody** [comment]
Ok, thanks
