### ISSUE TITLE
Walrus trying to ride a null vehicle?

### ISSUE THREAD

**Issue by Coji4000** [itsmeow/betteranimalsplus#201]
Unsure entirely if this is a better animals crash but I have a ticking entity which the crash report shows as a walrus.  The issue doesn't appear to be the walrus itself its a null pointer vehicle... I honestly... I just don't know. Crash log attached. I thought it may be relative to issue #165 but it doesnt give the render error.

To reproduce, wander around aimlessly. Sorry I don't have better steps. I know this is a shot in the dark. feel free to close if no one else is having similar issues :/
[crash-2020-09-14_21.56.48-server.txt](https://github.com/itsmeow/betteranimalsplus/files/5222072/crash-2020-09-14_21.56.48-server.txt)

**Comment by Coji4000** [comment]
well this just happened with a minecraft:pig so I dont think this is an issue for better animals. sorry for the bother. Thanks for the great mod!

**Comment by itsmeow** [comment]
This crash is caused by the performant coremod.
