### ISSUE TITLE
Low monster spawn rate with better animals plus installed

### ISSUE THREAD

**Issue by ToserBan** [itsmeow/betteranimalsplus#204]
Hi, when i install better animals plus, the monster spawn rate is very low. I can walk during the whole nighttime without getting spotted by monsters. I tried to set the spawn weights in the better animals plus config to 1/5 of the original setting, but that didnt help. I love the new animals, but i cant make my modpack too easy with almost no zombies and skeletons. 
I tested it on my modpack Tosers spacecraft with MC 1.12.2 and forge 14.23.5.2854
Any ideas ?

greetings
Toser Ban

**Comment by itsmeow** [comment]
Please include the template information of the issue. It exists for a reason.

**Comment by ToserBan** [comment]
I don´t know where to find the template. I use betteranimalsplus-1.12.2-9.0.1.jar, do you need more informations ?

**Comment by itsmeow** [comment]
The template is there when you create a bug report using the new issues form. I presume you clicked the empty template or you deleted it. But yes, that's enough information. Do you have InControl installed? It may interfere with spawning. It could also be another animal/entity mod. Minecraft's spawning system isn't built for a lot of entities being registered. Especially in 1.12.

**Comment by ToserBan** [comment]
I havent incontrol installed, but some other mods, which spawn creatures: Abyssalcraft, Primal Core, Aquatic and animalium. But only if i delete betteranimalsplus, the monster spawn rate seems to be normal. Abyssalcraft for example spawns only mobs in their special biomes or in shoggoths lairs, aquatic only spawns some angler fish in oceans, primal core didnt spawned anything at land since 2 hours of testing and animalium spawned very rare packs of wild dogs or rats while betteranimalsplus spawns animals everywhere, not too much in my opinion, but maybe too much for reaching the spawn cap of minecraft.

**Comment by dazadazu** [comment]
Did you resolve this issue? I've tried turning natural despawn on and all the spawn rates to 1-2. What did you do?

**Comment by itsmeow** [comment]
No, I haven't done anything related to this issue. I have no way of figuring out what causes it and it's for 1.12 which I don't really work on anymore.
