### ISSUE TITLE
Crash When feeding coyote phesant or chicken

### ISSUE THREAD

**Issue by GGeza** [itsmeow/betteranimalsplus#209]
**Describe what you were doing before the crash**
I was feeding coyote pheasant and it crashed, same thing happens when feeding chicken.

**To Reproduce**
Steps to reproduce the behavior (if possible):
1. Feed coyote
2. Server crash

**Crash Log (REQUIRED)**
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 27/10/20 10:37 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: its_meow.betteranimalsplus.common.entity.EntityCoyote.func_70908_e(Z)V
	at its_meow.betteranimalsplus.common.entity.EntityCoyote.func_184645_a(EntityCoyote.java:181) ~[?:8.2.1.96] {re:classloading}
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:985) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1067) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:68) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2258376632 bytes (2153 MB) / 4185391104 bytes (3991 MB) up to 4185391104 bytes (3991 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xmx4G -Xms4G
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.30
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 DONE}
		SilentMechanisms-1.15.2-0.7.6+57.jar Silent's Mechanisms {silents_mechanisms@0.7.6+57 DONE}
		Industrial Agriculture[Core]-1.15.2-1.7.0.jar Industrial Agriculture {industrialagriculture@1.15.2-1.7.0 DONE}
		strawgolem-1.15.2-1.7.1.jar Straw Golem {strawgolem@1.15.2-1.7.1 DONE}
		essentials-1.15.2-2.7.3.jar Essentials {essentials@1.15.2-2.7.3 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		NamePain-1.15.2-Forge-1.2.3.jar Name Pain {namepain@1.2.3 DONE}
		theloader-1.15.2-1.1.0.jar The Loader {theloader@1.15.2-1.1.0 DONE}
		u_team_core-1.15.2-3.0.0.160.jar U Team Core {uteamcore@3.0.0.160 DONE}
		randompatches-1.15.2-1.22.0.0.jar RandomPatches {randompatches@1.15.2-1.22.0.0 DONE}
		buildinggadgets-3.3.5.jar Building Gadgets {buildinggadgets@3.3.5 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		refinedstorage-1.8.6.jar Refined Storage {refinedstorage@1.8.6 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		useful_backpacks-1.15.2-1.10.1.66.jar Useful Backpacks {usefulbackpacks@1.10.1.66 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		Industrial Agriculture[Silent's Mechanisms]-1.15.2-1.6.0.jar Industrial Agriculture Plugin-Silent's Mechanisms {iapsm@1.15.2-1.6.0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		mining_dimension-1.15.2-1.0.4.jar Mining World {mining_dimension@1.15.2-1.0.4 DONE}
		SilentGear-1.15.2-1.7.5+106.jar Silent Gear {silentgear@1.7.5+106 DONE}
		simplefarming-1.15.2-1.2.9.jar Simple Farming {simplefarming@1.15.2-1.2.9 DONE}
		MysticalAdaptations-1.15.2-1.2.jar Mystical Adaptations {mysticaladaptations@NONE DONE}
		MysticalAgradditions-1.15.2-3.0.1.jar Mystical Agradditions {mysticalagradditions@3.0.1 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Patchouli-1.15.2-1.2-34.jar Patchouli {patchouli@1.15.2-1.2-34 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		NaturesAura-28.2.jar Nature's Aura {naturesaura@28.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		the_bumblezone-1.15.2-1.3.6.jar The Bumblezone {the_bumblezone@1.15.2-1.3.6 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		Cucumber-1.15.2-3.0.8.jar Cucumber Library {cucumber@3.0.8 DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		FallingTree-1.15.2-2.1.4.jar Falling Tree {falling_tree@2.1.4 DONE}
		fishtraps-forge-1.15.2-0.0.5.jar Fish Traps {fishtraps@1.14.4-0.0.4 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		KiwiBirds-1.1.jar Kiwi Birds {kiwibirds@1.1 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		goldenhopper-1.1.1-1.15.2.jar Golden Hopper {goldenhopper@1.1.1 DONE}
		light-overlay-4.7.0.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		FruitTrees-1.15.2-1.4.1.jar Fruit Trees {fruittrees@1.4.1 DONE}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 DONE}
		VanillaTweaks-1.15.2.1.5.27.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.27 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		JEITweaker-1.0.1.jar JEI Tweaker {jeitweaker@1.0.1 DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.30-universal.jar Forge {forge@31.2.30 DONE}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 DONE}
		MysticalAgriculture-1.15.2-3.0.8.jar Mystical Agriculture {mysticalagriculture@3.0.8 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.30-server.jar Minecraft {minecraft@1.15.2 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		SilentLib-1.15.2-4.6.4+56.jar Silent Lib {silentlib@4.6.4+56 DONE}
		morevanillalib-1.15.2-1.2.2.jar MoreVanillaLib {morevanillalib@1.2.2 DONE}
		MiscAdditions-1.2.3.jar Misc Additions {miscadditions@1.2.3 DONE}
		JAOPCA-1.15.2-3.2.0.11.jar JAOPCA {jaopca@3.2.0.11 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		performant-1.15-2.11m.jar Performant {performant@2.11m DONE}
		vanillahammers-1.15.2-2.1.jar Vanilla Hammers {vanillahammers@2.1 DONE}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
		PickleTweaks-1.15.2-4.0.4.jar Pickle Tweaks {pickletweaks@4.0.4 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		Aquaculture-1.15.2-2.0.16.jar Aquaculture 2 {aquaculture@1.15.2-2.0.16 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.1 DONE}
		refinedstorageaddons-0.6.2.jar Refined Storage Addons {refinedstorageaddons@0.6.2 DONE}
		SolarGeneration-1.15.2-1.2.2.jar Solar Generation {solargeneration@1.2.2 DONE}
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Player Count: 2 / 20; [ServerPlayerEntity['willllllc'/229, l='world', x=-290.85, y=64.00, z=56.51], ServerPlayerEntity['GnarGabaLord'/657, l='world', x=-214.09, y=64.00, z=271.77]]
	Data Packs: vanilla, inmemory:jaopca (incompatible), mod:netherportalfix (incompatible), mod:refinedpipes, mod:doggytalents (incompatible), mod:mcwwindows, mod:silents_mechanisms (incompatible), mod:industrialagriculture (incompatible), mod:strawgolem (incompatible), mod:essentials (incompatible), mod:placebo (incompatible), mod:namepain, mod:theloader (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:buildinggadgets (incompatible), mod:progressivebosses, mod:mcwdoors, mod:morpheus (incompatible), mod:mekanismgenerators, mod:waila (incompatible), mod:snowrealmagic, mod:refinedstorage (incompatible), mod:mcwbridges, mod:usefulbackpacks, mod:ambientsounds (incompatible), mod:iapsm (incompatible), mod:biomesoplenty, mod:phosphor, mod:blur (incompatible), mod:valhelsia_structures (incompatible), mod:mining_dimension, mod:silentgear (incompatible), mod:simplefarming, mod:mysticaladaptations (incompatible), mod:mysticalagradditions, mod:curios (incompatible), mod:patchouli (incompatible), mod:cloth-config2 (incompatible), mod:oreexcavation (incompatible), mod:libnonymous (incompatible), mod:elevatorid, mod:obfuscate (incompatible), mod:naturesaura (incompatible), mod:cfm (incompatible), mod:aiimprovements (incompatible), mod:mcwfurnitures, mod:the_bumblezone, mod:fastleafdecay, mod:inventorysorter (incompatible), mod:cucumber, mod:mining_helmet (incompatible), mod:jei (incompatible), mod:falling_tree, mod:fishtraps (incompatible), mod:abnormals_core, mod:buzzierbees, mod:kiwibirds, mod:goblintraders, mod:mekanism, mod:waystones (incompatible), mod:goldenhopper, mod:lightoverlay-forge (incompatible), mod:journeymap (incompatible), mod:naturescompass (incompatible), mod:fruittrees, mod:kiwi, mod:vanillatweaks, mod:betteranimalsplus (incompatible), mod:snowundertrees (incompatible), mod:bonsaitrees2, mod:jeitweaker, mod:crafttweaker (incompatible), mod:swampexpansion (incompatible), mod:forge (incompatible), mod:waddles (incompatible), mod:mysticalagriculture, mod:ironchest, mod:craftingtweaks (incompatible), mod:endergetic (incompatible), mod:swingthroughgrass (incompatible), mod:mousetweaks (incompatible), mod:silentlib (incompatible), mod:morevanillalib, mod:miscadditions, mod:jaopca (incompatible), mod:gravestone, mod:autumnity, mod:autoreglib (incompatible), mod:quark, mod:storagedrawers (incompatible), mod:performant (incompatible), mod:vanillahammers, mod:midnight, mod:pickletweaks, mod:appleskin (incompatible), mod:aquaculture, mod:iapmekanism, mod:refinedstorageaddons (incompatible), mod:solargeneration, the_loader/SGear-Basic-Metals-v1.3.zip
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 31.2.30
 - Mod Version: 1.15.2-8.2.1.96

**Additional context**
I am using New Beginnings Mod Pack 2.4.2

**Comment by itsmeow** [comment]
This bug was fixed in 10.0.0, but HR New Beginnings has an old version and causes this crash. Please update your pack or yell at the pack makers.
