### ISSUE TITLE
Still having same issues faq doesn't help

### ISSUE THREAD

**Issue by victre151** [itsmeow/betteranimalsplus#212]
![1606018313273802664635972792661](https://user-images.githubusercontent.com/74846338/99893524-f9813d80-2c4e-11eb-8a59-e27258328c7e.jpg)
^^this is literally all that's in the config folder if it helps im using the twitch launcher so the mod was downloaded from curseforge

**Comment by itsmeow** [comment]
You need to load a world first, not just the game. Please stop making new issues. Join the Discord if you have more problems.
