### ISSUE TITLE
Shark biting renders weird

### ISSUE THREAD

**Issue by BugmanBugman** [itsmeow/betteranimalsplus#228]
**Describe the bug**
Title, it looks a bit odd and glitched out. if this is intended then i'll close it. I just wasn't sure since i haven't seen any photos of the sharks in action.
**To Reproduce**
1. get bit by a shark
2. observe it

**Log output/error (if present)**
Get your minecraft log and paste it here.

**Expected behavior**
for it to not look odd

**Screenshots**
![2021-01-01_14 43 15](https://user-images.githubusercontent.com/40730042/103448343-0a659b80-4c5e-11eb-822a-ad6997a39ea3.png)

**Versions:**
 - Minecraft Version: 1.16.4
 - Forge Version: 35.1.28
 - Mod Version: 10.1.0

**Comment by itsmeow** [comment]
That's how it should look. They open their mouths and then mount you onto them
