### ISSUE TITLE
BAP Wont load 1.15

### ISSUE THREAD

**Issue by erk682000** [itsmeow/betteranimalsplus#229]
Downloaded series of mods with 1.15.2 Forge
Some mods allow the startup to go through, after that gives a crash. Others wont allow startup to happen at all

**To Reproduce**
Steps to reproduce the behavior (if possible):
1. Open Minecraft Launcher
2. Click Play
3. Depending on mods, early loading process will either start or crash
4. 

**Crash Log (REQUIRED)**
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/5767974/latest.log)

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 1.15.2
 - Mod Version: 1.15

**Additional context**

**Comment by itsmeow** [comment]
Your versions are all wrong. The mod version OUR mod version not the minecraft version, which I couldn't find in the log but I assume it's the latest (10.1.0). The Forge version is the version of Forge, not the minecraft version. Your log says you have forge 31.2.0, you need to update to the latest forge 1.15 version.
