### ISSUE TITLE
Request for animal meats / products to have forge tags in 1.16

### ISSUE THREAD

**Issue by SodiumShine** [itsmeow/betteranimalsplus#235]
Please consider adding forge tags for all the meats/ingredients that can be obtained from animals. This would allow them to work well with cooking mods.

**Comment by itsmeow** [comment]
Yep! This has been on my radar, but it keeps slipping out of my mind before updates. Will make sure to get this done for the next one :)

**Comment by itsmeow** [comment]
If you could, I'm not sure that I have the time to go through all this stuff.
Could you make a list of some sort with tags you think would be fitting?

You can look at the tags Pam's HC uses here:
https://github.com/MatrexsVigil/phc2foodcore-1.16.3/tree/main/src/main/resources/data/forge/tags/items

I don't know what other mods you want tags from, so let me know, please!
We can also make new tags for like our own meat types, etc (like how Pam's has tags for Pork specifically)

**Comment by SodiumShine** [comment]
Honestly this is a little beyond me, I'm not super familiar with how tags work beyond "oh so this recipe accepts any stock_ingredients".
Also, I think it might be somewhat debatable what some things could be tagged as? Like my personal belief is for the sheer sake of compatibility you could tag pheasant as chicken and venison as beef but I know some people might think it weird. Tagging venison as "rawvenison" probably wouldn't help anything, unless there's another mod out there that specifically has deer meat recipes.

Anyway here's _an attempt:_
- Raw Venison as raw beef: 
  - rawbeef
  - stock_ingredients
  - rawmeats
  - rawvenison
- Cooked Venison: 
  - cookedbeef
  - cookedvenison
- Goat Milk
  - milk
  - buckets/milk
  - goatmilk
- Goat Cheese
  - cheese
  - all_cheese (I think this is a Rats thing actually I'm not sure using JEI to check things)
  - goatcheese
- Raw pheasent
  - rawchicken
  - raw meats
  - stock_ingredients
  - rawpheasant
- Cooked Pheasent
  - cookedchicken
  - cookedpheasant
- Raw Crab Meat
  - rawcrab
  - stock_ingredients
  - rawmeats
- Cooked Crab Meat
  - cookedcrab
- Raw Turkey Leg
  - rawchicken
  - raw meats
  - stock_ingredients
  - rawturkey
- Cooked Turkey Leg
  - cookedchicken
  - cookedturkey
- Raw Eel Meat
  - raweel
  - rawfish
  - rawmeats
  - stock_ingredients
- Cooked Eel Meat
  - cookedeel
  - cookedfish
- Raw Calamari
  - rawcalamari
  - rawsquid
  - stock_ingredients
  - rawmeats
- Cooked Calamari
  - cookedcalamari
  - cookedsquid

Notes:
- I think counting crab and calamari as fish is perhaps too wild but I dunno.
- Pam doesn't use it and i don't know about other cooking mods but maybe considering pheasent and turky as poultry and fowl might be helpful.
- Didn't touch the buckets of fish because vanilla minecraft makes a distinction between buckets of fish and fish items you can eat so probably shouldn't use a bucket of barracuda to make a sandwich tasty as it sounds.

**Comment by itsmeow** [comment]
Not bad. I will use these as reference when I get around to implementing the tags. Thanks!

**Comment by sharlin073** [comment]
I came here to ask for this, and it seems like it is already planned. Great and thanks a lot!
