### ISSUE TITLE
Crash due to butterflies?

### ISSUE THREAD

**Issue by IceflowRE** [itsmeow/betteranimalsplus#244]
**Describe what you were doing before the crash**
walking around

**Crash Log (REQUIRED)**
[crash-server.txt](https://github.com/itsmeow/betteranimalsplus/files/6216596/crash-2021-03-28_00.34.27-server.txt)

**Versions:**
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.0
 - Mod Version: 1.16.5-10.1.0.19

**Additional context**
I used the pre-release from the release page.

PS:

Also i get spammed with 
```
[dev.itsmeow.betteranimalsplus.imdlib.entity.EntityRegistrarHandler/]: Unable to set serializable for octopus. This could result in possible saving issues with entities!
```
messages, but this is not limited to the development versions.

**Comment by itsmeow** [comment]
Alpha issues don't go on our tracker, but thank you!
