### ISSUE TITLE
BetterAnimal+ mobs do not spawn when I'm playing with Biome Bundle

### ISSUE THREAD

**Issue by Slen6** [itsmeow/betteranimalsplus#249]
When I create a Biome Bundle world and play on it, I could spend hours and hours but I can't find a single mob from BetterAnimal+. However, they do spawn on default worlds.
I've also tried changing the difficulty, or the render distance but they still didn't spawn. I hope somebody can find a solution.

**Versions:**
 - Minecraft Version:1.12.2
 - Forge Version:14.23.5.2854
 - Mod Version:9.0.1

**Comment by itsmeow** [comment]
Can you verify your configuration actually contains biome bundles biomes as spawn biomes? If it doesn't, try deleting it and letting it regenerate when entering the biome bundle world. It's likely it generated before biome bundle was present. Otherwise, you can manually add them if it won't generate with them properly (that would be very tedious though)

**Comment by Slen6** [comment]
Sorry, I didn't get a notification. And I also don't know how to check that. I have also been exploring around a world and some animals spawned, though they barely did. I have to walk for a while and then I find a bear (for example), on a biome similar to birch forest. And when it's night time, a lot of wolves spawn. That's all I've seen though.

**Comment by itsmeow** [comment]
It's in the config folder of your Minecraft install. If you're using the CF client it's in the three dots, then "Open Folder". Otherwise .minecraft or wherever the files are kept.

**Comment by Slen6** [comment]
I found the folder but there is no file named Biome Bundle for some reason. I also took the mod out of my mods folder for a while and I found out that hostile mobs spawned more than before.

**Comment by itsmeow** [comment]
You're looking for *our* config. `betteranimalsplus.cfg`.

**Comment by Slen6** [comment]
It seems like it got fixed! Thank you very much.

**Comment by itsmeow** [comment]
Nice!
