### ISSUE TITLE
Pikes Attack Reach Too Far

### ISSUE THREAD

**Issue by JukeboxxSheepters** [itsmeow/betteranimalsplus#252]
You can be three blocks away (flat ground) or even a block or two above them (on ground) and they can still hit you. Because of this, there is no escape in the water nor can I get close to the water. There are so many of them in this area able to hit me from further then you'd expect.

I'd expect the Pike to be able to hit you when you're in water or maybe right by the edge.

**Versions:**
 - Minecraft Version: 1.16.5
 - Forge Version: 1.6.5-forge-36.1.0
 - Mod Version: 1.16.5-10.2.0

**Comment by itsmeow** [comment]
You mean barracuda?

**Comment by JukeboxxSheepters** [comment]
> You mean barracuda?

It looked like them, however it said I was killed by a Pike, and the two I did kill in the mess dropped Raw Pike. And later, when I didn't find a giant mass of them and just two (these ones looked like actual Pike) but were still hitting the same way, when I killed them it dropped Raw Pike, whereas Barracuda seem to drop Raw Cod. They still attacked me and did decent knockback as well.

Are barracuda supposed to hit you from that far away?

This shows how far away I'd be getting hit from; maybe it was just because there was too many but I figured just in case this was an issue to bring it to your attention.

![darn pikes](https://user-images.githubusercontent.com/84359506/118743464-419ca980-b807-11eb-9537-e432b6247aa4.PNG)

**Comment by itsmeow** [comment]
There is no such Pike in the mod, nor the Pike items you speak of. I believe you have mistaken the source of the Pike.

**Comment by JukeboxxSheepters** [comment]
> There is no such Pike in the mod, nor the Pike items you speak of. I believe you have mistaken the source of the Pike.

Oh darn, sorry about that, I really thought the Pikes were from yours as they look like your style (if that makes sense?)

I'm so sorry about that, I'll mark this as closed and not waste anymore of your time. Again, very sorry.
