### ISSUE TITLE
Crash with ticking entity

### ISSUE THREAD

**Issue by Blacksky649** [itsmeow/betteranimalsplus#255]
version: betteranimalsplus-1.16.5-10.2.0

Seems to happen periodically in my world with no specific action taking place.

any thoughts? 

Thanks for your hard work!

[crash-2021-06-14_12.14.59-server.txt](https://github.com/itsmeow/betteranimalsplus/files/6649785/crash-2021-06-14_12.14.59-server.txt)

**Comment by Blacksky649** [comment]
Update:
The location the crash took place had a few skeletons around it in the overworld. I could not load in with betteranimalplus mod in my mod folder but when I took out the mod I could load in and tp to the location where everything ran normally. I'm thinking a mob from betteranimalplus is getting hit by a skeleton arrow and crashing

Here is a follow up log I was able to recreate the crash while a skeleton was fighting a coyote. As far as I can tell it only seems to happen to coyotes
[crash-2021-06-14_13.12.02-server.txt](https://github.com/itsmeow/betteranimalsplus/files/6650095/crash-2021-06-14_13.12.02-server.txt)

**Comment by itsmeow** [comment]
Can you try to reproduce this without mobifier and performant?

**Comment by itsmeow** [comment]
If it still happens without those, maybe disabling the bleeding effect from Majrusz's Difficulty?

**Comment by Blacksky649** [comment]
Sorry for the late reply, been a busy week.

So the culprit seems to be mobifier with betteranimalsplus (specifically the coyote, the feral wolf doesn't crash) as I can reproduce the crash with both mods on my server. The crash does not happen with makrusz in my mod folder. All this was tested while using performant.

Both your mod and mobifier are key to my modpack so ill continue to keep the coyote disabled on my map

**Comment by itsmeow** [comment]
This seems to be an issue with Mobifier. I've created the issue for you.
https://github.com/CorgiTaco/Mobifier/issues/1

**Comment by itsmeow** [comment]
The upstream issue has been resolved with Mobifier 1.0.2, by the way.
