### ISSUE TITLE
Load-Bearing Jellyfish?

### ISSUE THREAD

**Issue by Avery93** [itsmeow/betteranimalsplus#259]
Minecraft version 12.2.2, Forge version 4.23.5.2855, BetterAnimals version 5.5.0, BetterAnimals+ version 9.0.1:

I found myself having issues where infinite whales and saltwater eels would spawn, slowing the frame rate down to nothing and eventually crashing the game. Similar to previous issues #156 and #167, the config menu seemed to be having no effect on spawn rates, as whales were marked to not spawn at all and the eels were dropped down to a spawn weight of 1. 

My complete mod list is frankly ridiculous so I found two at least different mods which were likely culprits as they were designed to increase mobs overall (IncreaseMobs) and increase the spawn weight of water mobs overall (CustomSpawner). Disabled both and kept having the same issue. Deleted config file and reloaded after making same changes again, same problem. Roughly three hours of troubleshooting, and finally the thing that worked was re-enabling the jellyfish mobs in your mod! I had them turned off because they tend to float around right at the surface, and for some reason disabling them threw off the spawn weights of the other mobs as far as I can tell. Turned them off and back on again several times to make sure the issue was replicable, at least in my environment.

Before, with Too Many Eels:
![2021-07-22_18 20 19](https://user-images.githubusercontent.com/48781885/126717797-5ece3acb-cfff-42fb-a7d9-6560f9b72cb3.png)
![2021-07-22_18 20 22](https://user-images.githubusercontent.com/48781885/126717806-4d92e1bb-0b49-4e03-b207-d516757fdd82.png)

After, a normal amount of eels, with jellyfish also visible:
![2021-07-22_18 34 34](https://user-images.githubusercontent.com/48781885/126717816-defa4a47-53f2-4cd4-ae55-a5a4e5e68804.png)
![2021-07-22_18 35 39](https://user-images.githubusercontent.com/48781885/126717822-28fd0b62-a5cd-45b8-90f5-68ff653d8455.png)

No clue if it's still a mod interaction somewhere or if your jellyfish truly are loadbearing. Either way, thought I'd share in case any one has a similar problem.

**Comment by itsmeow** [comment]
CMS definitely causes issues on 1.12, I know that. I'm not sure why having jellyfish as an option would change the overall occurance of water mobs. Maybe it's just because they're so large size wise that it's jarring? Compared to say, a salmon, they seem about equally common but they're much larger.

**Comment by Avery93** [comment]
I think it really is a difference in actual spawn rate, not just something subjective. The above screenshots are after completely uninstalling and deleting the configs for CMS and IncreaseMobs, the only difference was changing DoSpawning on Jellyfish to false in your config. The other fish in the background are from Just a Few Fish and don't seem to be affected either way, it's just the eels ¯\_(ツ)_/¯ Haven't the foggiest idea as to why, I'm not a modder and know very little about coding itself, just enough to troubleshoot my own installs.

**Comment by itsmeow** [comment]
This weird, but 1.12 is unsupported so I am closing this. Sorry.
