### ISSUE TITLE
Improper tag naming

### ISSUE THREAD

**Issue by BlackAures1** [itsmeow/betteranimalsplus#261]
**Describe the bug**
Hello! You have the wrong tag on the fish, which makes other mods not compatible. 

**Screenshots**
As it is written in your
 ![image](https://user-images.githubusercontent.com/43911230/128172539-fe23a055-d8fa-469c-88b2-aa93a8f28857.png)

What it should look like
![image](https://user-images.githubusercontent.com/43911230/128172564-7e3be5ff-9c6b-46e5-8a64-fd72e1db9d28.png)

**Versions:**
 - Forge Version: 1.16.5
 - Mod Version: Better Animals Plus 1.16.5-10.2.0

**Comment by itsmeow** [comment]
Thanks! We didn't really know at the time what to pick for everything, so let us know if you find anything else.
