### ISSUE TITLE
Texture crash

### ISSUE THREAD

**Issue by candys123** [itsmeow/betteranimalsplus#262]
If I add this mod to my modpack, the game crashes pretty fast, if I load the crashed gamesave, it crashes the moment I join the world, if I remove this mod the crashed gamesave loads normally and I can play.

**Describe what you were doing before the crash**
walking around after creating the world (a couple minutes)

**To Reproduce**
Steps to reproduce the behavior (if possible):
1. Create new world
2. Walk a couple minutes around
3. See error:
The game crashed whilst registering texture
Error: java.lang.NullPointerException: Registering texture
Exit-Code: -1

**Crash Log (REQUIRED)**
[2021-08-04-4.log](https://github.com/itsmeow/betteranimalsplus/files/6935900/2021-08-04-4.log)

**Versions:**
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.0
 - Mod Version: 1.16.5-10.2.0

**Additional context**
Crash Report
[crash-2021-08-04_17.25.43-client.txt](https://github.com/itsmeow/betteranimalsplus/files/6935855/crash-2021-08-04_17.25.43-client.txt)

Thank you for your time.

**Comment by candys123** [comment]
Weird, now it works perfectly.

**Comment by itsmeow** [comment]
This is a bug with the Boarlin from Lee's creatures, by the way :)
