### ISSUE TITLE
I can give new jellyfish textures

### ISSUE THREAD

**Issue by Nicknaem** [itsmeow/betteranimalsplus#268]
I edited jellyfish textures, they looked a bit boring, now using optifine emessive textures they look cool, I can give those textures if you wish

https://user-images.githubusercontent.com/55950404/138066878-e08780d4-5a40-42d3-b276-07f97d1cf1ff.mp4

**Comment by itsmeow** [comment]
Hi, we are actually adding new jellyfish model and textures next update, so I think that will address that. I appreciate your drive, though!
