### ISSUE TITLE
A problem about Trillium

### ISSUE THREAD

**Issue by SnakeSna** [itsmeow/betteranimalsplus#272]
Trillium can reduce a large number of frames,please fix this bug.
game version 1.16.5
mod version 10.2.0

![2021-12-08_19 34 37](https://user-images.githubusercontent.com/95751304/145202154-4ecd524f-858f-407f-b588-c46924ac275a.png)
![2021-12-08_19 34 19](https://user-images.githubusercontent.com/95751304/145202291-326809ef-74fa-4597-90e8-c792c8f0d105.png)

**Comment by itsmeow** [comment]
You are running shaders. Trillium are entity models - any large amount of non-baked models with shaders will reduce FPS. Shaders are resource intensive.
