### ISSUE TITLE
couldnot made new 1.16.5 version work with architectury api

### ISSUE THREAD

**Issue by Nicknaem** [itsmeow/betteranimalsplus#278]
## Describe what you were doing before the crash
game crashes on loading
also tried older version of architectury api but no success, 

[eg. Loading game, creating world, spawning a certain mob, hurting a mob, walking around]

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Spawn '...'
3. See error

## Crash Log (REQUIRED)
[crash.txt](https://github.com/itsmeow/betteranimalsplus/files/7793018/crash.txt)

Get your minecraft crash log and paste it here.

## Versions
- Minecraft Version: 1.16.5
- Architectury API Version: architectury-1.27.46
- Platform (Forge/Fabric):
- Forge Version: forge-1.16.5-36.2.0.jar:36.2
- Fabric Loader Version:
- Fabric API Version:
- Mod Version: betteranimalsplus-1.16.5-11.0.0-forge

**Comment by itsmeow** [comment]
You are using an unsupported, archived version of the mod. Please redownload the mod, do not press the update button on the CurseForge client. CurseForge for some reason is continuing to distribute an archived version.
