### ISSUE TITLE
Boar Textures

### ISSUE THREAD

**Issue by ghost** [itsmeow/betteranimalsplus#280]
After updating BAP from version 10.2.0 to 11.0.2 some of the boar textures have disappeared. Going back to 10.2.0 doesn't make the textures "come back" either.

The boars in my SP world now look like this:
![boar](https://user-images.githubusercontent.com/83789506/148052561-d9dead40-1670-4276-8e87-a3f549c1c720.jpg)

 - Minecraft Version: 1.16.5
 - Architectury API Version: 1.28.48
 - Forge Version: 36.2.22
 - Mod Version: 10.2.0 / 11.0.2

**Comment by itsmeow** [comment]
This is because the boar variants were renamed. In the future, I will add a method to pick a new variant if it is removed.

**Comment by ghost** [comment]
Alright, thanks. I'll just kill the semi-pink bastards on sight then. ;)

**Comment by itsmeow** [comment]
Interestng, so, it seems I've already added logic to pick a new variant. At least, at runtime. Not sure why that's happening... The fact that switching back doesn't fix it makes me think it's writing a new "empty" type.

**Comment by itsmeow** [comment]
Found it! Problem was I had *too much* logic, it was returning a blank variant as a "valid" variant instead of using the Optional functionality I had implemented.

**Comment by ghost** [comment]
Nice, thanks for investigating!
