### ISSUE TITLE
Config to select animals to keep

### ISSUE THREAD

**Issue by RotokEralil** [itsmeow/betteranimalsplus#284]
There are some animals I would like to add to my world from the mod, but others I wouldn't; Is it possible to update the config file so it is possible to select which animals you wish to add and not add to your world?
Thanks.

**Comment by itsmeow** [comment]
Please read the FAQ. This is already a feature.

**Comment by RotokEralil** [comment]
This must be a forge only feature, because this is all thats in the fabric config.
{
	"entities": {
		"reindeer": {
			// Generates snow particles around reindeer.
			"create_snow": true
		}
	}
}

**Comment by cybercat5555** [comment]
You're looking in the wrong place. The config for disabling animals is per-world, so go to your save, then "server-configs" and it will be there. After you edit it as you please, you can then copy the text file into the "defaultconfigs" folder to have it apply to all saves

**Comment by RotokEralil** [comment]
> You're looking in the wrong place. The config for disabling animals is per-world, so go to your save, then "server-configs" and it will be there. After you edit it as you please, you can then copy the text file into the "defaultconfigs" folder to have it apply to all saves

Apologies; could you also point me to the FAQ? I cant seem to find it on curseforge (or is it here on github?) Sorry again.

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/148726094-9c7d306e-0039-40c8-add9-6f6cc578948c.png)
