### ISSUE TITLE
Key binds

### ISSUE THREAD

**Issue by kittech0** [itsmeow/betteranimalsplus#286]
## Describe what you were doing before the crash

Trying to change keybinds

## To Reproduce

Steps to reproduce the behavior (if possible):
1. clicks on `Key binds`
2. clicks on search bar (from controling mod)
3. types letters
4. crashes
## Crash Log (REQUIRED)
[crash-2022-01-15_17.39.34-client.txt](https://github.com/itsmeow/betteranimalsplus/files/7875400/crash-2022-01-15_17.39.34-client.txt)

## Versions
- Minecraft Version: 1.18.1 
- Architectury API Version: 3.4.9
- Platform (Forge/Fabric): Fabric
- Forge Version:
- Fabric Loader Version: 0.12.12
- Fabric API Version: 0.46.0+1.18
- Mod Version:1.18.1-11.0.3

**Comment by itsmeow** [comment]
The letter combination is Ctrl+H. don't press that for now. I will patch this eventually.
