### ISSUE TITLE
Spawning in old chunks

### ISSUE THREAD

**Issue by mropitzky** [itsmeow/betteranimalsplus#288]
Hello! I have a quick question, I have a server im currently playing on using Fabric in 1.18.1. I downloaded your mod as one of the first ones and upon playing for a while, realized that not a lot if any mobs form this mod are spawning. I checked my files, and realized i had the forge version downloaded and not the Fabric one. I installed the correct one but do not see any of the animals in chunks that I have already explored, I'm assuming their only gonna spawn in unexplored chunks. Is there a way to force them to respawn in the old chunks as well, kind of like a spawn reset just for this mod?

**Comment by mropitzky** [comment]
Another note is that i only see one Config file with only the option to change deer particle spawn client side, is there supposed to be more options?

**Comment by itsmeow** [comment]
There is currently no way to spawn them in old chunks, sorry! The configuration is located in the save / world "serverconfig" folder. Check our Frequently Asked Questions on the mod page for more info on that.
