### ISSUE TITLE
Crash: Just walking around

### ISSUE THREAD

**Issue by TheButterbrotMan** [itsmeow/betteranimalsplus#289]
## Describe what you were doing before the crash

Walking around

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Install https://www.curseforge.com/minecraft/modpacks/deathdusk
2. Walk around

## Crash Log (REQUIRED)

Get your minecraft crash log and paste it here.

## Versions
- Minecraft Version: 1.18.1
- Architectury API Version: 3.4.9
- Platform (Forge/Fabric): Fabric
- Forge Version: /
- Fabric Loader Version: 0.12.12
- Fabric API Version: 0.46.2
- Mod Version: 11.0.3

**Comment by itsmeow** [comment]
You did not include the crash log. Please include the crash log.

**Comment by TheButterbrotMan** [comment]
I could swear i did, it seems i cant find him again. Sorry.
