### ISSUE TITLE
[1.18.1] Fabric Crash after walking around & looking at the Badger?

### ISSUE THREAD

**Issue by pewblaze** [itsmeow/betteranimalsplus#290]
## Describe what you were doing before the crash

Generated the world 1 or 2 minutes ago & was walking around,

[eg. Loading game, creating world, spawning a certain mob, hurting a mob, walking around]

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Spawn '...'
2. look at a certain Mob (Badger?)
3. See error (Crashes)

## Crash Log (REQUIRED)

[crash-2022-01-26_23.59.30-client.txt](https://github.com/itsmeow/betteranimalsplus/files/7946188/crash-2022-01-26_23.59.30-client.txt)

## Versions
- Minecraft Version: 1.18.1
- Architectury API Version: architectury-3.4.9
- Platform (Forge/Fabric): Fabric
- Forge Version: -
- Fabric Loader Version: 0.12.12
- Fabric API Version: fabric-api-0.46.2+1.18
- Mod Version: betteranimalsplus-1.18.1-11.0.3-fabric

## Additional context
Not sure if its this mod or Iris though. But its cause of the Badger (you cann see that in the crashlog)

**Comment by itsmeow** [comment]
I think this is likely caused by Iris.
