### ISSUE TITLE
I made Korean Translation.

### ISSUE THREAD

**Issue by queso-gato1355** [itsmeow/betteranimalsplus#292]
[ko_kr.zip](https://github.com/itsmeow/betteranimalsplus/files/7947382/ko_kr.zip)

I made this thing.

As you can see from Discussions, the config-related translation has not yet been completed. Because I can't see how to check the config in the game. It would be nice if you could help me in this regard.

Still, I'm sure it's translated to the point where there's no inconvenience when playing games.

**Comment by itsmeow** [comment]
The config is on the fabric version, you need to install [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config) and [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu), then you can access the configuration of existing worlds in the main menu Mods button.
