### ISSUE TITLE
Pluckable arrows + better animals plus crashes

### ISSUE THREAD

**Issue by Chipotle4** [itsmeow/betteranimalsplus#293]
Minecraft crashes when shooting an arrow at an animal with the pluckable arrows mod.

I'm running Minecraft 1.18.1 with fabric 0.12.12, Better Animals plus 11.0.3, and Pluckables arrows 1.1.2

[crash-2022-01-26_22.43.52-client.txt](https://github.com/itsmeow/betteranimalsplus/files/7947473/crash-2022-01-26_22.43.52-client.txt)

**Comment by itsmeow** [comment]
This seems like an issue with Pluckable Arrows.
