### ISSUE TITLE
Feral Wolf Glitch

### ISSUE THREAD

**Issue by NovaWorks72** [itsmeow/betteranimalsplus#294]
## To Reproduce
Simply use the Feral Wolf spawn egg

## Expected behavior
I expected different texture/color wolf.

## Versions
 - Minecraft Version:

 - Fabric Loader Version:
 - Fabric API Version: 1.18
 - Mod Version: 1.18.1

**Comment by itsmeow** [comment]
Can you include a screenshot of this wolf? Are you using any other mods (especially shaders, like Iris?) - also please include the proper version information. "1.18.1" is your Minecraft version. The mod and Fabric API versions are completely different.

**Comment by itsmeow** [comment]
Closed, needs more information. Will reopen if more information is included.

**Comment by itsmeow** [comment]
Likely cause identified.

https://github.com/itsmeow/betteranimalsplus/blob/3317be85a55932941eb7a8cc91d8d15dabffac59/common/src/main/java/dev/itsmeow/betteranimalsplus/common/entity/EntityCoyote.java#L63

Will be fixed next patch.

**Comment by GirlMeetsWild** [comment]
I’m having this same glitch with feral wolves as well as zotzpyres. They are completely black except for the eyes but my toro health image clearly shows the texture should reflect differently.

I am in 1.12.2 and using Chocapic V8 Ultra Shaders but have not had an issue with any other mod or other animals in this mod.

I’m planning to use this mod for a series so seeing these issues fixed would be great:) I really admire your work and hope you solve the issue soon!

![C314A2E1-5E3E-4C0C-8E60-2FA435252F64](https://user-images.githubusercontent.com/114308407/192112244-585a2bb2-9f36-4caa-b018-4fa5e4560bbc.jpeg)

![A18FEC4C-CCC4-4879-AE41-613D3D772770](https://user-images.githubusercontent.com/114308407/192112256-98b16ed2-45b4-491e-94d2-80456ecc10e3.jpeg)

![9E8E25AA-C1ED-4BD9-95F6-E0D4FE24DC07](https://user-images.githubusercontent.com/114308407/192112267-ddc124e0-2a2c-47fa-ae19-300cbf969392.jpeg)

**Comment by itsmeow** [comment]
1.12.2 is not supported unfortunately so this will not be fixed in that version.

**Comment by GirlMeetsWild** [comment]
Not supported? Meaning what exactly? I’m just curious as i downloaded a
1.12.2 version off curseforge. It is one of, if not the most played version
of Minecraft next to 1.16.5 so some insight would definitely give me some
peace of mind. Thank you!

**Comment by itsmeow** [comment]
As in we're not updating it anymore. It's not really worth the effort as the code between 1.12 and 1.19 is completely different.
