### ISSUE TITLE
About Hirshgeist

### ISSUE THREAD

**Issue by BlueWither** [itsmeow/betteranimalsplus#3]
**Describe the bug**
First, when it walks, the movements of the ghost feet and bone legs do not match.
Next, it does not seem to have flames of eyes or horns.
Finally, it needs sound. How about using the skeleton horse with lower voice?

**Versions:**
 - MC Version:1.12.2
 - Mod Version:1.0

**Comment by itsmeow** [comment]
The leg bug is currently a work in progress.
The flames are currently not in but they might in the future. They were purposely left out due to the advanced techniques needed to render them.
The sound I could try, although I believe cyber is working on sounds.

**Comment by itsmeow** [comment]
Also: in the future, please split issues (even if about the same thing) into seperate issues so they can be resolved seperately.

**Comment by itsmeow** [comment]
Flames are still definitely not something for the near future. The legs have been fixed and the sounds have been added. Closing.
