### ISSUE TITLE
Birds are Murders with sihywtcamd Mod (incompatibility)

### ISSUE THREAD

**Issue by AshrielV** [itsmeow/betteranimalsplus#300]
When sihywtcamd's config 

> "merchantHostility": true

then every mob in this mod attempts to murder villagers and [guildmasters](https://www.curseforge.com/minecraft/mc-mods/guild).

## To Reproduce
1. Download [sihywtcamd](https://www.curseforge.com/minecraft/mc-mods/sihywtcamd) & install alongside betteranimalsplus
2. Navigate to config\sihywtcamd\overworld.json and change merchantHostility to true
3. Put any villagers next to any animals from betteranimalsplus. 

If you think this is better reported on [sihywtcamd's](https://github.com/sf-inc/sihywtcamd/issues) issues board, let me know and I'll set up a ticket there.

## Versions
 - Minecraft Version: 1.18.1
 - Architectury API Version: architectury-3.6.15.jar
 - Platform (Forge/Fabric): Fabric 
 - Fabric Loader Version: 0.12.12
 - Fabric API Version: fabric-api-0.46.1+1.18.jar
 - Mod Version: betteranimalsplus-1.18.1-11.0.3-fabric.jar **with** sihywtcamd-1.5.2+1.18.jar

**Comment by itsmeow** [comment]
We don't add any crickets?

**Comment by itsmeow** [comment]
This seems to be a bug with sihywtcamd before it is one with ours, I would suggest creating an issue there.
