### ISSUE TITLE
Non-land animals don't spawn in pregenned chunks

### ISSUE THREAD

**Issue by Alkiasan** [itsmeow/betteranimalsplus#302]
## Describe the bug
Installing the mod on a world with chunks already generated does not allow mobs from this mod to spawn. Underwater creatures still seem to spawn though, weirdly.

## To Reproduce
1. Pregen world
2. Install mod
3. See error

## Expected behavior
Mobs spawn naturally

## Versions
 - Minecraft Version: 1.18.1
 - Architectury API Version: 3.2.60
 - Platform (Forge/Fabric): Fabric

 - Fabric Loader Version: 0.12.2
 - Mod Version: 11.0.4

**Comment by itsmeow** [comment]
This is not a bug, this is how Minecraft's creature spawning system works. If the mod is not present at chunk generation, land creatures will not be spawned. It doesn't apply to water creatures, because that is how Minecraft's water spawning works. We use vanilla spawning algorithms.

**Comment by itsmeow** [comment]
If you go to ungenerated chunks, things will spawn as expected. This only applies to chunks that have been generated WITHOUT the mod installed.

**Comment by Alkiasan** [comment]
Hmm.. Chunks are pregenned 15k blocks out... Is there really no way around this?

**Comment by Alkiasan** [comment]
Like a launch arguement or something that can reset the chunk's spawning?

**Comment by itsmeow** [comment]
Entities not spawning would be a problem with your pregenerator, not the mod.

**Comment by Alkiasan** [comment]
I know it's not an issue with the mod, and the chunks were pregenned before the mod was added, which is why the problem is occuring. I was just wondering if there's a way to re-validate the chunks or something instead of straight-up resetting the world?
