### ISSUE TITLE
Goose creating Ticking entitiy error

### ISSUE THREAD

**Issue by Landaz2** [itsmeow/betteranimalsplus#306]
## Describe what you were doing before the crash

Walking around in peace, but i guess peace was never an option with these geese...
Happened several times now.

## To Reproduce

Not quite sure, happens "randomly", often several chunks away from water sources with geese

## Crash Log (REQUIRED)

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/17/22, 8:04 PM
Description: Ticking entity

java.lang.ClassCastException: class dev.itsmeow.betteranimalsplus.common.entity.EntityGoose cannot be cast to class net.minecraft.class_1657 (dev.itsmeow.betteranimalsplus.common.entity.EntityGoose and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @255b53dc)
	at net.minecraft.class_1799.handler$bcf000$finishUsingItem(class_1799.java:1141)
	at net.minecraft.class_1799.method_7910(class_1799.java)
	at dev.itsmeow.betteranimalsplus.common.entity.EntityGoose.method_6007(EntityGoose.java:171)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1799.handler$bcf000$finishUsingItem(class_1799.java:1141)
	at net.minecraft.class_1799.method_7910(class_1799.java)
	at dev.itsmeow.betteranimalsplus.common.entity.EntityGoose.method_6007(EntityGoose.java:171)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

-- Entity being ticked --
Details:
	Entity Type: betteranimalsplus:goose (dev.itsmeow.betteranimalsplus.common.entity.EntityGoose)
	Entity ID: 5473
	Entity Name: Goose
	Entity's Exact location: 111.46, 62.58, -177.61
	Entity's Block location: World: (111,62,-178), Section: (at 15,14,14 in 6,3,-12; chunk contains blocks 96,-64,-192 to 111,319,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.01, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Landaz'/247, l='ServerLevel[Terra]', x=208.49, y=72.12, z=-257.13]]
	Chunk stats: 4413
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,93,0), Section: (at 0,13,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 124924 game time, 204700 day time
	Level name: Terra
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 29297 (now: false), thunder time: 45893 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1122117216 bytes (1070 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7247
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25313.63
	Virtual memory used (MB): 20767.40
	Swap memory total (MB): 8980.40
	Swap memory used (MB): 132.30
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m
	Fabric Mods: 
		additionalbars: Additional Bars 2.2.1
		adorn: Adorn 3.3.1+1.18.1
		advancements-enlarger: Advancements Enlarger 0.2.4
		ae2: Applied Energistics 2 10.0.0
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architects_palette: Architect's Palette Fabric 1.6
		architectury: Architectury 3.6.17
		attributefix: AttributeFix 13.0.5
		balm-fabric: Balm 2.4.1+0
		basicshields: Basic Shields [Fabric] 1.2.1-1.18.1
		bclib: BCLib 1.3.4
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.4
		betterend: Better End 1.0.2
		betterf3: BetterF3 1.2.2
		betternether: Better Nether 6.0.10
		blue_endless_jankson: jankson 1.2.1
		botania: Botania 1.18.1-427-FABRIC
		bountiful: Bountiful 2.0.1
		bowinfinityfix: Bow Infinity Fix rv11
		cardinal-components-base: Cardinal Components API (base) 4.1.0
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.0
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		chipped: Chipped 1.2
		clienttweaks: Client Tweaks 7.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+5
		collective-fabric: Collective (Fabric) 4.8
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 1.0.2-1.18.1
		consistency_plus: Consistency Plus 0.4.3+1.18
		continuity: Continuity 1.0.3+1.18
		cosmetic-armor: Cosmetic Armor 1.2.1
		darkpaintings: DarkPaintings 9.0.3
		decorative_blocks: Decorative Blocks 2.0.4
		deepslatecutting: Deepslate Cutting 1.3.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		doubledoors-fabric: Double Doors (Fabric) 3.1
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49d-fabric
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18
		easymagic: Easy Magic 3.2.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchant_giver: Enchant Giver 1.1.0
		enderitemod: Enderite Mod 1.3.3
		entityculling: EntityCulling-Fabric 1.5.0
		exlinefurniture: Exline's Furniture fabric-1.18.1-v2.0.4
		expandedstorage: Expanded Storage 7.3.6
		experiencebugfix: Experience Bug Fix 18
		extraalchemy: Extra Alchemy 1.7.0
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.13.2
		fabricshieldlib: Fabric Shield Lib 1.5.0-1.18
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		fallingtree: FallingTree 3.2.1
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 1.7.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		illuminations: Illuminations 1.10.2
		impactfulweather: Impactful Weather 1.21
		indium: Indium 1.0.2-alpha2+mc1.18.1
		inmis: Inmis 2.5.1-1.18.1
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.4-1.18
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.1-1.18
		kleeslabs: KleeSlabs 11.0.0
		kyrptconfig: Kyrpt Config 1.3.4-1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		libcd: LibCapableData 3.0.3+1.16.3
		lithium: Lithium 0.7.7
		magna: Magna 1.7.0-1.18-pre1
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.18.1
		mcda: MC Dungeons Armors 2.0.1
		mcdar: MC Dungeons Artifacts 1.4.3-1.18
		mcdw: MC Dungeons Weapons 4.0.4
		mcwfences: Macaw's Fences and Walls 1.0.4
		mcwlights: Macaw's Lights and Lamps 1.0.2
		mcwpaintings: Macaw's Paintings 1.0.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.4
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		more_tooltips: MoreTooltips 1.1.1
		mousetweaks: Mouse Tweaks 2.22
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.3.0
		no-telemetry: No Telemetry 1.3.0
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		patchouli: Patchouli 1.18.1-65-FABRIC
		pipe: Pipe 1.6.2
		polymorph: Polymorph 0.0.19-1.18.1
		pride: Pride Lib 1.1.0+1.17
		puzzleslib: Puzzles Lib 3.1.5
		quarrymod: Industrial Quarry Mod 0.5.5
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0-beta.9
		repurposed_structures: Repurposed Structures 3.3.11+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.2.425
		roughlyenoughresources: Roughly Enough Resources 2.4.1
		seedfix: Seed Fix 1.0.0
		sodium: Sodium 0.4.0-alpha6+build.14
		spruceui: SpruceUI 3.3.0+1.17
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.1.0-beta.9
		terralith: Terralith for Fabric 2.0.12
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.1
		trinkets: Trinkets 3.2.0
		vanilla-hammers: Vanilla Hammers 3.2.0-1.18.1
		visualworkbench: Visual Workbench 3.1.0
		waystones: Waystones 9.0.3
		wthit: wthit 4.5.1
		xaerominimap: Xaero's Minimap 22.2.0.1
		xaeroworldmap: Xaero's World Map 1.20.3.1
		yigd: You're in Grave Danger 1.2.18
	Server Running: true
	Player Count: 1 / 8; [class_3222['Landaz'/247, l='ServerLevel[Terra]', x=208.49, y=72.12, z=-257.13]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

## Versions
- Minecraft Version: 1.18.1
- Architectury API Version: 3.6.17
- Platform (Forge/Fabric): Fabric 
- Forge Version: -
- Fabric Loader Version: 0.13.2
- Fabric API Version: 0.46.4
- Mod Version: 11.0.4

**Comment by Spectre96** [comment]
Also getting this on a Multiplayer server running other mods, crash report is attached below.

[crash-2022-02-17_00.03.59-server.txt](https://github.com/itsmeow/betteranimalsplus/files/8094699/crash-2022-02-17_00.03.59-server.txt)

**Comment by Senteth** [comment]
I'm getting the same goose-related ticking entity error as well in singleplayer. Crash report is as follows:

[crash-2022-02-18_05.21.02-server.txt](https://github.com/itsmeow/betteranimalsplus/files/8096378/crash-2022-02-18_05.21.02-server.txt)

**Comment by ghost** [comment]
I'm also getting this issue with the goose-related ticking.
[crash-2022-02-20_00.28.37-server.txt](https://github.com/itsmeow/betteranimalsplus/files/8103483/crash-2022-02-20_00.28.37-server.txt)

**Comment by itsmeow** [comment]
Hey, this appears to be caused by another mod injecting a mixin into the ItemStack finishUsingItem method and failing to check a cast. I will have to compare your modlists for a common factor.

**Comment by itsmeow** [comment]
Here is the list of shared mods between these four crash logs, with internals/fabric removed.

```
adorn
architectury
betteranimalsplus
collective-fabric
omega-config
waystones
```

**Comment by itsmeow** [comment]
I have located the source of the crash, the cause is collective. Please update to 4.9, which came out 10 hours ago. It should fix this crash.
https://github.com/ricksouth/serilum-mc-mods/issues/950
