### ISSUE TITLE
Boars are OP, pls nerf

### ISSUE THREAD

**Issue by Kingmiami** [itsmeow/betteranimalsplus#308]
Title is a joke, but this is a real problem.

## Is your feature request related to a problem? Please describe.

Boars are terrible. I can murder hordes of zombies, skeletons, spiders and creepers, but still fall victim to a small group of these evil creatures. I even limited the spawn group to one boar thinking that would make them more managable; but I still ended up getting rushed and killed by just one before I knew what happened.

## Describe the solution you'd like

Boars should not be murders. They should not chase down every player and kill them like the actual mobs. Instead, when a player gets too close, they should attack them once, knocking them back, and continuing on with their business. 

If the player does decide to fight them, they'll attack like this: stand still, aim at player, rush in straight line, knockback player if caught in attack. Simple.

## Describe alternatives you've considered
I considered just lowering how powerful their attacks are, but that does nothing for the real problem.

## Additional context
Albino Boars should be more rare, to make them extra desireable.

**Comment by cybercat5555** [comment]
There is a config for this in later versions of the mod. Likewise the white boar was removed when the boars themselves were remodeled

**Comment by Kingmiami** [comment]
@cybercat5555 Apologies, I was using 1.12.

I just tried it, and I guess they aren't as overpowered now, but they still chase down the player and animals, which seems somewhat silly. My issue still stands, I think.

**Comment by itsmeow** [comment]
The boar nerf config effectively solves this issue as 1.12 is unsupported. Lowering the target chance will prevent the "chasing down".
