### ISSUE TITLE
The wearable skull is rendered backwards in the player inventory.

### ISSUE THREAD

**Issue by darkhax** [itsmeow/betteranimalsplus#31]
**Describe the bug**
The wearable hirschgeist skull renders backwards in the player inventory.

**To Reproduce**
1. Get the skull
2. Make it wearable
3. Look in inventory

**Log output/error (if present)**
no erros

**Expected behavior**
Skull should render like it does in the overworld.

**Screenshots**
![image](https://user-images.githubusercontent.com/2250798/49562954-9ab54300-f915-11e8-892e-0af553b70bb8.png)

**Versions:**
 - OS: Windows
 - MC Version: 1.12.2
 - Mod Version: 2.0.0

**Additional context**

**Comment by itsmeow** [comment]
Oops. Forgot to close this. Was solved in 60cce203b654d4d1e9a38eb0ef06cd95cb2bf08b (4.1.0)
