### ISSUE TITLE
Geese crash the server.

### ISSUE THREAD

**Issue by RageQuitAmy** [itsmeow/betteranimalsplus#316]
So this mod is used in a pack that a friend of mine made. Multiple people reported that the geese crashed their server. I to start with did not have the problem on single player and could not reproduce it. I spawned geese and gave them items and still nothing. I then died and respawned and walked towards the geese and crashed. It said this:

The game crashed whilst ticking entity
Error: java.lang.ClassCastException: class dev.itsmeow.betteranimalsplus.common.entity.EntityGoose cannot be cast to class net.minecraft.class_1657 (dev.itsmeow.betteranimalsplus.common.entity.EntityGoose and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @255b53dc)
Exit Code: -805306369 

[crash-2022-03-08_20.51.34-server.txt](https://github.com/itsmeow/betteranimalsplus/files/8209557/crash-2022-03-08_20.51.34-server.txt)

After that happened I relaunched and tried again. This time I managed to get close to the geese. It was night time and zombies were around the geese. I started smacking the zombie and it crashed again.

The game crashed whilst ticking entity
Error: java.lang.ClassCastException: class dev.itsmeow.betteranimalsplus.common.entity.EntityGoose cannot be cast to class net.minecraft.class_1657 (dev.itsmeow.betteranimalsplus.common.entity.EntityGoose and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @255b53dc)
Exit Code: -1

[crash-2022-03-08_21.03.38-server.txt](https://github.com/itsmeow/betteranimalsplus/files/8209603/crash-2022-03-08_21.03.38-server.txt)

The mod version is betteranimalsplus-1.18.1-11.0.5-fabric

**Comment by itsmeow** [comment]
This crash is caused by Collective 4.8. Upgrade to 4.9.

**Comment by RageQuitAmy** [comment]
Thank you so much for the quick reply. I really appreciate the help. :)
