### ISSUE TITLE
Badger dirt doesn't despawn in certain situations

### ISSUE THREAD

**Issue by SmolFloofyRedhead** [itsmeow/betteranimalsplus#318]
Someone playing the Life in the Village 2 modpack was having a nasty lag issue and /killall was wiping out a whopping 58k+ entities. Crash Utilities revealed that these entities were the dirt projectiles that badgers throw.
![unknown](https://user-images.githubusercontent.com/25872390/158516065-b3379748-94ae-4958-ad3f-903a2ba075e7.png)
I checked in my own world, but there were no badgers anywhere. Also note that there were only 6 badgers present in that world at that time. I'm not really sure what they throw dirt at besides players, but the projectiles just weren't despawning. I've seen badgers in my own world before but haven't had dirt thrown at me, and there were no projectiles in Crash Utils either.

**Comment by itsmeow** [comment]
Badgers do attack other animals naturally so that could explain it, but I'm not sure why they're not being removed automatically. Can you provide the version info from the issue template?

**Comment by SmolFloofyRedhead** [comment]
It's the version used in Life in the Village 2. I'm on mobile rn, but I'll see if the person still has a backup from before they wiped the entities.

**Comment by DoctorMage** [comment]
the logs file from the player having the issue
[2022-03-15-6.log](https://github.com/itsmeow/betteranimalsplus/files/8269141/2022-03-15-6.log)
s
version betteranimalsplus-1.16.5-11.0.4-forge

**Comment by DoctorMage** [comment]
![image](https://user-images.githubusercontent.com/85318453/158675445-d7f14f0d-c53b-4cca-9759-9b5c33fb8f47.png)
accoring to crash utils their all in this same area and tping even 100 blocks near crashes

**Comment by SmolFloofyRedhead** [comment]
Yep, it's ONE badger that was tossing and tossing and tossing, and the dirt did not despawn. I had an idea to wipe just the dirt entities and then tp over there to get a look at just what this one badger is doing, and what is around it to make the projectiles persist like that. I need to get back to work, as I was on lunch just now, though given the same X ad Z coords it's throwing straight up or down.

**Comment by DoctorMage** [comment]
https://streamable.com/c5m5jg

**Comment by DoctorMage** [comment]
the area its occuring in is the spawn region so its being force loaded by hte world

**Comment by itsmeow** [comment]
I will add a timer to the Badger Dirt making it despawn after a certain length. The spawn chunk must be preventing projectile impacts.
