### ISSUE TITLE
Fried Egg furnace/campfire smelting Conflicts with jtl_elisa "Egg to capture mob- Fabric" capture egg furnace/campfire smelting. No way to choose capture egg, nor ability to turn off vanilla food items affected by BAP mod

### ISSUE THREAD

**Issue by TamedBologna** [itsmeow/betteranimalsplus#324]
## Describe the bug
when smelting a vanilla Minecraft egg, so that you can get a capture egg from jtl_elisa's mod, in survival the only option is to get the fried egg from this mod. I guess a data pack (that I don't know how to do or what EXACTLY is) would solve this problem but it would be nice to have a togglable config for the food in this mod that involves vanilla Minecraft food items, as to not turn off all the food of this great mod, but to choose to not interfere with mods that interact with the same vanilla food items. The mod "additional additions" has a fried egg, and a food items toggle config that I could turn off for this type of conflict, but looking through all the configs for this mod, there is a lot of spawning configs which is great but no vanilla food items interaction toggle, which does make rise for conflicts; I don't want to lose egg capture, and the "Polymorph" mod for the furnace in fabric 1.18.2 doesn't solve the problem.

## To Reproduce
1. Spawn '...' -campfire/furnace -egg -coal
2. Click on '....' furnace/campfire, put in egg and coal in respective boxes, get fried egg but no ability to get to a capture egg, an item added by "Egg to capture mob-fabric" a mod by jtl_elisa
 no ability to get to a capture egg, an item added by "Egg to capture mob-fabric" a mod by jtl_elisa
## Log output/error (if present)

No log required
## Expected behavior
Expected to be able to toggle the food items in BAP. There is a lot of new animals, The meat and pelts added are new items, but something altering a vanilla Minecraft food items that changes a path for them is something that I would expect to be togglable. A well known mod called "Additional Additions" by dqu1jjj has a "FoodItems" toggle, as it was the first mod conflicting in my game, doing its code properly of course just like BAP, making a fried egg pop out of a vanilla egg, but its bad as I wanted a capture egg, and now id like to toggle vanilla food items being altered by BAP.

## Versions
 - Minecraft Version: 1.18.2
 - Architectury API Version: 4.1.39
 - Platform (Forge/Fabric): Fabric
 - Forge Version:
 - Fabric Loader Version: 0.13.3
 - Fabric API Version: 0.48.0
 - Mod Version: 11.0.5

## Additional context
Big Fan, Minecraft is alive with BAP and its a must for me. thank you for your time.

**Comment by itsmeow** [comment]
I am confused on how Polymorph does not solve this problem.

**Comment by itsmeow** [comment]
I would also note it is not reasonable for me to implement a config disabling food at the moment due to the way the mod works. A datapack or a mod akin to CraftTweaker would functionally allow you to change recipes, yes. Polymorph, afaik, should do what you want, also? If it's not, I would suggest bringing this issue up with the egg capture mod. While I understand BAP adding this recipe to the vanilla egg is somewhat intrusive, it's tweakable using other mods to an extent where I don't have a good reason to add options for this, as recipe conditions are difficult enough on Forge, and Fabric has no infrastructure for doing so - currently I use a mixin to achieve this with a whisperwoods compatibility achievement.

**Comment by TamedBologna** [comment]
thank you for your insight with Crafttweaker. Glad there is mods to help novice modders get the most from great additions like BAP. Next time I will do my homework before wasting your time. 
Thank you
