### ISSUE TITLE
Warthogs, Lammergiers too aggressive

### ISSUE THREAD

**Issue by BugmanBugman** [itsmeow/betteranimalsplus#326]
## Is your feature request related to a problem? Please describe.

Warthogs and Lammergiers are far too aggressive to nearby animals 

## Describe the solution you'd like

A cool down period for them, because they end up killing every other animal in the vicinity

**Comment by itsmeow** [comment]
Lammergeiers only attack skeletons, so I do not agree that is an issue. As for boars, they have a configurable aggression. Feel free to lower it in the config.
