### ISSUE TITLE
Diamonds with tag betteranimalsplus:eggs_common (?)

### ISSUE THREAD

**Issue by Laifsyn** [itsmeow/betteranimalsplus#328]
Hello, so I just found out that diamonds are in the betteranimalsplus:eggs_common  tag. I neither find it inside my datapack. I was wondering if it could be something inside the code that's the culprit. It's no real problem though. I can just remove it . But really weird nonetheless
![image](https://user-images.githubusercontent.com/99366187/164105009-09a696ac-7527-474a-8fd6-c176b890596f.png)

**Comment by itsmeow** [comment]
I have no idea why that is there.

**Comment by Laifsyn** [comment]
Nvm. found the issue. I'll upload ticket in other place
