### ISSUE TITLE
Bug: recurring warns and defineID called for on server please have a look

### ISSUE THREAD

**Issue by GhostlyGaming** [itsmeow/betteranimalsplus#334]
## Describe the bug
Repeaded server warns and lag issues caused by some of these messages. The lag is not substantial or hardly noticeable but it does cause a lot of clutter on my console. Please let me know on how to fix this.

## Log output/error (if present)
Server thread/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityFreshwaterEel from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
17.05 19:50:19 [Server] Server thread/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityFreshwaterEel from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainerContainable
17.05 19:50:22 [Server] Worker-Main-7/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityCrab from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
17.05 19:50:22 [Server] Worker-Main-7/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityCrab from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainerContainable
17.05 19:50:49 [Server] Worker-Main-7/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityHorseshoeCrab from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
17.05 19:50:49 [Server] Worker-Main-7/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityHorseshoeCrab from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainerContainable
17.05 19:51:22 [Server] Server thread/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityLamprey from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
17.05 19:51:22 [Server] Server thread/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityLamprey from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainerContainable
17.05 19:51:23 [Server] Worker-Main-7/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityBoar from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
17.05 19:51:27 [Server] Worker-Main-7/WARN defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntitySquirrel from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer

## Expected behavior
I do not have a description but i have a lot of these on my server caused by this mod

## Versions
 - Minecraft Version: 1.18.2
 - Architectury API Version: 4.4.60
 - Platform (Forge/Fabric): Forge
 - Forge Version: 40.1.16
 - Fabric Loader Version: N/A
 - Fabric API Version: N/A
 - Mod Version: 11.0.5

**Comment by itsmeow** [comment]
This is not fixable. It does not cause lag. I have tried to forcibly remove the warnings before but the mixin is unstable. Forge does this without checking the class is controlled by the same mod, nothing I can do, sorry.
