### ISSUE TITLE
Mob's head duplication glitch

### ISSUE THREAD

**Issue by Siwek9** [itsmeow/betteranimalsplus#336]
## Describe the bug
You can duplicate animal's head from this mod (like reindeer's head or boar's head) because if you place the head it is not getting removed from your inventory.

## To Reproduce
1. Take mob's head from this mod (for example reindeer's head).
2. Try place it while looking up (pitch value smaller than -45).
3. You can see that the head is placed but you still have one in your inventory.

## Expected behavior
It should remove the animal's head from your inventory and then place it on the block.

## Screenshots
![2022-05-22_21 02 56](https://user-images.githubusercontent.com/72036867/169712626-0fe41ad8-be7f-469d-a1b1-9173dbb4492c.png)

## Versions
 - Minecraft Version: 1.18.2
 - Architectury API Version: 4.4.60
 - Platform (Forge/Fabric): Fabric
 - Forge Version: ----
 - Fabric Loader Version: 0.14.6
 - Fabric API Version: 0.53.0
 - Mod Version: 11.0.5

**Comment by itsmeow** [comment]
Can you verify the head item actually exists and does not disappear if the world is reloaded, or if it's dropped?

**Comment by Siwek9** [comment]
> Can you verify the head item actually exists and does not disappear if the world is reloaded, or if it's dropped?

No, it is normal item and i can throw it or place multiple time using this glitch, it didn't disappear. 

I have also verify this on the newest versions of the fabric api (0.53.4) and architectury (4.4.65) and the glitch still appear.

https://user-images.githubusercontent.com/72036867/170783170-ba4fe05f-7051-4f2f-88b7-ec53b5d36c92.mp4
