### ISSUE TITLE
Don't remove entity from game when disabling in config

### ISSUE THREAD

**Issue by EvertX** [itsmeow/betteranimalsplus#34]
**Type**
Mob config

**Is your feature request related to a problem? Please describe.**
I'm making a pack and want to customise spawning with InControl. When disabling spawning in your config-file, it removes the entity so I cannot assign it a new rule.

**Describe the solution you'd like**
Leave the entity in-game so I can assign a new spawn-rule to it.

**Describe alternatives you've considered**
Altering the spawn-rules, but that is too complex and I don't think 100% possible with existing mods.

**Comment by itsmeow** [comment]
Definitely doable. Will be in the next patch.

**Comment by itsmeow** [comment]
For when it releases: it's under the "spawning" category and are named "spawn(EntityName)" while the old one remains as "enable(EntityName)"
