### ISSUE TITLE
Extremely unusual crash

### ISSUE THREAD

**Issue by Sunconure11** [itsmeow/betteranimalsplus#340]
I literally can't provide good info on this, aside from the fact that this started after I updated a few mods. Of note is that one of them was Architectury, a dependency you use.

https://pastebin.com/taaJBwgM

**Comment by Sunconure11** [comment]
@lukebemish Hey dude, I think out of all things, this is being caused by your Dynamic Asset Generator for Excavated Variants.

**Comment by lukebemish** [comment]
I cannot reproduce this error with just DynAssetGen, Excavated Variants, Better Animals Plus, and dependents, so some other mod is to blame. Someone is probably doing something unfortunate with a mixin plugin, if I had to guess, possibly referencing a class that shouldn't be classloaded yet.

**Comment by itsmeow** [comment]
It could be our mixin plugin that checks for Architectury tripping. I reference arch in mixins, so I have a plugin checking if it is loaded before my mixins run, so that the game can properly inform the user Arch is mixin and not hardcrash in the mixin phase.

**Comment by lukebemish** [comment]
Could be, though I don't see you loading the class in question in that plugin. Sunconure11, can you find a minimal set of mods to reproduce this issue?

**Comment by itsmeow** [comment]
`advanced_runtime_resource_pack` looks like that?
