### ISSUE TITLE
Space Dimensions Compatibility

### ISSUE THREAD

**Issue by HacoKavanah** [itsmeow/betteranimalsplus#341]
Simple: Space Dimensions add various planets and moons. Better Animals Plus-folk spawn on these planets and die almost immediately do to lack of oxygen. Could u make it so the dimensions from this mod are automatically blacklisted?

 - Minecraft Version: 1.18.2
 - Architectury API Version: 4.4.68
 - Platform: Fabric
 - Fabric Loader Version: 0.14.6
 - Fabric API Version: 0.53.4
 - Mod Version: 11.0.5

**Comment by itsmeow** [comment]
Are the space biomes actually unique biomes or include overworld ones? If not, you can just remove them in the config.

**Comment by ByPaco10** [comment]
Space Dimentions adds biomes

**Comment by itsmeow** [comment]
We cannot account for every situation in the default config generation. You can always use defaultconfigs and remove the space biomes.
