### ISSUE TITLE
Many animals endemic to snowy/frozen biomes are vulnerable to freezing damage

### ISSUE THREAD

**Issue by twome** [itsmeow/betteranimalsplus#342]
I'm referring to the same damage effect caused by being buried under loose snow. When other mods (Ecologics, Immersive Weathering) apply that effect to things like icy biome *water* and permafrost blocks, you get mass extinction events of animals that evolved to adapt to sub-zero temperatures - moose that walk upon permafrost, whales, sharks, saltwater eels etc. The Immersive Weathering author is changing their mod to only give that freezing effect to players, but it'd probably be a good idea for animal-adding mods to also update status vulnerabilites. 

If there are any "standardised" dehydration/heatstroke -style effects from other mods it might help future-proof BAP by giving desert fauna similar resistances. While we're at it, maybe immunities to any venoms/poisons for venomous animals (and their natural predators) for compatability with mods like Poison Dart Frogs, and, for a lark, immunity for eels to electrical shock damage (such as from Immersive Engineering's exposed power lines).

Thanks for the delightful mod; it was awesome hearing my new-to-modded friends gasp today every time they saw a new animal.

## Versions
 - Minecraft Version: 1.18.2
 - Platform (Forge/Fabric): Fabric
 - Fabric Loader Version: Latest
 - Fabric API Version: Latest
 - Mod Version: Latest

**Comment by itsmeow** [comment]
Aware of this, forgot to add this when porting to 1.17+. Thanks for the issue.
