### ISSUE TITLE
Crash in 1.19

### ISSUE THREAD

**Issue by 123FLO321** [itsmeow/betteranimalsplus#346]
## Describe what you were doing before the crash

The game crashes when the "create new world" screen is opened.

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Start Game
2. Create new world

## Crash Log (REQUIRED)
[crash-2022-06-10_20.35.13-client.txt](https://github.com/itsmeow/betteranimalsplus/files/8881949/crash-2022-06-10_20.35.13-client.txt)

## Versions
- Minecraft Version: 1.19
- Architectury API Version: 5.6.22
- Platform (Forge/Fabric): Fabric
- Fabric Version: 0.14.7
- Fabric Loader Version: 0.11.0
- Fabric API Version: 0.55.3
- Mod Version: 11.0.6

## Additional context

**Comment by itsmeow** [comment]
This crash report makes no sense, there is likely another mod at play in this crash.

**Comment by itsmeow** [comment]
Try this without BetterNether/BetterEnd and BCLib. It appears they have a mixin targeting the errored class. If this resolves it, I'd suggest opening an issue on the BCLib GitHub.

**Comment by 123FLO321** [comment]
Even without BCLib it crashes.
The modlist in the crash report works fine Better Animals disabled.

BetterNether/BetterEnd and BCLib and Better Animals in it's own modpack works fine.
So it must an incompatibility between Better Animals and some other mod in that list.
I'll try if i can figure out which one it is.

**Comment by 123FLO321** [comment]
Minimal setup to reproduce:
- architectury-5.6.22.jar
- betteranimalsplus-1.19-11.0.6-fabric.jar
- thonkutil-2.15.2+1.19.jar

**Comment by KawaiiUzi** [comment]
I am having the same issue as well i looked around and people are saying has something to so with the architectury mod. seems like any mod that adds new mobs to the game is causing this issue.

**Comment by valkyrienyanko** [comment]
Well I'm using BetterNether, it adds new mobs to the game but it does not crash the game.

**Comment by Jab125** [comment]
I've found the issue: ThonkUtil adds to tags directly via a mixin, but doesn't create a new tag object when the tag is null

**Comment by aAndrew3030** [comment]
This explains the crash well
https://github.com/LimeAppleBoat/ThonkUtil/issues/21

**Comment by Jab125** [comment]
Issue fixed with the closure of LimeAppleBoat/ThonkUtil#21
