### ISSUE TITLE
Global Configuration File

### ISSUE THREAD

**Issue by BrekiTomasson** [itsmeow/betteranimalsplus#350]
This mod deserves a "global" configuration file where you can enable/disable specific mobs so that any new world created will have those settings applied. Having to make those changes on a per-world basis is very tedious and time-consuming.

(For reference, I'm running the mod in Fabric, 1.18.2)

**Comment by cybercat5555** [comment]
Put the edited config in the "defaultconfigs" folder and it applies to all
