### ISSUE TITLE
Bat-like mobs ( especially theese orange, I think ) destroy sand somehow and change sand to soulsand

### ISSUE THREAD

**Issue by Kasia1403** [itsmeow/betteranimalsplus#353]
Could this be fixed or turned off ?

**Comment by itsmeow** [comment]
Bro. I just closed your issue. We don't add this, it's not from our mod. Something else is doing it.

**Comment by itsmeow** [comment]
Now if you have further gripes go be dumb on our discord and not the GitHub

**Comment by Kasia1403** [comment]
So You are saying that bats from Your mod don't destroy sand ? Or that they don't change sand to soulsand ? Or about both things ? And if I will tell You that I'm disabled, will it change Your mind or not ? Hope it's not too much questions.

**Comment by itsmeow** [comment]
They don't do any of that
