### ISSUE TITLE
Fabric 1.18.2 Watchdog crash (Suspected mod Better Animals Plus)

### ISSUE THREAD

**Issue by Gamerbolts** [itsmeow/betteranimalsplus#357]
## Describe what you were doing before the crash

I was testing my modpack and running a server, had my client connected and was doing some things in the background when I came back I noticed that Minecraft has Timed Out. I checked my server and saw it had crashed.

## To Reproduce

Steps to reproduce the behavior (if possible):
I am on a custom modpack

## Crash Log (REQUIRED)
[crash-2022-07-14_17.51.41-server.txt](https://github.com/itsmeow/betteranimalsplus/files/9116806/crash-2022-07-14_17.51.41-server.txt)
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/9116808/latest.log)

## Versions
- Minecraft Version: 1.18.2
- Architectury API Version: 4.5.76
- Platform (Forge/Fabric): Fabric
- Fabric Loader Version: 0.14.8
- Fabric API Version: 0.57.0
- Mod Version: 11.0.5

## Additional context
This is a rather large modpack so I know the issue could be hard to pinpoint but thought I would let you know anyway. Any help is appreciated. thank you!

**Comment by itsmeow** [comment]
Has this occurred more than once? It looks like a really strange edge case with internal Minecraft stuff. I don't think it was actually caused by the mod, we just got caught in the stacktrace.

**Comment by Gamerbolts** [comment]
Only once so far. Yeah I was thinking it was probably a one off but wanted to report it :) thanks!
