### ISSUE TITLE
[Fabric 1.18.2] Better Animals causing a crash with Charm on client

### ISSUE THREAD

**Issue by thedeerirty** [itsmeow/betteranimalsplus#358]
## Describe what you were doing before the crash

Throwing Charm into my mods flares an issue with this mod on initilization. Doesn't, weirdly enough, happen serverside. 

## To Reproduce

Steps to reproduce the behavior (if possible):
Throw any recent version of Charm (Fabric) together with this mod on 1.18.2.

## Crash Log (REQUIRED)

[crash-2022-07-23_12.33.19-client.txt](https://github.com/itsmeow/betteranimalsplus/files/9174172/crash-2022-07-23_12.33.19-client.txt)
(also here's the latest.log as I know that sometimes also helps)
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/9174173/latest.log)

## Versions
- Minecraft Version: 1.18.2
- Architectury API Version: tesed both 4.5.74 and 4.6.77
- Platform (Forge/Fabric): Fabric
- Fabric Loader Version: 0.14.8
- Fabric API Version: 0.56.0
- Mod Version: 11.0.5

## Additional context
Very aware it could be unrelated to your mod, and simple mention it as minecraft's funky; regardless, I hope you can shed some light on what's going on here, because I'm confused myself.

**Comment by itsmeow** [comment]
This looks like a problem with charm, it just so happens that it happened during our initialization phase and crashed, we don't mixin `ClientPacketListener` at all (class_634)
