### ISSUE TITLE
Crashes With Exit Code 1 When Loaded With Whisperwoods

### ISSUE THREAD

**Issue by Vadertot** [itsmeow/betteranimalsplus#359]
## Describe what you were doing before the crash
Loading Game

## To Reproduce
I isolated the issue by removing all other mods and left the three below. They work by themselves but crash when combined.

architectury-5.10.33-forge.jar
betteranimalsplus-1.19-11.0.7-forge.jar
whisperwoods-1.19-2.1.1-forge.jar

Steps to reproduce the behavior (if possible):
Load with Whisperwoods

## Crash Log (REQUIRED)
All I have is Exit Code 1 from launcher

## Versions
- Minecraft Version: 1.19
- Architectury API Version: architectury-5.10.33-forge
- Platform (Forge/Fabric): Forge
- Forge Version: 41.1.0
- Fabric Loader Version:
- Fabric API Version:
- Mod Version: 1.19-11.0.7-forge

**Comment by itsmeow** [comment]
Fixed in eaf2882632ca11ed60e06288d0b7b4f2fd2a6e3f
