### ISSUE TITLE
Crash on logging into server

### ISSUE THREAD

**Issue by trav90** [itsmeow/betteranimalsplus#36]
**Describe what you were doing before the crash**
Logging into server

**To Reproduce**
Steps to reproduce the behavior (if possible):
try logging into server

**Crash Log [(REQUIRED)**]
https://paste.dimdev.org/azoxexofor.mccrash

**Versions:**
 - OS: Manjaro Linux (server running on CentOS 7)
 - MC Version: 1.12.2
 - Mod Version: 4.1.0

**Additional context**
The server is a private server that runs a modified version of the Direwolf20 pack. In addition to Better Animals +, the Familiar Fauna, BetterFps and VanillaFix mods have been manually added to the pack.

**Comment by itsmeow** [comment]
Hmm looks like your NBT data could be corrupted. Did the server force shutdown? Also, can I get your world file / region data?
I did notice this in the crash.

> -- Entity being ticked --
>   Entity Type: betteranimalsplus:lammergeier (its_meow.betteranimalsplus.common.entity.EntityLammergeier)
>   Entity ID: 20924
>   Entity Name: Lammergeier
>   Entity's Exact location: 1739.35, 75.00, 2153.42
>   Entity's Block location: World: (1739,75,2153), Chunk: (at 11,4,9 in 108,134; contains blocks 1728,0,2144 to 1743,255,2159), Region: (3,4; contains chunks 96,128 to 127,159, blocks 1536,0,2048 to 2047,255,2559)
>   Entity's Momentum: 0.00, -0.08, 0.00
>   Entity's Passengers: []
>   **Entity's Vehicle: ~~ERROR~~ NullPointerException: null
>   Entity NBT: ~~ERROR~~ ReportedException: Saving entity NBT**

**Comment by itsmeow** [comment]
[betteranimals-devbuild.zip](https://github.com/itsmeow/betteranimalsplus/files/2775284/betteranimals-devbuild.zip)
Try this build (may have some in development features, namely boars, but is fully stable)
If it still fails you have a few options:
> 1. Remove mod, load world, exit, add mod, load world
> 2. Repair your nbt data (delete the specific entity using NBTExplorer or send it to me to do it
> 3. Remove mod

**Comment by trav90** [comment]
> Hmm looks like your NBT data could be corrupted. Did the server force shutdown?

I should have mentioned previously that is is a client crash, not a server crash. I know the server was never forced shutdown, but it's possible the client was (it is crashing on my wife's machine).

> EDIT: Specifically (to save upload space) send me region/3.4.mca

Here it is:
[r.3.4.mca.zip](https://github.com/itsmeow/betteranimalsplus/files/2775669/r.3.4.mca.zip)

> Try this build 

I will try this build later today and will report back.

Thank you for looking into this it is appreciated!

**Comment by trav90** [comment]
Unfortunately the devbuild causes the server to crash on startup. Here's the log:

[crash-2019-01-19_09.48.54-server.txt](https://github.com/itsmeow/betteranimalsplus/files/2775700/crash-2019-01-19_09.48.54-server.txt)

**Comment by itsmeow** [comment]
[betteranimalsplus-devbuild-regiondata.zip](https://github.com/itsmeow/betteranimalsplus/files/2775845/betteranimalsplus-devbuild-regiondata.zip)

My bad on the crash. It's fixed. I removed the Lammergeier from the region data, but make a backup (rename the old one) just in case. This should fix it.

**Comment by trav90** [comment]
I can confirm the the server now starts up without crashing; thank you again!

After my wife and I play again (likely later today) I will report back on if the client-side crash still occurs.

**Comment by trav90** [comment]
OK, I was able to log into the server using the devbuild-2 without crashing and everything seems to work! My animal loving wife says Thank you!

I am seeing an oddity with the animal models, but will open a new issue for that.

**Comment by trav90** [comment]
Well, after playing for a little while (45 minutes or thereabouts) it crashed again. Looks like a similar crash, but with a different entity:

https://paste.dimdev.org/ikikaquwaw.mccrash

**Comment by itsmeow** [comment]
Was this while loading or just playing and crashed out of nowhere?

**Comment by trav90** [comment]
She was playing and stepped away for a moment. When she came back it had crashed.

**Comment by itsmeow** [comment]
Hmm, can I get the `debug.log` from one of the errored logs?

**Comment by trav90** [comment]
Sorry for my late response. After following the above instructions we were able to play for several hours with no crashes. Thanks!

**Comment by itsmeow** [comment]
Good! Any updates on #37?

**Comment by trav90** [comment]
Yes the above instructions seems to have fixes #37 as well. Thank you!

**Comment by itsmeow** [comment]
Fix released:
https://minecraft.curseforge.com/projects/betteranimalsplus/files/2672568

**Comment by Thundercatsffs** [comment]
Sorry for this necro-bump but ive had the same issue with a new version of the pack (11.0.5 - fabric). New ticket?

**Comment by itsmeow** [comment]
Yes please holy wow this is three years old, I'm certain your crash has nothing to do with this
