### ISSUE TITLE
Only reindeer shows up in entities when configuring

### ISSUE THREAD

**Issue by melaniepaul** [itsmeow/betteranimalsplus#360]
## Describe the bug
When trying to configure the entities, only reindeer shows up.

## To Reproduce
1. Start game
2. Hit escape
3. Click mods
4. Click Better Animals Plus
5. Click configure
6. Click entities
7. Only reindeer appears

## Expected behavior
All of the entities should appear in the list

## Screenshots
![image](https://user-images.githubusercontent.com/74322154/181881315-45c6fea2-b096-42e0-a31c-08facb711f91.png)

## Versions
 - Minecraft Version: 1.19
 - Architectury API Version: 5.10.33
 - Platform (Forge/Fabric): Fabric
 - Fabric Loader Version: 0.14.8
 - Fabric API Version: 0.58.0+1.19
 - Mod Version: 1.19-11.0.7

**Comment by itsmeow** [comment]
This is the client config, we use serverconfigs for our entity configuration, you need to open the file itself and not the GUI

You have to create a world first, then it'll show in GUI and also create the file
