### ISSUE TITLE
shark, when grab you, will get immune/dont get hit from all damge even with ranged weapons?

### ISSUE THREAD

**Issue by babacon88** [itsmeow/betteranimalsplus#363]
## Describe the bug
when a shark gets a hold of you, you literally cannot hit it, even with ranged weapons, you are locked with him even in creative or spectator mod until you die

## To Reproduce
Steps to reproduce the behavior: just get mauled by a shark

## Versions
 - Minecraft Version:1.19
 - Architectury API Version:architectury-5.10.32-forge
 - Platform (Forge/Fabric):forge
 - Forge Version:1.19forge 14.1.0
 - Fabric Loader Version:
 - Fabric API Version:
 - Mod Version: betteranimalsplus-1.19-11.0.7-forge

## Additional context
will it get damged by potions at least?

**Comment by itsmeow** [comment]
Hi, you should try spamming shift to unmount the shark.
