### ISSUE TITLE
Domestication Innovation support

### ISSUE THREAD

**Issue by mimi-min** [itsmeow/betteranimalsplus#364]
## Is your feature request related to a problem? Please describe.

BAP animals don't behave in the way that Domestication Innovation lets vanilla/Alex's mobs do (adds "wander" to their following type).
I think this would include enchants, but I haven't tried it.

## Describe the solution you'd like

I'd like to be able to set pets to "wander" (roam around the area they've been set instead of just sitting).
There's also a tooltip in DI that notifies you of their state.

## Additional context

The developer of DI has this on their mod page:

> If you are a mod dev and want to make sure Domestication Innovation works out of the box for your mod, remember to make sure your tameable mob's class extends TameableAnimal.

I wonder if this means it's an easy fix?

Thanks in advance.

**Comment by itsmeow** [comment]
I don't think this would be reasonably possible at the moment, sorry
