### ISSUE TITLE
Crash caused by octopus 

### ISSUE THREAD

**Issue by EnderLiquid** [itsmeow/betteranimalsplus#365]
## Describe what you were doing before the crash

It happened on my modded server. My friend and I was on the sea and there were octopuses around.Suddenly we all got a client-side crash.It seemingly cause by an entity "octopus".Before this there was another similar crash caused by nautilus.

## To Reproduce

I haven't found a way to reproduce.

## Crash Log (REQUIRED)

https://pastebin.com/W24Mpb92

## Versions
- Minecraft Version:1.16.5
- Architectury API Version:1.30.53
- Platform (Forge/Fabric):Forge
- Forge Version:36.2.39
- Mod Version:11.0.4

**Comment by FoxyFox909** [comment]
Same crash is also occurring in Minecraft 1.12.2.

**Comment by itsmeow** [comment]
This appears to be an issue with your java and OpenGL, and not the mod
