### ISSUE TITLE
Wrong animal models

### ISSUE THREAD

**Issue by trav90** [itsmeow/betteranimalsplus#37]
**Describe the bug**
Some of the animals (Foxes and Goats specifically; possibly others) seem to be using the wrong models (see screenshots below).

**To Reproduce**
1. Look at a mob added by Better Animals +

**Log output/error (if present)**
[latest.log.txt](https://github.com/itsmeow/betteranimalsplus/files/2775894/latest.log.txt)

**Expected behavior**
Mobs to look correct.

**Screenshots**
![2019-01-19_13 04 37](https://user-images.githubusercontent.com/10595410/51431296-7d4de700-1bec-11e9-8e52-397818ed0a0f.png)
![2019-01-19_13 04 57](https://user-images.githubusercontent.com/10595410/51431297-7e7f1400-1bec-11e9-9735-98f18677d5e3.png)

**Versions:**
 - OS: Linux (Manjaro) 64-bit
 - MC Version: 1.12.2
 - Mod Version: 4.1.0-release (as well as devbuild-2)

**Additional context**
I'm assuming this is a conflict with one of the other mods I have installed. Using version 2.4.0 of the Direwolf20 pack with the following mods manually added:

Better Animals Plus 4.1.0-devbuild-2
Familiar Fauna 1.0.11
BetterFps 1.4.8
VanillaFix 1.0.10-99

**Comment by itsmeow** [comment]
I installed DW20 with the aforementioned mods and noticed no issues whatsoever. Is there any other factors that could affect this?

**Comment by trav90** [comment]
After removing the mod, starting the server and /fml confirming removal of mobs on server; then re-adding the mod this issue seems to be gone as well. Sorry for the noise.
