### ISSUE TITLE
Giant and colossal squid doesnt spawn in deep ocean

### ISSUE THREAD

**Issue by zeid0ne** [itsmeow/betteranimalsplus#372]
## Describe the bug
Giant and colossal squid doesnt spawn in deep ocean.

## To Reproduce
1. Go on deep Ocean in survival
2. Wait a long time

## Expected behavior
Giant and colossal squid spawn in deep ocean.

## Versions
 - Minecraft Version: 1.18.2
 - Architectury API Version: 4.9.83
 - Platform (Forge/Fabric): Fabric
 - Fabric Loader Version: 0.14.9
 - Fabric API Version: 0.58.0
 - Mod Version: 11.0.5

**Comment by itsmeow** [comment]
They are quite rare, as intended. Also, waiting in one spot does not mean one will spawn due to how spawning works. You will have to explore a lot of deep ocean

**Comment by zeid0ne** [comment]
Ok thanks
