### ISSUE TITLE
Tamed feral wolf tp in a place where they suffocate

### ISSUE THREAD

**Issue by zeid0ne** [itsmeow/betteranimalsplus#373]
## Describe the bug
Tamed feral wolf tp in a place where they suffocate. The targeted block to tp is free, but as the tamed feral wolf occupy several blocks, he can be partially in a wall and suffocate without the possibility of moving.

## To Reproduce
1. Make 2 island in an ocean with like 50 blocks separating them
2. On the second island, let only one block allowing wolf tp, and surround it with wall in east and south border
3. Spawn several Feral Wolf on first island, and tame them
4. Fly on the second island to trigger the tp of tamed wolf

## Expected behavior
Tamed Feral wolf doesnt tp in a place where they suffocate

## Versions
- Minecraft Version: 1.18.2
- Architectury API Version: 4.9.83
- Platform (Forge/Fabric): Fabric
- Fabric Loader Version: 0.14.9
- Fabric API Version: 0.58.0
- Mod Version: 11.0.5

##Screenshot

![image](https://user-images.githubusercontent.com/38461940/192490686-f805eb8e-2b8d-4ffc-a923-a8cb63a9d8c8.png)

**Comment by itsmeow** [comment]
This looks to be an issue with the vanilla pathfinder logic. I'm not really willing to invest the time to write my own so I'll just hope Mojang fixes it at some point.
