### ISSUE TITLE
Weird crash involving a sheep, a lamprey and misty world.

### ISSUE THREAD

**Issue by MrRedstoneA1** [itsmeow/betteranimalsplus#375]
## Describe what you were doing before the crash

I was walking around the Overworld and suddenly the game froze. I opened the log and saw that the game has crashed and a crash report was created.

## To Reproduce

I don't know exactly how to reproduce the crash, but according to the crash report, you must have Misty World installed, a lamprey must be attached to a sheep and the sheep must try to eat grass. According to the crash report, that's what happened when the game froze.

## Crash Log (REQUIRED)

[crash-2022-10-15_21.33.36-server.txt](https://github.com/itsmeow/betteranimalsplus/files/9792861/crash-2022-10-15_21.33.36-server.txt)

## Versions
- Minecraft Version: 1.12.2
- Architectury API Version: Not sure what this is. According to Google, it's a mod for minecraft 1.19
- Platform (Forge/Fabric): Forge
- Forge Version: 14.23.5.2860
- Fabric Loader Version: -
- Fabric API Version: -
- Mod Version: 1.12.2-9.0.1

## Additional context

This seems like a weird series of specific circumstances that have to happen for the game to crash. I think the culprit is Misty World, but the crash report does mention that a lamprey was attached to the sheep (entity's passengers: entityLamprey). Whether this is coincidence and not related to the crash, I don't know. I saw that a lamprey was involved and made this report. I will also post a crash report to Misty World. Note that I was not in Misty World, the involved sheep, lamprey and me were all in the Overworld.

**Comment by itsmeow** [comment]
1.12 is not supported anymore unfortunately!
