### ISSUE TITLE
Server crashes when I fly near ocean/Giant Squid

### ISSUE THREAD

**Issue by CybormanX** [itsmeow/betteranimalsplus#377]
## Describe what you were doing before the crash

Flying around loading in chunks. Flew near ocean shore and server crashed. This has happened at least 2 other times.

## To Reproduce

Go/fly near ocean. Supposedly near a squid.

## Crash Log (REQUIRED)

[crash-2022-11-11_15.54.35-server.txt](https://github.com/itsmeow/betteranimalsplus/files/9993730/crash-2022-11-11_15.54.35-server.txt)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_22.16.0_Forge_1.12.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.28.1_Forge_1.12.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 11/11/22 3:54 PM
Description: Ticking entity

java.lang.NoSuchMethodError: its_meow.betteranimalsplus.common.entity.EntityBAPCephalopod.func_189651_aD()Lnet/minecraft/util/math/Vec3d;
	at its_meow.betteranimalsplus.common.entity.EntityBAPCephalopod.func_70071_h_(EntityBAPCephalopod.java:80)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at its_meow.betteranimalsplus.common.entity.EntityBAPCephalopod.func_70071_h_(EntityBAPCephalopod.java:80)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: betteranimalsplus:giantsquid (its_meow.betteranimalsplus.common.entity.EntityGiantSquid)
	Entity ID: 1420
	Entity Name: Giant Squid
	Entity's Exact location: -857.50, 56.00, 580.50
	Entity's Block location: World: (-858,56,580), Chunk: (at 6,3,4 in -54,36; contains blocks -864,0,576 to -849,255,591), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['CybormanX'/1403, l='world', x=-767.67, y=106.06, z=559.51]]
	Chunk stats: ServerChunkCache: 445 Drop: 0
	Level seed: -5525400810344473706
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (88,64,-34), Chunk: (at 8,4,14 in 5,-3; contains blocks 80,0,-48 to 95,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 158462 game time, 180967 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 39497 (now: false), thunder time: 17840 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_351, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5192852800 bytes (4952 MB) / 5878841344 bytes (5606 MB) up to 5878841344 bytes (5606 MB)
	JVM Flags: 2 total; -Xmx6000M -Xms6000M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                  | Source                                        | Signature                                |
	|:------ |:-------------------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                                          | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99                | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2860             | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit                                    | 1.3.3-1.12               | minecraft.jar                                 | None                                     |
	| LCHIJA | xaerominimap_core                            | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| LCHIJA | xaeroworldmap_core                           | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                 | None                                     |
	| LCHIJA | passableleavescore                           | 1.0.0                    | minecraft.jar                                 | None                                     |
	| LCHIJA | damageindicatorsmod                          | 1.0                      | [1.12.2]DamageIndicatorsMod-3.5.0.jar         | None                                     |
	| LCHIJA | betteranimalsplus                            | @VERSION@                | betteranimalsplusplus-1-29-2022.jar           | None                                     |
	| LCHIJA | forgelin                                     | 1.8.4                    | Forgelin-1.8.4.jar                            | None                                     |
	| LCHIJA | bountiful                                    | 2.2.2                    | Bountiful-2.2.2.jar                           | None                                     |
	| LCHIJA | corpse                                       | 1.12.2-1.0.8             | corpse-1.12.2-1.0.8.jar                       | None                                     |
	| LCHIJA | cosmeticarmorreworked                        | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | craft_gunpowder_11                           | 1.1.0                    | CraftableGunpowder_1-1.jar                    | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.353               | movingworld-1.12-6.353-full.jar               | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar           | None                                     |
	| LCHIJA | orelib                                       | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                                    | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | findme                                       | 1.1.0                    | findme-1.12.2-1.1.0-8.jar                     | None                                     |
	| LCHIJA | llibrary                                     | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                                   | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCHIJA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jei                                          | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | mca                                          | 6.1.0                    | MCA-1.12.2-6.1.0-universal.jar                | None                                     |
	| LCHIJA | medieval_craft                               | 1.14.4                   | MedievalCraft-1.12.2-1.18.1.jar               | None                                     |
	| LCHIJA | millenaire                                   | Millénaire 8.1.2         | millenaire-8.1.2.jar                          | None                                     |
	| LCHIJA | naturescompass                               | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar               | None                                     |
	| LCHIJA | reccomplex                                   | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                  | None                                     |
	| LCHIJA | roguelike                                    | 2.4.1                    | RoguelikeDungeonsFnarEdition-1.12.2-2.4.1.jar | None                                     |
	| LCHIJA | uteamcore                                    | 2.2.5.226                | u_team_core-1.12.2-2.2.5.226.jar              | None                                     |
	| LCHIJA | usefulbackpacks                              | 1.5.4.85                 | useful_backpacks-1.12.2-1.5.4.85.jar          | None                                     |
	| LCHIJA | veinminer                                    | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| LCHIJA | veinminermodsupport                          | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| LCHIJA | villagermarket                               | 1.0.2                    | villager-market-1.12.2-1.0.2.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones                                    | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCHIJA | xaerominimap                                 | 22.16.0                  | Xaeros_Minimap_22.16.0_Forge_1.12.jar         | None                                     |
	| LCHIJA | w2w                                          | 1.2.1                    | w2w-1.2.1.jar                                 | None                                     |
	| LCHIJA | worleycaves                                  | 1.5.2                    | worleycaves-1.12.2-1.5.2.jar                  | None                                     |
	| LCHIJA | xaeroworldmap                                | 1.28.1                   | XaerosWorldMap_1.28.1_Forge_1.12.jar          | None                                     |
	| LCHIJA | passableleaves                               | 2.0.0                    | PassableLeaves-1.12.2-2.0.0.jar               | None                                     |
	| LCHIJA | rtg                                          | 6.1.0.0-snapshot.1       | RTG-1.12.2-6.1.0.0-snapshot.1.jar             | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
XaeroMinimapPlugin (Xaeros_Minimap_22.16.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.28.1_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['CybormanX'/1403, l='world', x=-767.67, y=106.06, z=559.51]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

## Versions
- Minecraft Version: 1.12.2
- Architectury API Version:
- Platform (Forge/Fabric): Forge
- Forge Version: 14.23.5.2860
- Fabric Loader Version:
- Fabric API Version:
- Mod Version:  1-29-2022 

## Additional context
Have mercy on me; I have no idea what I'm doing in general. This is my first attempt at a modded server.

**Comment by itsmeow** [comment]
Unfortunately Minecraft 1.12 is no longer supported.
