### ISSUE TITLE
Fabric enchantment "Beheading" related to animal heads

### ISSUE THREAD

**Issue by notIkibo** [itsmeow/betteranimalsplus#378]
## Is your feature request related to a problem? Please describe.
Just a little comat with fabric enchantment on that regards. Idk what the percentage of getting a head is, but getting every variant of animal heads is a tough task and that plus 5% wouldn't hurt

**Comment by itsmeow** [comment]
Ahhh, a problem with the way the head drops work, it's done in the code, and not with loot tables so it would be very difficult to do compat for this. I don't really want to do this currently.
