### ISSUE TITLE
Crashes on 1.19.3

### ISSUE THREAD

**Issue by TheButterbrotMan** [itsmeow/betteranimalsplus#379]
## Describe what you were doing before the crash

Loading Game

## Crash Log (REQUIRED)
https://bytebin.lucko.me/ugWIitwKwi
Get your minecraft crash log and paste it here.

## Versions
- Minecraft Version: 1.19.3
- Architectury API Version: 7.0.64
- Platform (Forge/Fabric): Fabric
- Fabric Loader Version: 0.14.11
- Fabric API Version: 0.68.1+1.19.3
- Mod Version: 1.19-11.0.7

**Comment by HacoKavanah** [comment]
Same here.

**Comment by itsmeow** [comment]
1.19.3 is currently not supported
