### ISSUE TITLE
BAP latest version causing mixin crash

### ISSUE THREAD

**Issue by otavio-silva** [itsmeow/betteranimalsplus#381]
## Describe what you were doing before the crash
Crashes on trying to launch the game after updating mod
## To Reproduce

Steps to reproduce the behavior (if possible):
1. Update mod
2. Click to launch game
3. See error

## Crash Log (REQUIRED)

https://mclo.gs/8M7PBCP

## Versions
- Minecraft Version: 1.19.2
- Architectury API Version: 6.4.62
- Platform (Forge/Fabric): Fabric
- Fabric Loader Version: 0.14.11
- Fabric API Version: 0.69.0
- Mod Version: 11.0.8

**Comment by TheeMrCheeky** [comment]
Same

**Comment by itsmeow** [comment]
Let me know if that fixed it, should've!
