### ISSUE TITLE
Crash when loading the world with mod Whisperwoods present

### ISSUE THREAD

**Issue by otavio-silva** [itsmeow/betteranimalsplus#382]
## Describe what you were doing before the crash
Loading my already created and functional world

## To Reproduce

1. Open Minecraft
2. Click on load world
3. See error

## Crash Log (REQUIRED)

https://mclo.gs/w9B6UEM

## Versions
- Minecraft Version: 1.19.2
- Architectury API Version: 6.4.62
- Platform (Forge/Fabric): Fabric
- Fabric Loader Version: 0.14.11
- Fabric API Version: 0.69.0
- Mod Version: 11.0.9

## Additional context
Whisperwoods seems to be related

**Comment by itsmeow** [comment]
Every day I hate this language and game more

**Comment by pokesmells** [comment]
[crash-2022-12-24_06.09.42-server.txt](https://github.com/itsmeow/betteranimalsplus/files/10298544/crash-2022-12-24_06.09.42-server.txt)
[crash-2022-12-24_06.17.20-server.txt](https://github.com/itsmeow/betteranimalsplus/files/10298545/crash-2022-12-24_06.17.20-server.txt)

**Comment by pokesmells** [comment]
Same here, same issue cannot do anything

**Comment by itsmeow** [comment]
Fixed in eaf2882632ca11ed60e06288d0b7b4f2fd2a6e3f
