### ISSUE TITLE
[Quilt] [1.19.2] Game crashes on world creation.

### ISSUE THREAD

**Issue by paulhlschr** [itsmeow/betteranimalsplus#384]
## Describe what you were doing before the crash

I was loading up the game and was about to create a new world. After confirming my world settings and starting the generator, the game log told me, that the game crashed. Minecraft itself was not responsive and I had to force kill the process.

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Create a new world.
3. Game crashes. Error in console.

## Crash Log (REQUIRED)

[Crash log](https://mclo.gs/NYzO313)

## Versions
- Minecraft Version: 1.19.2
- Architectury API Version: 6.4.62
- Platform (Forge/Fabric): Quilt
- Quilt Loader Version: 0.17.8
- Quilted Fabric API Version: 4.0.0-beta.25+0.70.0-1.19.2
- Mod Version: 1.19.2-11.0.9

## Additional context
I am aware that Quilt has its peculiarities compared to Fabric. **With Fabric there is no crash.** So I don't expect a fix here. Nevertheless, I wanted to document the issue here to make you aware of it. 

Thanks for your work! :)

**Comment by itsmeow** [comment]
11.0.7 should work still on Quilt.. Looks like another consequence of a dumb change I did. I really hate this game

**Comment by Surpos0** [comment]
i have same issue but on fabric. i have same log with "meow". And i just can't not only create world but i can't either play on already generated worlds.

**Comment by itsmeow** [comment]
Fixed in eaf2882632ca11ed60e06288d0b7b4f2fd2a6e3f
