### ISSUE TITLE
Game crashes while creating world

### ISSUE THREAD

**Issue by TheRealPicasso** [itsmeow/betteranimalsplus#385]
## Describe what you were doing before the crash

I was trying to create a world with my mods installed.

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Spawn '...'
3. See error

## Crash Log (REQUIRED)

[crash-2022-12-28_00.48.30-server.txt](https://github.com/itsmeow/betteranimalsplus/files/10311436/crash-2022-12-28_00.48.30-server.txt)

Get your minecraft crash log and paste it here.

## Versions
- Minecraft Version: 1.18.2
- Architectury API Version: architectury-4.10.88-fabric.jar
- Platform (Forge/Fabric): Fabric
- Forge Version: -
- Fabric Loader Version: Fabric - 0.14.11
- Fabric API Version: fabric-api-0.67.0+1.18.2.jar
- Mod Version: betteranimalsplus-1.18.2-11.0.8-fabric.jar

**Comment by GameBurrow** [comment]
Getting the same error on MC: 1.19.2 & Fabric 0.14.11 & 0.14.12 with 11.0.9. In my case the game doesn't crash but the world keeps loading foerver. Reverting pack to 11.0.7 works fine.

Noticing on curseforge comments, same is being reported.

**Comment by TheRealPicasso** [comment]
> Getting the same error on MC: 1.19.2 & Fabric 0.14.11 & 0.14.12 with 11.0.9. In my case the game doesn't crash but the world keeps loading foerver. Reverting pack to 11.0.7 works fine.
> 
> Noticing on curseforge comments, same is being reported.

Yea i reverted it too, hopefully gets fixed soon :)

**Comment by itsmeow** [comment]
Fixed in eaf2882632ca11ed60e06288d0b7b4f2fd2a6e3f
