### ISSUE TITLE
[1.19.3] Client crash on startup java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by ProsperCraft** [itsmeow/betteranimalsplus#387]
## Describe what you were doing before the crash

Loading the game with only Better animals plus and Architectury.

## To Reproduce

Steps to reproduce the behavior (if possible):
Install a fresh instance of 1.19.3 with Fabric and BEtter animals plus and Arch.

## Crash Log (REQUIRED)

[Get your minecraft crash log and paste it here.](https://gist.github.com/ProsperCraft/640668637c3403260e5b237d8a6d0e39)

## Versions
- Minecraft Version: 1.19.3
- Architectury API Version: 7.0.66
- Platform (Forge/Fabric): Fabric
- Forge Version:
- Fabric Loader Version: 
- Fabric API Version: 0.73.0+1.19.3
- Mod Version: 1.19-11.0.7

**Comment by itsmeow** [comment]
1.19-11.0.7 does not work on 1.19.3.

We have betas for 1.19.3 in our Discord but otherwise try 1.19.2. I also suggest 11.0.10 over 11.0.7

**Comment by ProsperCraft** [comment]
The confusion is that this https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus/files/3884095 is flagged in such a way that it is showing up when selecting mods for Fabric 1.19.3.  I think if you change the tags it will stop showing up until you a ready for 1.19.3

**Comment by itsmeow** [comment]
It is not tagged with 1.19.3 so I don't know what to tell you. Looks to be an issue with CF
