### ISSUE TITLE
Glowing Animals on SEUS

### ISSUE THREAD

**Issue by Broozyr** [itsmeow/betteranimalsplus#389]
## Describe the bug
Feral Wolves, Spiders, Tarantulas, and Coyotes all appear glitched in SEUS shaderpacks due to their glowing eyes. 

## To Reproduce
Spawn one of these animals.
Observe.

## Log output/error (if present)
No output error.

## Expected behavior
I expected the eyes to glow normally. Perhaps add an option to disable glowing eyes if there is no way to fix it?

## Screenshots
![image](https://user-images.githubusercontent.com/123692849/214956124-fb1db25d-6a31-4b0b-a441-2f3016471234.png)

## Versions
1.12.2

## Additional context
Coyotes only glow at night due to how their eyes work.

**Comment by itsmeow** [comment]
Unfortunately 1.12 is no longer supported and shaders are even more difficult to support so I cannot help you.
