### ISSUE TITLE
Log spam [03:02:59] [Server thread/WARN] [minecraft/SynchedEntityData]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityButterfly from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainerContainable

### ISSUE THREAD

**Issue by MarioPEgamer** [itsmeow/betteranimalsplus#392]
## Describe the bug
In the log of the Minecraft server the following line is spammed again and again when I run through the world:
[03:02:59] [Server thread/WARN] [minecraft/SynchedEntityData]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityButterfly from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainerContainable

## To Reproduce
Set up a Minecarft server with Forge version 40.2.0 or 40.2.1 and install the better animals plus mod.
In my case I used the following server:
https://magmafoundation.org/ (Minecraft Forge and Bukkit hybrid)

## Expected behavior
The above line is not spammed into the log.

## Versions
 - Minecraft Version: 1.18.2
 - Architectury API Version: 4.11.89
 - Platform (Forge/Fabric): Forge
 - Forge Version: 40.2.1
 - Mod Version: 11.0.10

## Additional context
There was a similar problem with an older version of the mod:
#236

**Comment by itsmeow** [comment]
Unfortunately there is no way to get around or disable this with how the mod is setup. The logging is a warning from Forge that I am unable to suppress despite it not applying in this case.
