### ISSUE TITLE
Biomes Configurations spawn mobs

### ISSUE THREAD

**Issue by MacKey-255** [itsmeow/betteranimalsplus#40]
Buenas, muchos usuarios juegan con el mod de biomas BiomesOPlenty, en el cual no spawnean los animales del Better Animals Plus. Solo aparecen en los biomas de Minecraft. Si puedieran hacer algun tipo de compatibilidad con dicho mods, sera super cool. SAlu2s

**Comment by itsmeow** [comment]
He probado el desove con BOP y funciona hasta donde sé. ¿Has probado esto tú mismo? No hay ninguna razón por la cual el código no genere.

**Comment by MacKey-255** [comment]
Probe y no se genera en todos los biomas, solo en algunos como nieve, desierto o otros que son generaicos o presentan partes del propio minecraft

**Comment by itsmeow** [comment]
Utilizo tipos de biomas genéricos para configurar biomas de desove, por lo que debería funcionar con BOP. Entiendo que digas que no, pero estoy seguro al ochenta por ciento que sí. De lo contrario, esto sería un problema si BOP no registra tipos de biomas. Sé que los animales se reproducen en los biomas de Traverse.

**Comment by MacKey-255** [comment]
El problema radica en que algunos biomas del BoP creo, que no estan afiliados a los tipos de biomas genericos (algunos). Y alli es cuando otros mods han creado un simple sistema en la configuracion, donde carga un pequeño listado de los biomas, tanto los de Minecraft como los del BoP, para saber con mas exactitud el spawn de los mobs. Yo he probado y no spawnean en todos los biomas del BoP, solo en algunos que hacen referencia al generico, como los de nieve, desierto y algunos bosques. Te recomiendo hacer esa configuracion extra para quitarte el trabajo de programar la compatibilidad con los mods de biomas. SAlu2s

**Comment by itsmeow** [comment]
Bueno. Cambiar el nombre de este problema a "configuración de bioma" (en inglés para que otros puedan leer)

**Comment by MacKey-255** [comment]
Te pongo un simple ejemplo:
`7-worldgenmobs {
    S:"Bear" <
        minecraft:forest
        minecraft:swampland
        minecraft:roofed_forest
        minecraft:redwood_taiga
        minecraft:jungle
        biomesoplenty:bayou
        biomesoplenty:boreal_forest
        biomesoplenty:brushland
        biomesoplenty:coniferous_forest
        biomesoplenty:flower_field
        biomesoplenty:grove
        biomesoplenty:lush_swamp
        biomesoplenty:marsh
        biomesoplenty:moor
        biomesoplenty:orchard
        biomesoplenty:redwood_forest
        biomesoplenty:temperate_rainforest
        biomesoplenty:wetland
        biomesoplenty:mangrove
        biomesoplenty:tropical_island
        biomesoplenty:flower_island
     >
}`

**Comment by Graywaren** [comment]
I can't understand most of this unfortunately, but I believe this is one of the features I'm also looking for! I very much want to be able to determine the biomes that a particular animal can spawn in via biome dictionary tags as well as the ability to whitelist/blacklist specific biome ids. This would be wonderful.

**Comment by itsmeow** [comment]
@Graywaren Yep. Plan is to have the default config generate with the current biomes and allow modifications to the list of biomes. However, due to the way the biome system works it will be strictly whitelist.

**Comment by Graywaren** [comment]
Awesome! I look forward to it

**Comment by itsmeow** [comment]
Issue solved in acc091ca0f46b26caa187d5748699d3e237c6deb
Will release with 5.0.0.

> Problema resuelto en acc091ca0f46b26caa187d5748699d3e237c6deb
Se lanzará con 5.0.0.

See here:
![image](https://user-images.githubusercontent.com/10366817/52530239-07f7a280-2cd0-11e9-8dce-3cdf6bf44164.png)

**Comment by itsmeow** [comment]
5.0.0 lanzó.
https://minecraft.curseforge.com/projects/betteranimalsplus/files/2672568
