### ISSUE TITLE
[question] Invalid biome "???" for entity ???

### ISSUE THREAD

**Issue by IceflowRE** [itsmeow/betteranimalsplus#403]
I get a lot of 
```
[Server thread/ERROR] [dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer.EntityConfiguration/]: Invalid biome "minecraft:giant_spruce_taiga_hills" for entity lammergeier. No biome exists with that name. Skipping.
```
when updating  a world from 1.18.2 to 1.19.2. Can this error be ignored?
Version: 11.0.10

**Comment by itsmeow** [comment]
Yes, this just means that the biomes listed in the spawning configuration no longer exist (giant taigas were removed/renamed in 1.19.2). You can manually remove them to suppress the error.

If you haven't changed the configs, the easiest method to do so is just deleting the existing one, as it will regenerate with the correct defaults.

Configs are located in `saves/(world)/serverconfigs/` or `world/serverconfigs/` on dedicated servers.
