### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by iamtaya122** [itsmeow/betteranimalsplus#404]
not an issue but a question! looking to feature this mod into a youtube video and was wondering how long it took to make this mod from start to finish? thanks in advance! love this mod!

**Comment by itsmeow** [comment]
Well we started development in August 2018, and released 1.0 in September 2018, but the mod was continuously updated with new features until January 2023.

You can read about our early history on the wiki to get more specific dates:
https://better-animals-plus.fandom.com/wiki/History
