### ISSUE TITLE
Duplicate ID Value spam in log

### ISSUE THREAD

**Issue by Enterprise12nx01** [itsmeow/betteranimalsplus#407]
## To Reproduce
1. Play on any world with this mod
2. Check console for spam
3.

## Log output/error (if present)
[Get your minecraft log and paste it here.] (https://pastebin.com/rVw1jX5u)

## Expected behavior
No errors

## Screenshots
NA

## Versions
 - Minecraft Version: 1.19.2
 - Architectury API Version: 6.6.92
 - Platform (Forge/Fabric): Forge
 - Forge Version: 43.4.4
 - Fabric Loader Version:
 - Fabric API Version:
 - Mod Version: 11.0.10

## Additional context
I notice the world taking awhile to load an area sometimes, idk if that is related to this issue, but i do see this error keep spamming, sometimes it mentions id 22/23

**Comment by itsmeow** [comment]
This is unrelated and a Forge warning that doesn't apply to the mod.

**Comment by Enterprise12nx01** [comment]
> This is unrelated and a Forge warning that doesn't apply to the mod.

so its safe to ignore it? is there a reason its happening? its specifically mentioning only the feral wolf and Lammergeier
using their spawn egg, they wont spawn with it either, and when i attempt it, the error shows up

**Comment by itsmeow** [comment]
Ohh are you using the latest 1.19 version? That's a different error with the network manager. It doesn't usually cause any problems but yes I'm aware of it it's fixed in dev

**Comment by Enterprise12nx01** [comment]
> Ohh are you using the latest 1.19 version? That's a different error with the network manager. It doesn't usually cause any problems but yes I'm aware of it it's fixed in dev

yes i am! im not sure if its related to the world freezing up loading, but everytime it happens the error does appear. Not sure if its some interaction, i have sophisticated wolves and alex's mobs too, although i disabled some duplicate mobs from spawning
Those 2 mobs specifically wont even spawn with spawn eggs, but others have from my testing
