### ISSUE TITLE
Jellyfish levitating above Water & Icon Size

### ISSUE THREAD

**Issue by Graywaren** [itsmeow/betteranimalsplus#41]
**Describe the bug**
Jellyfish float above water. This seems to be related to their hitbox, which appears at the bottom of their tentacles. There's a closed bug for this, but it still seems to be happening. 

Also their map mob icon is way too big

I included a screen shot. You can see 4 jellies floating above the water and how large their map icon is in comparison to fish. They're also about 2-3x the size of normal land mobs. I'm guessing this is based on the size of an icon file?

**To Reproduce**
1. Create world
2. find some jellyfish
3. Occasionally some will be floating above the water. 

**Expected behavior**
Jellyfish shouldn't levitate! lol

**Screenshots**
https://pasteboard.co/I09c8Ax.png

**Versions:**
 - OS: Windows 10
 - MC Version: 1.12.2
 - Mod Version: 4.1.0

**Additional context**
Here's a pastebin of all my mods.
https://pastebin.com/xmNu2Chp

**Comment by itsmeow** [comment]
I closed this issue because it has already been resolved on the development branch, but hasn't been released yet. In the future, you can comment on existing issues and they may be re-opened.
I do not have control over icon sizes, but I have reduced the max spawn size of jellyfish as well.
You'll have to wait until 5.0.0 is done.

**Comment by Graywaren** [comment]
Ohhh. Thanks! I  misunderstood the timing of the fix, I though it was in the released version already and not working vs an upcoming one. Glad to hear it's on its way. Thanks for the info!

**Comment by itsmeow** [comment]
5.0.0 has been released - https://minecraft.curseforge.com/projects/betteranimalsplus/files/2672568

**Comment by Graywaren** [comment]
Awesome!!
