### ISSUE TITLE
Cooking Venison doesn't increase the food levels

### ISSUE THREAD

**Issue by Froggy800** [itsmeow/betteranimalsplus#43]
As per title, Raw Venison and Cooked Venison appear to have the same nutrition values (1,5 food and 1,5 saturation).

Tested on Better Animals Plus version 5.0.1 on Forge 14.23.5.2814

**Comment by itsmeow** [comment]
Does the same happen for pheasant meat?

**Comment by Froggy800** [comment]
Nope, Pheasant meat gains one point of food and one poit of saturation upon cooking.

**Comment by itsmeow** [comment]
Resolved by a123f333431fedb430be9890d01e126e318884c3. Will release with 1.13 as a patch for 5.0.
