### ISSUE TITLE
deer head displays different variants based on angle

### ISSUE THREAD

**Issue by TheOneTraveler** [itsmeow/betteranimalsplus#44]
**Describe the bug**

**To Reproduce**
1.) place down deer head [Variant 1]
2.) look at it from all angles
**Log output/error (if present)**
N/A

**Expected behavior**
i expected it to only render 1 variant at a time

**Screenshots**
i have created an imgur album to display the bug
https://imgur.com/gallery/WdB4taV
**Versions:**
 - OS: Windows 10
 - MC Version: 1.12.2
 - Mod Version: 5.0.1

**Additional context**
null

**Comment by itsmeow** [comment]
Are you using Optifine or some other strange TESR rendering system? This does not happen on it's own.

**Comment by itsmeow** [comment]
Most likely optifine, which is not supported. Use foamfix + betterfps if you want performance and not this bug combined.
