### ISSUE TITLE
cant pick up dropped boar heads (on occasion)

### ISSUE THREAD

**Issue by TheOneTraveler** [itsmeow/betteranimalsplus#45]
**Describe the bug**
i killed a group of about 4 boars, the first one i killed dropped a head and i picked it up no problem, then the last one i killed also dropped a head, but no matter what i do, i still cant pick up the head. i tested if the issue might be lag by breaking a few blocks around the item, and i could pick up blocks just fine, but i could not pick up the boar head.
**To Reproduce**
1. Spawn spawn a few boars
2. kill them in survival
3. try picking up the heads they drop (mind you i cant reproduce the same bug every single time, only on occasion.

**Log output/error (if present)**
N/A

**Expected behavior**
i expected to pick up the head of the boar i just killed

**Screenshots**
https://i.imgur.com/ElryInm.png

**Versions:**
 - OS: Windows 10
 - MC Version: 1.12.2
 - Mod Version: 5.0.1

**Additional context**
null

**Comment by itsmeow** [comment]
Yeah - it's because they only exist on the client. I forgot to put a `!world.isRemote` check on the dropping logic. Relogging should fix this.

**Comment by itsmeow** [comment]
Resolved in 1.13 branch - 1.12 pending

**Comment by itsmeow** [comment]
Will release whenever 1.13 releases as a patch for 5.0
