### ISSUE TITLE
Loot tables for deer not found

### ISSUE THREAD

**Issue by katubug** [itsmeow/betteranimalsplus#49]
**Describe the bug**
I'm using LootTweaker-1.12.2-0.0.9 (for CraftTweaker2-1.12-4.1.17) with Better Animals Plus 5.0.2 and I'm trying to edit the drop tables for the deer. I used /ct loottables target when looking at the deer entity, which produced "dumps/loot_tables/betteranimalsplus/deer.json."

According to the LootTweaker documentation, to edit the table I'd need to call the table with "LootTables.getTable("betteranimalsplus/deer");" However, when I do this, my game gives me an error that says that loot table doesn't exist. Bizarrely, it DOES seem to have properly modified the drop table, even though it supposedly doesn't exist. Even more bizarrely, the deer don't seem to drop ANYTHING upon death. This leads me to believe that there might be some kind of issue here, which is why I'm reporting this.

**To Reproduce**
1. Spawn BAP deer.
2. With previously mentioned mods installed, type "ct loottables target"
3. In the /scripts/ folder, following the documentation [here](https://loottweaker-docs.readthedocs.io/en/latest/tutorials/adding-loot-basic.html), put the following code:

`//Remove Venison Drops from BetterAnimalsPlus`
`val bapDeer = LootTables.getTable("betteranimalsplus");`
`val bapDeerMain = bapDeer.getPool("deer");`
`bapDeerMain.removeEntry("betteranimalsplus:venisonraw");`

`//Add Pam's Venison to BetterAnimalsPlus`
`bapDeerMain.addItemEntry(<harvestcraft:venisonrawitem>, 5);`

**Log output/error (if present)**
"Error: No loot table with name minecraft:betteranimalsplus/deer exists!"

**Expected behavior**
The deer will not drop BAP venison, but HC venison instead.

**Versions:**
 - OS: Windows 7
 - MC Version: 1.12.2
 - Mod Version: 5.0.2

**Comment by itsmeow** [comment]
I've actually noticed this bug in modpacks (no drops/null loottables). It works fine with just BA+, but something about modpacks breaks it. I'll investigate more. Can you confirm this happens in a barebones pack with just Pam's, BA+, and LootTweaker?

**Comment by itsmeow** [comment]
Actually, do you have twilight forest/roots or another mod that adds deer? Possibly there is a conflict on the table IDs causing an error? Try testing barebones pack with and without any other mods that add deer.

**Comment by katubug** [comment]
I do have two other mods that spawn deer, Twilight Forest and Familiar Fauna. I have just slaughtered about 20 deer in a barebones pack (only BAP, LootTweaker and CraftTweaker), and not gotten a single drop aside from EXP.

Actually, I just loaded into a new world with ONLY Better Animals Plus installed, killed 10 deer, and still received no drops.

**Comment by itsmeow** [comment]
I will definitely look into this more when I have time. Just so you know, our venison is OreDicted under Pam's Venison as well, so it will be compatible in recipes.

**Comment by katubug** [comment]
Thanks for your help! Regarding the OreDicting, I definitely appreciate it but since I have so many deer, I thought it best to just unify the drops at the source and save everyone some inventory space. I do prefer your art for it, if I'm honest, but for sake of ease we went with Pam's.

Thanks again!

**Comment by itsmeow** [comment]
I'm not noticing this issue even with Familiar Fauna and Twilight Forest installed, even outside of dev. Can you confirm that this issue happens on forge 1.12.2-23.5.2824?

**Comment by itsmeow** [comment]
Actually, I think I've noticed the issue. Your error is targeting `"Error: No loot table with name minecraft:betteranimalsplus/deer exists!"`
The proper loot table should be: `betteranimalsplus:deer`

**Comment by itsmeow** [comment]
Just tested this in my personal pack - the issue definitely exists. I'm not sure why, though.

**Comment by itsmeow** [comment]
Hmm, so I've tested this on 5.0.2 vs 6.0.0 (in dev) on the same exact pack and it seems this has somehow been fixed in dev. I don't know how, but it is. So I'm going to mark this as solved and I'll leave a message here when 6.0.0 comes out.

**Comment by katubug** [comment]
> Actually, I think I've noticed the issue. Your error is targeting `"Error: No loot table with name minecraft:betteranimalsplus/deer exists!"`
> The proper loot table should be: `betteranimalsplus:deer`

Ah, yes, I was grasping at straws by changing the syntax around in case that was the problem. I've fixed it now.

Thanks for the help, and the great mod!

**Comment by itsmeow** [comment]
6.0.0 has released, this issue is fully resolved!
