### ISSUE TITLE
Spawn rate is way too high

### ISSUE THREAD

**Issue by angelnc1989** [itsmeow/betteranimalsplus#5]
**Describe the bug**
The spawn rate is way too high.

**Screenshots**
https://imgur.com/FqpZHnV

**Versions:**
 - OS: Windows 10
 - MC Version: 1.12.2
 - Mod Version: 1.1.0

**Comment by itsmeow** [comment]
Hi. This is a known bug caused by Biomes O Plenty. We are working on adjusting spawnrates in BOP Biomes. Outside of BOP everything spawns normally.

**Comment by angelnc1989** [comment]
Well, I am not using BoP.

**Comment by angelnc1989** [comment]
https://pastebin.com/UR939tpU

Probably Traverse.

**Comment by itsmeow** [comment]
Many of our users have used both Traverse and BOP and experiences no issues. Is there other mods that could be affecting this? Is this a public modpack I can download to test?

**Comment by angelnc1989** [comment]
It's a private pack. I included the modlist in my last response.

**Comment by nickjackson-ff** [comment]
This is happening in my pack, too: [Magic Explosion Murder](https://www.curseforge.com/minecraft/modpacks/magic-explosion-murder)

These mods overlap with @angelnc1989's mod list:
- BetterFps
- Bone Torch
- Carry On
- Chameleon
- Chisel
- Chisels & Bits
- CodeChicken Lib
- Comforts
- Controlling
- Cooking For Blockheads
- Cosmetic Armor Reworked
- CraftTweaker
- Diet Hoppers
- Dirt2Path
- Dynamic Surroundings
- Enchantment Descriptions
- Ender Storage
- Fairy Lights
- FastWorkbench
- FoamFix
- Fullscreen Windowed
- Hammer Core
- Inventory Tweaks
- JEI
- JEI Integration
- JourneyMap
- Just Enough Resources
- LagGoggles
- LLibrary
- Login Shield
- MetalChests
- MmmMmmMmmMmm
- Mo' Villages
- Mowzie's Mobs
- MTLib
- Mystical Agriculture
- Mystical Agradditions
- Nature's Compass
- Neat
- Nether Chest
- Open Glider
- Placebo
- Quark
- Redstone Paste
- Soul Shards Respawn
- Spartan Shields
- Storage Drawers
- Thaumcraft
- Thaumic Additions
- Thaumic Inventory Scanning
- Thaumic JEI
- Thaumic Periphery
- TombManyGraves
- Unlimited Chisel Works
- Waystones
- Wither Skeleton Tweaks

**Comment by itsmeow** [comment]
Resolved the issue by updating to the new registry system. (Commit 4671f20104c62c048de575bc820ea3241975aa16)
