### ISSUE TITLE
Boars dropping head items that are non-textured and cause crashes when placed.

### ISSUE THREAD

**Issue by katubug** [itsmeow/betteranimalsplus#50]
**Describe what you were doing before the crash**
A player of mine looted a boar head and, like a genius, placed the non-textured item in his base. Now anyone who enters the area is crashed out of the game.

**To Reproduce**
Kill boars until one drops a head, place the head.

**Crash Log (REQUIRED)**
https://paste.dimdev.org/sajihuzuqu.mccrash

**Versions:**
 - OS: Windows 7
 - MC Version: 1.12.2
 - Mod Version: 5.0.2

**Comment by itsmeow** [comment]
For a temporary solution to this issue you can use
`setblock 207 66 819 air`
I will look into this.

**Comment by katubug** [comment]
Thank you!

**Comment by itsmeow** [comment]
6.0.0 has released, this issue is fully resolved!
