### ISSUE TITLE
Deer not dropping venison

### ISSUE THREAD

**Issue by DWX12** [itsmeow/betteranimalsplus#51]
**Describe the bug**
Seems like a similar issue to the deer not dropping anything from before, but neither reindeer nor regular deer (I'm pretty certain that the hirschgeist is not supposed to drop any meat) drop any venison when killed. I have been getting heads from them though.

**To Reproduce**
1. Kill deer

**Expected behavior**
Kill deer get venison

**Versions:**
 - OS: Windows
 - MC Version: 1.12.2
 - Mod Version: betteranimalsplus-5.0.2

Thanks for creating this awesome mod.

**Comment by itsmeow** [comment]
Hey, thanks for the report! I meant to say in the last post, I resolved the loot table issue but the deer will probably not have drops. I have somehow (not sure how) resolved this issue in 6.0.0 so this issue is also solved (however not publicly until it releases). Sorry about the inclarity.

**Comment by itsmeow** [comment]
6.0.0 has released, this issue is fully resolved!
