### ISSUE TITLE
lamprey disappears after killed a mob

### ISSUE THREAD

**Issue by BlueWither** [itsmeow/betteranimalsplus#53]
**Describe the bug**
Lamprey despawns after killed mobs.

**To Reproduce**
1. Spawn lampreys
2. Spawn other mobs
3. Lamprey disappears 

**Versions:**
- Windows
 - MC Version:1.12.2
 - Mod Version:6.0.1

**Comment by BlueWither** [comment]
Hmm... I tried, but it didn't happened...
But sometimes lamprey disappears. I don't know why it happened...

**Comment by itsmeow** [comment]
It probably despawned naturally as most entities do when unloaded. Is that fine or should I disable it?

**Comment by BlueWither** [comment]
Hmm... they disappeared near from me.
Maybe it may just be my mistake.

**Comment by itsmeow** [comment]
Closing this unless it happens again.
