### ISSUE TITLE
Lamprey should not spawn in ocean

### ISSUE THREAD

**Issue by BlueWither** [itsmeow/betteranimalsplus#54]
**Is your feature request related to a problem? Please describe.**
I always see lampreys in ocean, but they are freshwater fish...
I know some lamprey live in ocean, but they should live in river mainly.

**Comment by itsmeow** [comment]
Sounds good to me. @cybercat5555 ?

**Comment by cybercat5555** [comment]
I'd say its far, keep them freshwater only (swamps, rivers, and the small ponds that generate)

**Comment by itsmeow** [comment]
Will do.
