### ISSUE TITLE
Lamprey which have no targets don't move?

### ISSUE THREAD

**Issue by BlueWither** [itsmeow/betteranimalsplus#55]
**Describe the bug** (Required)
When lamprey is idle, they don't swim before they found their prey.

**Versions:**
 - Forge Version: forge1.12.2-14.23.5.2796
 - MC Version:1.12.2
 - Mod Version:6.0.1

**Additional context**
Add any other context about the problem here. This may be skipped/removed.

**Comment by itsmeow** [comment]
This isn't actually a bug, I basically skipped adding wander AI. Will do.
