### ISSUE TITLE
Songbirds should fly higher and faster

### ISSUE THREAD

**Issue by BlueWither** [itsmeow/betteranimalsplus#56]
**Type**
Entity (Mob),

**Is your feature request related to a problem? Please describe.**
Songbirds are good ambient mobs, but they should fly higher and faster, like lammergeiers.

**Comment by PCAwesomeness** [comment]
I literally pointed out that they reuse the (frankly incredibly lousy) parrot AI, but Pythva explained that they don't really need anything more because all they'll be doing is flying from tree to tree, and that the bearded vulture AI will only be for raptors that soar long distances.

**Comment by itsmeow** [comment]
Yep. That's basically my reasoning. It's like how when there's a bird on the road and they fly away last second. It's basically "don't move unless I must or I see food"

**Comment by BlueWither** [comment]
OK, I see,
