### ISSUE TITLE
Pam's HarvestCraft replaces Raw Rabbit causing taming to not work + Configuration for taming items

### ISSUE THREAD

**Issue by RiekaGodfrey** [itsmeow/betteranimalsplus#58]
I seem to not be able to tame coyotes even when its day. Is there any mods that might cause this issue?

**Comment by itsmeow** [comment]
Not that I know of. Can you please follow the issue template? What are you trying? Mod version?

**Comment by RiekaGodfrey** [comment]
I am currently on MC 1.12.2 and the mod version is BetterAnimalsPlus 6.0.1
Sorry for the lack of information. I have not had to report for a issue for a mod.

I have been trying to tame a coyote with raw rabbit but nothing happens.No smoke/particles indicating if the coyote is getting tamed.

**Comment by RiekaGodfrey** [comment]
Okay so apparently the mod Pam's Harvestcraft changes the raw rabbit and cooked rabbit somehow and it just doesn't work like a vanilla raw rabbit.The issue is solved after removing Pam's Harvestcraft so basically BetterAnimals+ doesn't really work with HarvestCraft.

**Comment by JoelZBub** [comment]
It must be a mod other than Harvestcraft causing this issue. 
I tested it with only Harvestcraft and Better Animals Plus installed, and was able to tame a coyote with raw rabbit meat. (Note that it registers still as <minecraft:rabbit> in the screenshot below.)
![2019-05-18_22 58 37](https://user-images.githubusercontent.com/12024500/57977314-f22b0500-79c3-11e9-8371-d0845f65554f.png)
![2019-05-18_22 59 52](https://user-images.githubusercontent.com/12024500/57977315-f525f580-79c3-11e9-996e-92fac5fd0647.png)

**Comment by RiekaGodfrey** [comment]
@JoelZBub There is definitely another mod conflicting or causing issues.I'm just not sure how to figure what mod it is.

**Comment by itsmeow** [comment]
Press F3+H and hover over the rabbit item in inventory, it should have a tooltip with the Item ID, which will contain the mod name.

**Comment by RiekaGodfrey** [comment]
This is the Item ID I get which is why I thought HarvestCraft is conflicting with the mod.
![2019-05-22_08 34 17](https://user-images.githubusercontent.com/50659056/58139257-920abc00-7c6c-11e9-9995-2fb16da81441.png)

**Comment by itsmeow** [comment]
I don't see a reason that wouldn't work. There must be something else here.

**Comment by itsmeow** [comment]
Okay, so I should be able to fix this by checking item IDs rather than direct `==` comparison. This also introduces the concept of allowing a configurable taming item. So next update there will be a configuration for this as well as fixing issues with mods replacing item instances in the registry.
