### ISSUE TITLE
Tiles load before blocks causing null blockstate crash

### ISSUE THREAD

**Issue by katubug** [itsmeow/betteranimalsplus#59]
**Describe what you were doing before the crash**
So some friends and I were messing around with a command block that would /kill you if you pressed a button (we were bored I guess? I have no good excuse). And about every second or third time we died from it, we got disconnected from the server, with the attached crash log.

My assumption is that this is somehow related to the fact that players drop their heads upon death (which I thiiiiink is from Quark? I've attached my modlist in case it's something else). There are still some textureless heads in JEI so perhaps they're somehow related? Unsure.

**To Reproduce** (Required unless unknown)
Steps to reproduce the behavior (if possible):
1. Type /kill @p
2. Die, drop head.
3. Crash occurs.

**Crash Log (REQUIRED)**
https://paste.dimdev.org/otopefomoh.mccrash

**Versions:**
 - Forge Version: forge-1.12.2-14.23.5.2838-universal
 - MC Version: 1.12.2
 - Mod Version: betteranimalsplus-1.12.2-6.0.1

**Additional context**
Here is my full modlist: [mods.txt](https://github.com/itsmeow/betteranimalsplus/files/3222132/mods.txt)

**Comment by itsmeow** [comment]
There's something missing here, players do not drop any BA+ heads. The affected head is a block located at x 451, y 76, z 1940. It should be a hirschgeist skull. I've identified the bug, it seems it was rendering while the block itself was not loaded, causing the blockstate to be null, and by extension crashing the game while rendering. Not sure what actually caused the issue, maybe someone respawned near it and saw it without the chunk being loaded? I have no idea. I will resolve this.

**Comment by katubug** [comment]
Ah, that makes total sense actually. We have a Hirschgeist skull hanging in
our spawn lodge and that's where we were respawning. Sorry for the red
herring player heads, sometimes I think I know more than I do, lol.

Thanks for your response and for providing such good support for the mod.

**Comment by itsmeow** [comment]
And just a btw, the broken heads in JEI are because I recently "flattened" the heads, each variant has their own item ID now. I had to put an item on the original IDs so that when the world loaded it would not say "Missing ID conflict for ___ item".

**Comment by katubug** [comment]
Ah okay! I just hid them from JEI in my pack, so it's not at all a big deal. :)
