### ISSUE TITLE
1.1.2 crashes dedicated server Forge 1.12.2 build 2766

### ISSUE THREAD

**Issue by kreezxil** [itsmeow/betteranimalsplus#6]
Issue:  1.1.2 crashes dedicated server Forge 1.12.2 build 2766

Notes:
     on startup looking for a missing class

crash report:
http://paste.ubuntu.com/p/Nw58dbFcX6/

fml server latest:
http://paste.ubuntu.com/p/ZySyNcXh5y/

**Comment by nickjackson-ff** [comment]
I am also experiencing this issue with Forge 1.12.2 builds 2759 and 2768.

[crash-2018-10-07_12.21.00-server.txt](https://github.com/itsmeow/betteranimalsplus/files/2454131/crash-2018-10-07_12.21.00-server.txt)
[crash-2018-10-07_12.25.15-server.txt](https://github.com/itsmeow/betteranimalsplus/files/2454137/crash-2018-10-07_12.25.15-server.txt)

**Comment by itsmeow** [comment]
Fixed in Commit f542eb957733e8f6b50ea0ef688dfeff9a0c7d27 - Releasing v1.1.3 now as a patch.
