### ISSUE TITLE
Crash report during loading in the log

### ISSUE THREAD

**Issue by NickelHub** [itsmeow/betteranimalsplus#60]
**Describe what you were doing before the crash**
Loading game. Found that while looking in the log.

1. See log https://pastebin.com/vRaGBgJe

**Crash Log (REQUIRED)**
https://pastebin.com/vRaGBgJe

See full log for more information if disired
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/3223528/latest.log)

**Versions:**
 - Forge Version: (2838)
 - MC Version:1.12.2
 - Mod Version:6.0.1

**Comment by itsmeow** [comment]
Can I see your configuration file?

**Comment by NickelHub** [comment]
As far as I know, only thing I changed was adding biomesoplenty:wasteland to some spawns,
https://pastebin.com/eYwkWeJv

**Comment by itsmeow** [comment]
Can you confirm this happens if you delete/rename your config, open a world, and then restart the game and open a world again?

**Comment by P3rf3ctXZer0** [comment]
@NickelHub can I please see your mod list? You removed it from latest.txt

**Comment by P3rf3ctXZer0** [comment]
@itsmeow I will attempt to recreate it. As I have taken and interest in your mod. I will say right of the but his log has a surprising amount of errors. Also a read flag is Azanors Thaumcraft 6.

**Comment by itsmeow** [comment]
I'm gonna put this down to improper configuration. If this pops up again or anyone can find it with a default generated configuration, feel free to comment / re-open
