### ISSUE TITLE
Badgers not spawning naturally

### ISSUE THREAD

**Issue by viceroy369** [itsmeow/betteranimalsplus#61]
Version 6.0.1 (1.12.2)

Badgers do not appear to be spawning in the world naturally, at least not in my modpack: https://minecraft.curseforge.com/projects/gondwana 
which uses a Biomes O Plenty worldtype.

The config shows a long list of biomes from vanilla, biomes o plenty, novam terram and other biome mods where badgers are supposed to be spawning and yet I have never seen one in the wild, not even after putting their spawn chance right up to 100, not even in vanilla biomes.

I find every other animal from better animals+ easily even though the spawn rate is set much lower

They do however spawn normally from spawn egg which makes me think it's a problem with BA+ rather than a conflict with another mod as usually when it's some other sort of conflict the mob won't spawn at all or crashes the game.

To reproduce simply start a single player world in my modpack after a short creative flyover you will see that all the other BA+ animals are everywhere except for badgers.

What I expected? I expected badgers.

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/59162563-05138f80-8ac1-11e9-9887-8148998775be.png)
Found this boy after searching in a savanna for about 40 seconds. I'm gonna put this down to lack of luck / wrong biomes.
