### ISSUE TITLE
Crafting goat cheese consumes the bucket

### ISSUE THREAD

**Issue by Sweddy** [itsmeow/betteranimalsplus#62]
**The Bug** 
When 'Goat Cheese' is crafted with 'Goat Milk' and a mushroom, the bucket holding the 'Goat Milk' is consumed.

**To Reproduce** 
1. Put Goat Milk in a bucket using a Goat.
2. Use it to craft Goat Cheese with a mushroom.
3. Bucket is not returned.

**Expected behavior** 
The bucket is returned when Goat Cheese is crafted.

**Versions:**
 - Forge Version: 1.12.2-14.23.5.2837
 - MC Version: 1.12.2
 - Mod Version: 6.0.1

**Comment by itsmeow** [comment]
I swear I've fixed this, but I've confirmed it and will fix it.
