### ISSUE TITLE
Crashing when killing animals

### ISSUE THREAD

**Issue by X-Niter** [itsmeow/betteranimalsplus#64]
https://paste.dimdev.org/exusuwigif.mccrash

**Comment by X-Niter** [comment]
The crash log is that link. Player says he was killing the animals and then boom crashed! Not sure what the solution would be to this?

**Comment by itsmeow** [comment]
Looks like something is wrong with the config, and they were killing a fox? I need more information to be able to fix this.

**Comment by katubug** [comment]
I've got some good news and some bad news. The bad news is, my players are having the same crash. The good news is, we have some more data for you!

The crashes are identical: https://paste.dimdev.org/cugisigowu.mccrash

Reportedly it's affecting at least three of my players, although bizarrely I can't replicate it myself. There's nothing in the server log. The only thing the client log has that the crash report doesn't is

```
[21:08:51] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: null
```
and then it goes into the crash report.

My versions are:
betteranimalsplus-1.12.2-6.0.2
forge-1.12.2-14.23.5.2838-universal

Full modlist with versions is at the bottom of this post: http://enthusiasticraft.cf/modpack-update-1-5-3/

Let me know if you need any more information!

**Comment by itsmeow** [comment]
I think it may be that the entity is somehow getting an interaction during the process of dying / being removed. This causes the entity type to be null, which causes this crash as checking the tame items from the config requires the entity type.

**Comment by itsmeow** [comment]
Another possible cause is desync. Server/client config does not match. Anyways, I've implemented null checks and a packet syncing system for the taming items, so this is all nil point. Pushing 6.0.3 soon.

**Comment by katubug** [comment]
Thanks very much!
