### ISSUE TITLE
It seems like emisissive textures are on some mobs.

### ISSUE THREAD

**Issue by marharols** [itsmeow/betteranimalsplus#65]
It seems like emisissive textures are on some mobs such as the skeleton horse and the tarantula, it glows with shaders on.

**Comment by itsmeow** [comment]
Yes, we have emissives on the eyes of feral wolves, coyotes, hirschgeist, and tarantulas. I am aware of the shaders issue, but unfortunately it is not something I am aware of how to fix nor worry much about, as shaders and optifine often cause rendering issues and it should be expected. I will inform you should I ever solve this, but it is not something I will actively fix.
