### ISSUE TITLE
Invisible Fox Model

### ISSUE THREAD

**Issue by chibicheesepuff** [itsmeow/betteranimalsplus#66]
The fox model is not appearing 

To reproduce, spawn a fox from better animals +

[debug.log](https://drive.google.com/open?id=1eUMZKkZ0Gd_6h_d5VS_uNGTA8NVr8hSy)
the debug.log file is pretty large, not sure if this was what you were looking for

I expected the fox to be visible, especially since the game is able to recognize the model, just somehow its not loading in the wild.

![invisible fox](https://user-images.githubusercontent.com/52190635/60146871-d79d3600-9790-11e9-9b71-7c58a89c59be.png)

![using morph mod to transform the player into the fox model](https://user-images.githubusercontent.com/52190635/60146887-e388f800-9790-11e9-83de-0bd4a92b7ca4.png)

**Versions:**
 - Forge Version: forge-1.12.2-14.23.5.2768-universal
 - MC Version: 1.12.2
 - Mod Version: 5.0.1

I tried updating the mod to the latest version but the client side ended up crashing soon after logging into the server. Even so, for the small amount of time on the server the fox was still invisible. I have about 175 mods on this server and I'm really not sure what could be causing this graphical glitch.

**Comment by itsmeow** [comment]
Some other entity mod is registering invalid datamanager entries, which is corrupting the fox network data. Can I have the crash log from loading 6.0.0?

**Comment by chibicheesepuff** [comment]
[crash-2019-06-25_20.49.07-client.txt](https://github.com/itsmeow/betteranimalsplus/files/3327970/crash-2019-06-25_20.49.07-client.txt)

**Comment by itsmeow** [comment]
Okay. I have no idea what is causing that. But some mod has SEVERELY messed up the data manager registry. I don't know what to do really, something you have is not coded well at all.

**Comment by chibicheesepuff** [comment]
Huh, that's unfortunate. I'll see if I can remove some mods that might be causing some registry issues. But if that doesn't work, I can live with invisible foxes. Thank you for your help!
