### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by Gaber373** [itsmeow/betteranimalsplus#68]
Language:Italian

**Are you able to translate to this language?**
yes

**Comment by Gaber373** [comment]
[Ita.txt](https://github.com/itsmeow/betteranimalsplus/files/3411549/Ita.txt)

**Comment by Gaber373** [comment]
[Ita.txt](https://github.com/itsmeow/betteranimalsplus/files/3411649/Ita.txt)

**Comment by itsmeow** [comment]
Hey, thank you so much for the translation! The lang file has changed a little bit since you made that, if you could please update it?

**Comment by Gaber373** [comment]
I get the lang file from the latest version of the mod on curseforge ,i don t know where I can get the new file.

**Comment by itsmeow** [comment]
Right here on GitHub :) 
https://github.com/itsmeow/betteranimalsplus/blob/master/src/main/resources/assets/betteranimalsplus/lang/en_us.lang

**Comment by Gaber373** [comment]
i am dumb

**Comment by Gaber373** [comment]
Is the adjective Timber like Hardened or its like made of wood?

**Comment by itsmeow** [comment]
It refers to the timber wolf / gray wolf's coat color
https://en.wikipedia.org/wiki/Timber_Wolf
I believe it translates to just "grigio" from what I researched briefly just now.

**Comment by Gaber373** [comment]
[itaV2.txt](https://github.com/itsmeow/betteranimalsplus/files/3413568/itaV2.txt)
I am not sure if crab rave should be translated because it lose his sense

**Comment by itsmeow** [comment]
It's good, I'll just put crab rave back to english when I add it to the mod, thanks so much! I'll make sure to credit you in the description and all that. Looks good.
