### ISSUE TITLE
Lampreys don't release upon death

### ISSUE THREAD

**Issue by DoomRater** [itsmeow/betteranimalsplus#69]
**Describe the bug** (Required)
A lamprey that bites onto a player and then dies from no oxygen can be seen dying multiple times on a server.  Additionally, a lamprey that bites onto an Animania horse makes the horse unridable.
This may be related to the console spam "[15:10:08] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity"

**To Reproduce** (Required unless not known)
1. Spawn Animania horse and Lamprey
2. Let Lamprey bite horsey
3. Make sure horse is dragged out of water with lead
4. Lamprey will die, but you will not be able to mount the horse.
5. Log off server, log back in
6. Note Lamprey death particles upon login

**Expected behavior** (Required)
Once Lampreys die, they should not be mounted to an entity anymore.

**Versions:**
 - Forge Version: 14.23.5.2838
 - MC Version: 1.12.2
 - Mod Version: 1.12.2-6.0.2

**Additional context**
Animania version: 1.6.2

**Comment by itsmeow** [comment]
The inability to mount something with a lamprey attached is an unfortunate consequence of the passengers system prior to 1.13. Pushing a patch for the not detaching part now.
