### ISSUE TITLE
BA+ Mobs not spawning in modded biomes

### ISSUE THREAD

**Issue by cybercat5555** [itsmeow/betteranimalsplus#7]
**Describe the bug**
BA+ animals do not spawn in biomes added by other mods, despite the fact vanilla mobs and other modded mobs do spawn in those biomes

**To Reproduce**
Install BA+ along with another mod that adds biomes, tested with Traverse and Abyssalcraft (for its overworld biomes), check the modded biomes, no BA+ entities spawn within them.

**Expected behavior**
BA+ mobs would spawn in modded biomes just as vanilla animals and other modded animals do.

**Versions:**
 - OS: Windows 10
 - MC Version: 1.12.2
 - Mod Version: 1.1.3

**Comment by itsmeow** [comment]
Resolved in Commit 39347369edde13cfd21be867540873a4f2d3ca47
