### ISSUE TITLE
More farm and game animals

### ISSUE THREAD

**Issue by ChelonianEgghead** [itsmeow/betteranimalsplus#70]
**Type**
Entity (Mob)

I love the deer, goats, ducks, and pheasants in this mod. I'd just like to offer a few suggestions for some more animals.
-Turkeys
-Geese
-Bison
-Raccoons
-Beavers
I might be able to help a little with textures, as I have a little experience with GIMP, and I'd love to learn Krita.

**Comment by itsmeow** [comment]
@cybercat5555

**Comment by itsmeow** [comment]
> ducks, 
wait, what ducks?
