### ISSUE TITLE
[Server crash] Sidedness - clientside code on the dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [itsmeow/betteranimalsplus#73]
**Describe what you were doing before the crash**
Playing on the Adventures of Halk official server and I placed a Reindeer head and the server crashed.  

**Crash Log (REQUIRED)**
https://gist.github.com/ProsperCraft/9fc091320be796d32b8b8b8b2d26baea

**Versions:**
 - Forge Version: forge-1.14.4-28.0.23
 - Mod Version: betteranimalsplus-1.14.4-7.0.0

**Comment by ProsperCraft** [comment]
Reproduced here - https://paste.fedoraproject.org/paste/RZlLvwPQhAYqQohywc59-g
And here - https://paste.fedoraproject.org/paste/c0~D2k8vKTqEwnEPWqMxBw

**Comment by itsmeow** [comment]
Thanks for this, the 1.14 version is very much a WIP, so everything helps. I will fix this asap.
