### ISSUE TITLE
[1.12.2+] Mobs killed by lampreys should not drop items.

### ISSUE THREAD

**Issue by DWX12** [itsmeow/betteranimalsplus#74]
**Type**
Entity (Mob)

**Is your feature request related to a problem? Please describe.**
When lampreys kill mobs, the killed mobs should not drop anything. Currently items from mob deaths drop and could potentially pile up and cause lag.

**Describe the solution you'd like**
When a lamprey kills a mob, that killed mob should not drop any drops. 

**Describe alternatives you've considered**
Increase the despawn time for only those dropped items upon death from lamprey.

**Additional context**
Would like to see it for version 1.12.2 and onward.

**Comment by itsmeow** [comment]
Thoughts @cybercat5555 ?

**Comment by ProsperCraft** [comment]
Yes please, our server is getting trashed with items from this.

**Comment by itsmeow** [comment]
This is confirmed for 7.1.

**Comment by itsmeow** [comment]
Added in 7.1.0, out now

**Comment by DWX12** [comment]
Awesome! Thanks so much.
