### ISSUE TITLE
[1.14.4] Server crash - NPE - entity.ai.goal.BreedGoal.

### ISSUE THREAD

**Issue by ProsperCraft** [itsmeow/betteranimalsplus#76]
This just happened on the server, I saw you were fixing bugs so thought I better rush to report it -

It happened twice but I can't get anyone on the server to reply to me about how they did it.

https://paste.fedoraproject.org/paste/LPbrAYuxU4d6hfnLQ1sxYA
https://paste.fedoraproject.org/paste/3PEVwBoiM0HPfWdlxE3fPQ

betteranimalsplus-1.14.4-7.0.0
forge-1.14.4-28.0.29

**Comment by itsmeow** [comment]
Just tested this, appears to be a client crash, not a server crash.

**Comment by itsmeow** [comment]
Oh yeah, the crash is caused by breeding unnamed reindeer, I've identified it, fix soon.
