### ISSUE TITLE
Minor Bug -  Snowy wolf cape missing

### ISSUE THREAD

**Issue by Lictor000** [itsmeow/betteranimalsplus#77]
**Describe the bug** (Required)
Snowy wolf cape variant uncraftable.

**To Reproduce** (Required unless not known)
Install the mod.

**Expected behavior** (Required)
To be able to craft it. JEI just shows a glitched texture too. See below.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/39945124/62411976-bafbe580-b5fb-11e9-8c65-7d31144623fc.png)

**Versions:**
 - Forge Version: 14.23.5.2838
 - MC Version:1.12.2
 - Mod Version:7.0.0

**Comment by itsmeow** [comment]
Can I get the full log produced by starting the game to the main menu? Looks like a resource error of some sort, which usually produce outputs. Also, does wearing it still work?

**Comment by Lictor000** [comment]
Yes, you can still wear it. The model is fine, but it has the purple/black texture.
Not sure which log is the one that you need, so I'll attach both.
[debug.log](https://github.com/itsmeow/betteranimalsplus/files/3464156/debug.log)
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/3464157/latest.log)

**Comment by itsmeow** [comment]
Hmmmm... apparently I changed the ID and somehow this slipped by @cybercat5555 and batman without being noticed. That's... quite interesting. The ID is supposed to be betteranimalsplus:wolf_cape_classic but I changed it to betteranimalsplus:wolf_cape_snowy, which broke both the model loading and the recipes. tbh I was probably half asleep at 2am and missed this. This is quite embarrassing.

**Comment by itsmeow** [comment]
Resolved in 8902f62
