### ISSUE TITLE
[1.14.4] Server hard lockup. EntityLamprey.dismountEntity:L171

### ISSUE THREAD

**Issue by ProsperCraft** [itsmeow/betteranimalsplus#81]
**Describe the bug** (Required)
Server locked while I was sleeping and the watchdog kicked in and kicked out this crash log.

**To Reproduce** (Required unless not known)
Unknown.

**Log output/error (if present)**
https://gist.github.com/ProsperCraft/93fc422dcdae5ab6de1a18d855e6a656

**Versions:**
 - Forge Version:   forge-1.14.4-28.0.40
 - MC Version: 1.14.4
 - Mod Version: betteranimalsplus-1.14.4-7.0.1

**Additional context**
1.14.4 modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by itsmeow** [comment]
Fixed in 7.1.0, out now
