### ISSUE TITLE
[1.14.4] Server crash on load. ConcurrentModificationException: null

### ISSUE THREAD

**Issue by ProsperCraft** [itsmeow/betteranimalsplus#85]
**Crash Log (REQUIRED)**
Useless crash report- 
https://paste.fedoraproject.org/paste/TQHGYXFFDDWxfOXcJ5nDHQ
The actual stacktraces are in the logs.

Full log-
[debug.log](https://github.com/itsmeow/betteranimalsplus/files/3490273/debug.log)
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/3490274/latest.log)

The happened before but dismissed it as a fluke, happned again so reporting.

**Versions:**
 - Forge Version: forge-1.14.4-28.0.45
 - MC Version: 1.14.4(this question is redundant ;)
 - Mod Version: betteranimalsplus-1.14.4-7.0.2.1

**Comment by Shadows-of-Fire** [comment]
Caused here https://github.com/itsmeow/betteranimalsplus/blob/1.14/src/main/java/its_meow/betteranimalsplus/BetterAnimalsPlusMod.java#L80
We may need a non-parallel forge event for collecting biome features.

**Comment by itsmeow** [comment]
I don't understand how I'm concurrently modifying anything. Wat.

**Comment by Shadows-of-Fire** [comment]
Because that event is run concurrently with other mods which can also do the same thing, resulting in such an error.  You should schedule feature adds to the main thread using `DeferredWorkQueue`

**Comment by itsmeow** [comment]
Thanks for the help @Shadows-of-Fire :)

**Comment by itsmeow** [comment]
Fixed in 7.1.0, out now
