### ISSUE TITLE
Unknown bug/conflict

### ISSUE THREAD

**Issue by EightBlade** [itsmeow/betteranimalsplus#86]
**Describe the bug** (Required)
I have no idea. It's not a crash, but Minecraft seems to think there's a non-crash causing conflict.

**To Reproduce** (Required unless not known)
Unknown

**Log output/error (if present)**
https://paste.dimdev.org/yegaxuyabe.mccrash

**Expected behavior** (Required)
I expected it to work as normal. 

**Versions:**
 - Forge Version: 14.23.5.2836
 - MC Version: 1.12.2
 - Mod Version:7.0.2

**Additional context**

**Comment by itsmeow** [comment]
This looks like some sort of corrupted block packet giving crap values and causing a crash. I've never seen this before. You've said it's not a crash but the provided log is a crash log?

**Comment by itsmeow** [comment]
I need more details in order to do anything about this. What exactly happened before this? Has it happened again?

**Comment by itsmeow** [comment]
Closing this unless anyone else has something to offer.
