### ISSUE TITLE
Lammergeiger Pathing Issue

### ISSUE THREAD

**Issue by majidemah** [itsmeow/betteranimalsplus#88]
**Describe the bug** (Required)
I think you already know about some issues with Lammergeigers, but here's a very specific issue. Lammergeigers, if led south, fly without issue. If led north, they seem to hit an invisible wall - even in creative mode above any trees and attached to a lead (this is the same with a tamed lammergeiger just following without a lead) they will not follow me north. If led west, they will slide south on an invisible wall infinitely (as far as i could go and still see it). If led east, they will slide south a couple of spaces and then follow east without further issue.

**To Reproduce** (Required unless not known)
1. Spawn lammergeiger.
2. Tame lammergeiger.
3. Lead lammergeiger in a southern direction.
4. Lead lammergeiger in another direction.

**Expected behavior** (Required)
Lammergeigers to be able to travel....

**Versions:**
 - Forge Version: 28.0.45
 - MC Version: 1.14.4
 - Mod Version: 7.1.0

**Comment by itsmeow** [comment]
I knew 1.14 lammergeiers were borked, but not this borked. Thanks for the report.
