### ISSUE TITLE
Ice and Fire Compat

### ISSUE THREAD

**Issue by mxnmnm** [itsmeow/betteranimalsplus#89]
**Describe the bug** (Required)
Sharks are able hold dragons from ice and fire when it should be the other way around.

**To Reproduce** (Required unless not known)
1. Spawn in dragon
2. Spawn in shark
3. Put them both in the ocean (use iron chains if you're having trouble getting them down there)
4. Wait for the magic to happen

**Expected behavior** (Required)
I expected the dragon to hold the shark or at least for them to ignore each other

**Screenshots**
https://imgur.com/a/kMSwKF8

**Versions:**
 - Forge Version: 14.23.5.2838
 - MC Version: 1.12.2
 - Mod Version: Better Animals+: 7.1.0 Ice and Fire: 1.8.1

**Comment by itsmeow** [comment]
I'll add some size limit to sharks.
