### ISSUE TITLE
Crash when dying [1.14.4]

### ISSUE THREAD

**Issue by Gbergz** [itsmeow/betteranimalsplus#90]
**Describe what you were doing before the crash**
[Simply just dying by anything, fall. Mob etc.]

**To Reproduce**
Steps to reproduce the behavior (if possible):
1. Spawn 
2. Die.
3. Crashed

**Crash Log**
https://paste.ee/p/86QZZ

**Versions:**
 - Forge Version: 28.0.93
 - MC Version: 1.14.4
 - Mod Version:  1.14.4-7.1.0

**Comment by Wissi** [comment]
Can confirm as well.
Full crash log [here](https://gist.github.com/Wissi/b85c26c7be751b95f5c8c88e30b66879).
Great mod, Hope it helps so we can re-add the mod.
Using:
Forge-28.0.93
betteranimals-1.14.4-5.2.1.jar
Thanks.

**Comment by itsmeow** [comment]
That's very odd. This looks like a mappings issue but tbh could be Forge. Let me update my workspace. I'll get back to you if I can reproduce this

**Comment by itsmeow** [comment]
Huh, so Forge renamed getEntityData to getPersistantData, so.....
In this commit: https://github.com/MinecraftForge/MinecraftForge/commit/e1863383ffbd7696a1e3d29bf7be07a1b6872794
So for now go back to Forge 1.14.4-28.0.91 and see if that works still. I will patch this ASAP.
```
Build: 1.14.4-28.0.92 - Thu Sep 05 05:33:28 GMT 2019
	lex:
		Fix naming conflicts with official names.
```

**Comment by itsmeow** [comment]
Probably gonna wait to patch this as it may need changing again https://github.com/MinecraftForge/MinecraftForge/issues/6131 For now try 91 still and report back

**Comment by rfwainug** [comment]
91 is working just fine. Gave it a check.

**Comment by Anarchick** [comment]
Arf, I have a problem, I can't use 91 cause Optifine 1.14.4_HD_U_F4_pre4 does not work on it, need Forge 28.0.93 minimum and an other mod need 92 minimum :(

Do you have a hotfix ? I tried to quit the game but when I join I have again the "respawn menu"

**Comment by matsimoto** [comment]
@Anarchick If you need the pre3 version of Optifine, reply and I can provide a link (if that's allowed).

**Comment by itsmeow** [comment]
Okay I'm just gonna go ahead and release a patch since obviously it's a big issue.

**Comment by itsmeow** [comment]
Pushing a build out now.
