### ISSUE TITLE
 error has occurred during loading (bug?) i have forge 28.0.102

### ISSUE THREAD

**Issue by Gbergz** [itsmeow/betteranimalsplus#91]
**Describe the bug** (Required)
Not sure if this is a bug or whatever, but its not starting and spews out an error upon launch
"1 error has occurred during loading" 

**To Reproduce** (Required unless not known)
1. Start game
2. wait
3. Error has occurred during loading

**Log output/error (if present)**
LOGS [PASTEBIN](https://pastebin.com/xMqTNmV9)

**Expected behavior** (Required)
Loading the game as normal to the title screen.

**Screenshots**
[IMGUR](https://i.imgur.com/2Gmy48B.png)

**Versions:**
 - Forge Version: 28.0.102
 - MC Version: 1.14.4
 - Mod Version: 1.14.4-7.1.1

**Comment by itsmeow** [comment]
fixing asap

**Comment by itsmeow** [comment]
https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus/files/2782522
