### ISSUE TITLE
Picking up Feral Wolves with Carry On makes them invisible

### ISSUE THREAD

**Issue by Partonetrain** [itsmeow/betteranimalsplus#93]
**Describe the bug** (Required)
Picking up certain tameable mobs (Feral Wolf and Lammergier) with [https://www.curseforge.com/minecraft/mc-mods/carry-on](Carry On) and placing them back down makes them invisible. They are still there, fully functional, just not visible. They are still invisible after reloading the world.

**To Reproduce** (Required unless not known)
0. Have Carry On and BA+ installed
1. Spawn tameable, such as Feral Wolf
2. Shift-rclick on feral wolf
3. Rclick on ground

**Expected behavior**
Mob gets placed down, fully visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/19861808/64930524-37870400-d7f7-11e9-857b-6f1784b6936f.png)

![image](https://user-images.githubusercontent.com/19861808/64930536-4a013d80-d7f7-11e9-8b6d-2cede6373cff.png)
(oddly, wolf still has its eyes and outline)

**Versions:**
 - Forge Version: 28.1.1
 - MC Version: 1.14.4
 - Mod Version: BA+ 7.1.2 CarryOn 1.12.3

**Additional context**
May be a CarryOn problem, but given there isn't a crash I can't tell.

**Comment by itsmeow** [comment]
is there any log output?

**Comment by Partonetrain** [comment]
No log output. 

Songbirds have their textures set to the default when picked up too - maybe CarryOn doing something to the mob's data?

**Comment by itsmeow** [comment]
Seems so.

**Comment by Partonetrain** [comment]
Was messing around with other mobs and it just NPEs Loading entity NBT with vanilla foxes. https://github.com/Tschipp/CarryOn/issues/191
I think this is a result of a carryon bug

**Comment by itsmeow** [comment]
Yeah, the texture types are serialized to NBT so I assume their NBT serialization is broken. Closing this for now. Reopen if CarryOn says something is wrong here.

**Comment by Partonetrain** [comment]
@itsmeow Found out that this happens with [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)'s Ender-Farmer's Lead as well - it's possible that that mod's NBT serialization is *also* broken, but I believe it is more likely that BA+ mobs are not acting like these mods expect. What do you think?

**Comment by itsmeow** [comment]
I don't know enough about how CarryOn works to comment but I'm using pretty much the same code as the vanilla wolf for sitting, so.... I don't know.

**Comment by Partonetrain** [comment]
Sorry, I should've specified that I've narrowed it down to any mobs with multiple textures (I thought it was just tameables, but both the feral wolf and lammergeier do have several textures). Also, I've noticed there doesn't seem to be any texture field when I use `/data entity get <press tab to get the mob I'm looking at>` on a BA+ goat/feral wolf/lammergeir/songbird. This makes me believe BA+ isn't saving the texture number to the entity?

I'd like to re-open the issue but I can't because I didn't close it myself. 
Thanks for the support!

**Comment by itsmeow** [comment]
They use NBT to save the texture number under an integer field called `TypeNumber`

**Comment by itsmeow** [comment]
I have an idea. Maybe it's because I use `writeUnlessRemoved` and not `writeAdditional` to save the data.  Also gonna say this issue is connected to #100 since that is also an issue with CarryOn. Tschipp commented that carryon is not stable on 1.14, so I don't think this should be reopened.
