### ISSUE TITLE
Polish translation [PL]

### ISSUE THREAD

**Issue by ImperatorEdi** [itsmeow/betteranimalsplus#95]
Because I like this mod, and You helped me with game crash (sorry for my mistake).

**Language:**
Polish [PL]
**Are you able to translate to this language?**
This is my native language.

[pl_pl.txt](https://github.com/itsmeow/betteranimalsplus/files/3640768/pl_pl.txt)

**Comment by itsmeow** [comment]
Thank you! I will add this in the next update :D
Don't worry, it was a minor mistake to make.
