### ISSUE TITLE
Crashed While Loading The World

### ISSUE THREAD

**Issue by Timo2157** [itsmeow/betteranimalsplus#96]
**Loading Game**

1. Opened MC Launcher
2. Clicked Join For a Single-Player world
3. Then It said: The game crashed whilst ticking memory connection
Error: java.lang.IllegalArgumentException: Invalid message its_meow.betteranimalsplus.network.ClientConfigurationPacket

**Crash Log**
[crash-2019-09-23_18.21.00-server.txt](https://github.com/itsmeow/betteranimalsplus/files/3644404/crash-2019-09-23_18.21.00-server.txt)

**Versions:**
 - Forge Version: Forge 28.1.0
 - MC Version: 1.14.4
 - Mod Version: 7.1.2

**Comment by itsmeow** [comment]
This log implies another issue. Try finding your full latest.log or debug.log from the logs folder. I'm thinking another mod of yours is out of date and crashing

**Comment by itsmeow** [comment]
Those logs have no better animals plus installed.
