### ISSUE TITLE
Blocks don't drop in 1.14 (hof/trillium)

### ISSUE THREAD

**Issue by itsmeow** [itsmeow/betteranimalsplus#97]
**Describe the bug** (Required)
Trillium and Hand Of Fate don't drop in survival

**To Reproduce** (Required unless not known)
1. Place trillium/hof
2. Go in survival
3. Break with appropriate tool

**Expected behavior** (Required)
For one trillium or one hof item to drop when one is broken

**Versions:**
 - Forge Version: 28.1.0
 - MC Version: 1.14.4
 - Mod Version: 7.1.2

**Comment by Partonetrain** [comment]
Mob heads do not drop either.
