### ISSUE TITLE
Pheasant meat cannot be cooked in a Smoker

### ISSUE THREAD

**Issue by QuantumToasted** [itsmeow/betteranimalsplus#98]
**Describe the bug**
As it says on the tin. I am not sure what other animals in BA+ drop special meat, but i would assume this applies to them as well.

**To Reproduce**
1. Spawn a Pheasant
2. Kill it and collect its meat
3. Place it (and fuel) in a Smoker

**Expected behavior**
Pheasant meat to be cooked as all food items are cookable in a Smoker.

**Screenshots**
![image](https://user-images.githubusercontent.com/30324210/66262952-ecd22980-e7af-11e9-9cb8-922d6ba5c4ca.png)

**Versions:**
 - Forge Version: 28.1.30
 - MC Version: 1.14.4
 - Mod Version: 1.14.4-7.1.2

**Comment by itsmeow** [comment]
Something I hadn't thought about for 1.14 porting. Will do.
