### ISSUE TITLE
[1.14.4] incorrect key

### ISSUE THREAD

**Issue by ProsperCraft** [itsmeow/betteranimalsplus#99]
**Describe the bug** (Required)
Error showing up in console when trying to log in to a dedicated server.

**Log output/error (if present)**
https://gist.github.com/ProsperCraft/2c9eb52c8169fb639ac224264cc105fe

**Expected behavior** (Required)
The error not showing up.

**Versions:**
 - Forge Version: forge-1.14.4-28.1.39
 - MC Version: 1.14.4
 - Mod Version: betteranimalsplus-1.14.4-7.1.2

**Comment by itsmeow** [comment]
I don't know what causes this, but it's so minor that I've been ignoring it. It's not an error. If I come across a fix I will fix it but I will not actively work on this.
